### ISSUE TITLE
passenger-install-apache2-module fails unnecessarily on SSL certificate/key read error

### ISSUE THREAD

**Issue by marteber** [phusion/passenger#1251]
This issue is a reproduction of one posted in the phusion-passenger Google Group some days ago: https://groups.google.com/forum/#!topic/phusion-passenger/83hvsI00T00

What steps will reproduce the problem?
- framework installation is SEEK (http://seek4science.org/sites/default/files/seekdocs/doc/INSTALL.html) for a production environment (http://seek4science.org/sites/default/files/seekdocs/doc/INSTALL-PRODUCTION.html), run as an **unprivileged** user
- arrive at `bundle exec passenger-install-apache2-module` 

What is the expected output?
- the installation succeeds
- optionally, a warning is given that the program could not read Apache's SSL key files (because only the superuser has the required privileges)

What do you see instead?
- the installation aborts when checking the Apache configuration because the SSL key file cannot be read
- likewise for the certificate file
- comment: Why should it be necessary for Passenger to read either of the key/certificate files?

What version of Phusion Passenger are you using?
- 4.0.27 or 4.0.46 (for some reason, both are in the gemset)

Which version of Ruby, Rails, Node.js or Meteor are you using? On what operating system?
- ruby-1.9.3p547 (in rvm)
- Ubuntu 14.04 Server Edition

**Comment by FooBarWidget** [comment]
I believe this issue has been sufficiently addressed by the fix referenced in #1289.

The thing is: we need to execute a bunch of Apache tools in order to autodetect Apache settings. But those tools require root privileges even if they're not making changes. This is a fundamental issue in those tools that Passenger is not able to solve, so the best thing we can do is warning users that they need to provide root privileges.
