### ISSUE TITLE
4.0.53 + 2.1.0p0: Strange 500 server errors, if caching enabled

### ISSUE THREAD

**Issue by jelmd** [phusion/passenger#1315]
We see strange 500 server errors with passenger 4.0.53 and ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux], when config.action_controller.perform_caching is set to true. As long as PassengerLogLevel is not explicitly set, it seems to happen every 2nd request or a reload of a page. When PassengerLogLevel gets set to e.g. 7, it is slightly harder to get a 500 error, however, by clicking fast enough on the same link or clicking on the reload button of the browser it is still reproducable. As soon as  config.action_controller.perform_caching gets set to false, everything behaves as expected - no 500 errors anymore. When running w/o apache httpd (2.4.10)+passenger (i.e. just "rails server"),  config.action_controller.perform_caching setting doesn't matter, we've never seen a 500 error in this case.

So I guess, passenger has some threading issues, but since I just started working with it, I'm not sure, how to really find out, what's going on/to fix it. Extended log is avaliable via: http://iws.cs.uni-magdeburg.de/~elkner/tmp/passenger.log

**Comment by OnixGH** [comment]
@jelmd it's best to try the latest Passenger (v5). It has reworked internals and extended error logging. I don't see any threading problem in your trace, but there is a permission error `Disconnecting with error: application socket read error: Permission denied (fd=24, errno=13)`. Let us know if you that's working for you?

Btw. I noticed in the linked thread that you somehow seem to think passenger is heavyweight due to it being written in C++, this is actually opposite, C++ is about as *lightweight* as it gets and it's one of the reasons why passenger is so blazing fast ;)

**Comment by jelmd** [comment]
Hi OnixGH,

thanx for the hint. However, since we didn't have months to troubleshoot the issue, we moved to puma completely and are more than satisfied with it. It integrates nicely with the environment and even if we may get a problem, we can sort out the problem easily (in contrast to the C++ crap). Also with puma the complete setup gets quite a lot less complicated (we're doing auto aka unattended  setups of related LXCs incl. apache + ruby*) and get finished much much faster (~50%). So at least for us passenger is now just another, unneeded point of failure/overhead, which even makes troubleshooting much harder/impossible and thus we'll probably never get back to it (BTW, C++ and lightweight is a good one ;-)).

**Comment by OnixGH** [comment]
@jelmd actually we find and fix most issues within days, unfortunately your report apparently slipped under the radar while we were extremely busy with the passenger 5 release (although you could have gotten guaranteed responses and advice with the enterprise version).

Anyway, I'll close this issue since we're not sure it's a passenger issue considering the log states a permission error.
