### ISSUE TITLE
OPTIONS requests returning 400 when running multi-process Node/Socket.IO server.

### ISSUE THREAD

**Issue by tjlahr** [phusion/passenger#1361]
I'm running a simple Socket.IO server behind nginx 1.6.2 and Phusion Passenger 4.0.58 on Ubuntu 12.04.

When the server is in long-polling mode, the client sends an OPTIONS request after every successful poll. When Passenger is configured to run with a single node process, that request works fine and Socket.IO is able to serve the proper Allow* headers.

However, when Passenger is running >1 Node server, the sever consistently sends a 400 Bad Request back before the OPTIONS request ever reaches Node.

I tried to track down what was happening in nginx and passenger but couldn't figure it out. I'm assuming the problem is with Passenger and not nginx, because the requests work fine when running a single Node process.

The problem is reproducable on a Vagrant setup that I have here: https://github.com/tjlahr/passenger-affinity-problem

**Comment by FooBarWidget** [comment]
Thanks for providing a clearly reproducible Vagrant example. I'm investigating this issue now.

**Comment by FooBarWidget** [comment]
I couldn't get your app to work immediate.y Even if I ran it in Node.js directly, it didn't work because of 2 issues:

 1. You call `createServer(handler)`, but `handler` is a variable that hasn't been assigned yet at that point. Removing the `handler` variable and changing the handler function into an actual function fixed that.
 2. The app reads an index.html, but it's not in the server/app directory. Instead it's in the client/ directory, but that directory is not mounted into Vagrant. I fixed this by copying over index.html.

Let me know if my fixes are incorrect. The investigation continues.

**Comment by FooBarWidget** [comment]
I believe the problem here is a case of sticky session cookie race conditions.

Your index.html references "localhost.amplifydev.net" as the host for Socket.io connections. At the same time, your instructions tell me to access index.html through a different host name. This is intentional, right?

Normally, when your index.html and Socket.io server are on the same domain, the browser loads index.html first. This causes Passenger to set a sticky session cookie. The browser then proceeds with sending Socket.io requests. Because of the sticky session cookie, all requests end up in the same process, and everything goes well.

But if your index.html and Socket.io server are on different domains, then the sticky session cookie for index.html has no effect on the Socket.io domain. So as soon as index.html loads, the browser sends multiple Socket.io requests simultaneously -- all without sticky session cookies. The multiple requests are all routed to different processes (because of load balancing), so they all get a different sticky session cookie. This causes subsequent requests to fail because they are routed to the process that's associated with the last response that the browser has received.

There are two solutions to this problem:

1. Before calling Socket.io, ensure that your browser has loaded some random URL on the Socket.io domain which would set the sticky session cookie.

    For example, you could stick a `<script src="">` tag inside `<head>`. This script tag would load a dummy Javascript file from your Socket.io domain. This Javascript file is not a real file on the filesystem, but is just a dummy that is served by your Node.js app for the purpose of setting the sticky session cookie. Because the browser blocks everything until this script tag returns, this method guarantees that a sticky session is set for the Socket.io domain before the multiple simultaneous Socket.io connections are made.
2. Introduce IP-based sticky sessions in Passenger. But this is not something that we can do until 5.0.2.

**Comment by tjlahr** [comment]
Thank you for taking a look at this.

I apologize for the errors in my repo. There are some artifacts from my real project that I forgot to remove...
	- The handler function in app/server.js should not exist. Run a server in /client and access index.html through that.
	- The socket.io url in index.html should be "http://localhost:5656”. The “amplifydev" domain maps to 127.0.0.1 on my machine.

I’ve made those changes and pushed them to the repo.

Also, the client and the server are supposed to be on different domains in this example as the server.js file wasn’t supposed to serve the client.

As to your explanation, I have a couple of observations.

1. The initial socket.io GET requests happen sequentially, receive the cookie and consistently route to the same process.
2. It’s the OPTIONS requests that are failing every time. And I can tell it’s not a process routing error because the request never gets to the Node process. I’m convinced it’s passenger that’s returning the 400, not the application.
3. Unlike the GET and POST requests, the OPTIONS requests seem to never send request cookies. (Chrome 40) This is strange to me, and I don’t see anything in the spec that suggests this is deliberate.

I don’t think Solution 1 would fix #2 or #3 above. Solution 2, the IP-based sticky sessions, is interesting but won’t work when clients are NAT’d behind a firewall as many corporate and education networks are setup.

The solution we implement is to have nginx statically serve OPTIONS requests. This works fine, but I still think there's something buggy going on here either in how cookies are attached to OPTIONS or how passenger treats them.

Your call to reopen or not. Thanks again.

**Comment by FooBarWidget** [comment]
What I'm observing is that some combination of GET and OPTIONS requests are sent out simultaneously. Maybe it depends on the browser. But the gist is that the sticky session cookie must be set before any simultaneous requests are made.

I've confirmed that the 400 errors do in fact come from the application. I've also confirmed that putting the index.html and Socket.io on the same domain solves the problem, even when there are multiple Node.js processes.

But strangely, my solution number 1 does not work. It seems that the browser (Firefox at least...) does not send any cookies when sending OPTIONS requests. :(

So I do not think this counts as a Passenger bug, but it does need to be documented. That's why I've opened two issues for improving the documentation. Could you tell me how you configured Nginx to serve the OPTIONS requests? What do they return?

**Comment by tjlahr** [comment]
> I've confirmed that the 400 errors do in fact come from the application.
Interesting. How can I verify this? I'm listening to HTTP requests on the Node server and am not seeing the OPTIONS request coming in.

> It seems that the browser (Firefox at least...) does not send any cookies when sending OPTIONS requests.
I see this in Chrome 40 as well. I wonder what's going on...

>  I do not think this counts as a Passenger bug
Agreed.

> Could you tell me how you configured Nginx to serve the OPTIONS requests? What do they return?

```
      #inspired by http://enable-cors.org/server_nginx.html

      # if the request included an Origin: header with an origin on the whitelist,
      # then it is some kind of CORS request.

      if ($http_origin ~* (https?://[^\/]*\.(amplify\.com|amplifydev\.net|ampaxs\.com)(:[0-9]+)?) {
        set $cors "true";
      }

      # Nginx doesn't support nested If statements, so we use string
      # concatenation to create a flag for compound conditions

      # OPTIONS indicates a CORS pre-flight request
      if ($request_method = 'OPTIONS') {
        set $cors "${cors}options";
      }


      # if it's OPTIONS, then it's a CORS preflight request so respond immediately with no response body
      if ($cors = "trueoptions") {

        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Credentials' 'true';

        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since,X-Amplify-Metrics-API-Key,X-CSRF-Param,X-CSRF-Token';

        add_header 'Content-Length' 0;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        return 204;
      }
      #inspired by http://enable-cors.org/server_nginx.html

      # if the request included an Origin: header with an origin on the whitelist,
      # then it is some kind of CORS request.

      if ($http_origin ~* (https?://[^\/]*\.(amplify\.com|amplifydev\.net|ampaxs\.com)(:[0-9]+)?) {
        set $cors "true";
      }

      # Nginx doesn't support nested If statements, so we use string
      # concatenation to create a flag for compound conditions

      # OPTIONS indicates a CORS pre-flight request
      if ($request_method = 'OPTIONS') {
        set $cors "${cors}options";
      }


      # if it's OPTIONS, then it's a CORS preflight request so respond immediately with no response body
      if ($cors = "trueoptions") {

        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Credentials' 'true';

        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since,X-Amplify-Metrics-API-Key,X-CSRF-Param,X-CSRF-Token';

        add_header 'Content-Length' 0;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        return 204;
      }
```

Hope that helps!

**Comment by FooBarWidget** [comment]
> Interesting. How can I verify this? I'm listening to HTTP requests on the Node server and am not seeing 
the OPTIONS request coming in.

You can set passenger_log_level to 3 (or, if you're on version 5, to 7). This will cause Passenger to log all communication between itself and the app. You'll get *a lot* of log output so it can be overwhelming, but inside the log output you will see that it is the application that sends back the 400.

There is also no code inside Passenger for generating a 400, so it couldn't have been from Passenger anyway.

**Comment by tjlahr** [comment]
Great. If I learning anything new about OPTIONS, I'll pass it along.

Thanks for your help on this.

**Comment by FooBarWidget** [comment]
But the fact that you are able to work around it with a static Nginx response makes me wonder whether Socket.io supports OPTIONS requests at all. Maybe Socket.io is treating it as a regular GET/POST request and trying to serve it. I get the feeling that they didn't anticipate cross-domain requests.
