### ISSUE TITLE
5.0.0.beta3 and mod_xsendfile

### ISSUE THREAD

**Issue by distler** [phusion/passenger#1376]
There seems to be a conflict between 5.0 and `mod_xsendfile`.

I have an x-sendfile enabled Rails App (static resources are served via `mod_xsendfile` under Apache 2.4). With Passenger 5.0.0beta3, every time a request involving such a resource is made, the number of application instances goes up, until `PassengerMaxPoolSize` is reached, and the application stops responding to new requests.

* Turning off x-sendfile fixes the problem.
* Reverting to Passenger 4.0.59 also fixes the problem.

**Comment by distler** [comment]
Hmmm. I may be wrong about this.

Turning off x-sendfile seems to drastically ameliorate the problem of the App becoming non-responsive. But it doesn't eliminate it entirely. I will have to explore further...

**Comment by FooBarWidget** [comment]
Have you found any clues so far?

**Comment by distler** [comment]
Sorry. I haven't had the time to track down what's going on. I will try to get back to this and figure out what the pattern is, over the next few days.

My current suspicion is that the problem has nothing (direct) to do with `mod_xsendfile`, but that that simply exposes some other underlying issue.

**Comment by distler** [comment]
One thing that does seem to be the case (which is already a bug) is that `PassengerMaxInstancesPerApp` does not seem to be respected. I've set

```
PassengerMaxInstancesPerApp 3
PassengerMaxPoolSize  12
```

But, when this app becomes unresponsive, the number of instances is invariably larger than 3 ... which I would have thought would never happen.

**Comment by distler** [comment]
OK. Some progress. I can now reliably reproduce the problem by hitting 'reload', on a particular page, a few times.

The page contains a bunch of (previously uploaded) images which are (normally) sent using X-Sendfile. It doesn't seem to matter, however, whether X-Sendfile is enabled or disabled. Under 4.0.59, the page serves up fine. But, under 5.0.0.beta3, hitting reload a few times causes the App to freeze.

The difference seems to be whether the `FileController#file` action (which manages the uploaded images) terminates after sending the image (whether directly or using X-Sendfile). Under 4.0.59, it does, and the App can then handle other requests. Under 5.0.0.beta3, it seems to hang (waiting for something), and the App rapidly loses the ability to handle other requests.

**Comment by FooBarWidget** [comment]
5.0.0 RC 1 has been released (announcement still to be written, but the files are published). It fixes a bug whose symptoms sound a lot like what you're describing. Could you try RC 1?

**Comment by FooBarWidget** [comment]
Actually, just found out there's a problem with RC 1 that makes installation fail. I'm releasing RC 2 now.

**Comment by FooBarWidget** [comment]
RC 2 is released now.

**Comment by distler** [comment]
With RC2, the app seems to work fine with X-Sendfile disabled. But I can still get it to freeze with X-Sendfile turned on.

**Comment by FooBarWidget** [comment]
Maybe there are two issues, and one of them has been fixed, and now the other one is left. I'm marking this for 5.0.1. Further investigation is required.

**Comment by FooBarWidget** [comment]
I cannot reproduce your problem. mod_xsendfile seems to work fine with Passenger 5.

Let's continue investigating the problem. But I will need your help because I cannot reproduce the issue.

Could you set PassengerLogLevel to 7, then restart Apache?
And could you make a single request, using curl, to an endpoint that sets the X-Sendfile header?
Could you run passenger-status immediately afterwards and show me what you see?
Could you also attach your Apache error log file for me to inspect?

**Comment by distler** [comment]
I am trying out 5.0.1, now.

I will see what I can come up with.

**Comment by distler** [comment]
OK. I have an Apache Error log, per your suggestion (I used a browser rather than curl, but  I don't think that will matter). It's rather lengthy, though. Can I send it via email?

**Comment by FooBarWidget** [comment]
Sure. Please feel free to send it to hongli@phusion.nl.

**Comment by FooBarWidget** [comment]
It seems your app sets both X-Sendfile and Content-Length. In my test I didn't set a Content-Length header so I couldn't reproduce your issue.

How are you setting X-Sendfile? Are you using Rails's send_file method?

**Comment by distler** [comment]
> Are you using Rails's send_file method?

Yes, with the option `:x_sendfile => true`. As far as I understand, `send_file` automatically sets the `Content-Length` header, and I have not messed with that.

**Comment by FooBarWidget** [comment]
This probably won't make it to 5.0.2 because we have some pretty critical fixes that we want to release asap, but I can schedule this for 5.0.3.

**Comment by distler** [comment]
This bug is still labeled as `CannotReproduce`. Let me know if you need any more information.

>I can schedule this for 5.0.3.

That's fine.  4.0.59 continues to work fine.

**Comment by FooBarWidget** [comment]
I've removed the label. I'll have a better look at this soon.

**Comment by felixbuenemann** [comment]
It's not clear from the description, but this could be the same problem as #1404, so testing if it works on 5.0.2 would be a good.

**Comment by FooBarWidget** [comment]
No, it's not related to #1404. I've taken a look at his log files and it's pretty clear that it has got something to do with the headers the application sends. So I now know what the cause is, but I need to come up with a solution.

**Comment by ryreitsma** [comment]
I'm having the same issue with a Rack app that uses Rack::Sendfile, where static resources are served via mod_xsendfile in Apache 2.2. Every time a request is made, the number of application instances goes up, until PassengerMaxPoolSize is reached, and the application stops responding to new requests. I've tried Passenger 5.0.5, that doesn't work. 
Reverting to Passenger 4 works and removing the Rack::Sendfile also works fine.

Reproducing this error may be as simple as using this Rack app:

```ruby
require 'rack/contrib'

use Rack::Sendfile

map '/' do
  run Rack::File.new("/opt/www/whateverdirectoryyouwant")
end

**Comment by felixbuenemann** [comment]
I tried to reproduce with a rails 3.2 app that uses `send_file` with `x_sendfile_header = "X-Sendfile"` setting for apache, but couldn't replicate the problem.

Maybe it depends on the kind of apache2 worker used?

Versions:
```bash
dpkg -l |grep 'apache2\|passenger\|ruby2.1'|awk '{print $2" "$3}'
apache2 2.2.22-1ubuntu1.8
apache2-mpm-worker 2.2.22-1ubuntu1.8
apache2-threaded-dev 2.2.22-1ubuntu1.8
apache2-utils 2.2.22-1ubuntu1.8
apache2.2-bin 2.2.22-1ubuntu1.8
apache2.2-common 2.2.22-1ubuntu1.8
libapache2-mod-passenger 1:5.0.5-1~precise1
libapache2-mod-xsendfile 0.12-1
libruby2.1 2.1.5-1bbox1~preicse1
passenger 1:5.0.5-1~precise1
passenger-dev 1:5.0.5-1~precise1
passenger-doc 1:5.0.5-1~precise1
ruby2.1 2.1.5-1bbox1~preicse1
ruby2.1-dev 2.1.5-1bbox1~preicse1
```

**Comment by ryreitsma** [comment]
I have a completely different setup, so yeah, it may depend on the kind of apache worker being used. I'm running an up-to-date CentOS 6 server. 

Versions:

httpd.x86_64                         2.2.15-39.el6.centos  @base 
mod_xsendfile.x86_64          0.12-3.el6                   @epel/6Server

And I'm using RVM with Ruby 2.1.5 as default. Passenger is installed with the passenger gem and an auto-install for the apache module.

**Comment by FooBarWidget** [comment]
I don't think it depends on the Apache worker, but on what the app sends. Instead, I think the problem depends entirely on the value of the Content-Length header.

In @distler's case, things go wrong because his app sends a response with a Content-Length of non-zero, yet sends no body (presumably because of the X-Sendfile). @ryreitsma's example is similar: Rack::Sendfile sets Content-Length to the length of the file to send, yet sends no actual body.

I just tested with a new Rails 4.1 app, and it works fine. A `send_file` call in Rails generates a Content-Length header with a zero value.

So where does the Content-Length header with the non-zero value come from in @distler's case? distler, which Rails version were you using?

Anyway, the problem for me now is to determine what I should do with this. I could treat Content-Length as always being zero in case there is an X-Sendfile header. But the problem is that X-Sendfile is not a standard, it's just an Apache module. It seems nobody knows whether you are supposed to Content-Length to non-zero or not, so I don't know whether I'd be doing the right thing.

**Comment by FooBarWidget** [comment]
After some discussion with @OnixGH, we decided that it's best if we ignore Content-Length if X-Sendfile is set (and, analogously, X-Accel-Redirect). This is because it makes no sense to send an X-Sendfile response with a body, so we can always assume that the body is empty, in which case Content-Length doesn't do anything anymore.
