### ISSUE TITLE
Rails app run with Passenger get stuck

### ISSUE THREAD

**Issue by rubytastic** [phusion/passenger#1380]
Running an existing Rails application ( Rails 4, redis, sidekiq, SSE events ) it seems to get stuck on the rails 4 server side events. Whenever I enable these in my code the app just get stuck running with passenger 5 on osx. 

This problem is not existant when using Puma webserver.

Is there a known issue with passenger 5 and SSE rails 4 that prevent this to work correctly?

I have the passenger gem inside my Gemfile

**Comment by FooBarWidget** [comment]
There is no known problem with SSE. SSE should work fine. Does this demo work for you? https://github.com/phusion/passenger-ruby-server-sent-events-demo

**Comment by rubytastic** [comment]
The exact error is:

Processing by QueueController#events as text/event-stream
[ 2015-02-17 14:04:03.4467 88630/0x7fff7ab13300 agents/Watchdog/Main.cpp:386 ]: Some Phusion Passenger agent processes did not exit in time, forcefully shutting down all.
Completed 401 Unauthorized in 115666ms

I try the provided demo app thank you

**Comment by FooBarWidget** [comment]
The "Some Phusion Passenger agent processes did not exit in time, forcefully shutting down all" message is a red herring. This message may sometimes be printed shortly after you shutdown Passenger. It is a failsafe to ensure that it shuts down correctly (as opposed to freezing) even if the application misbehaves. Most likely, you shut down Passenger before, then you started Passenger again, and the message you're seeing is from the *previous* instance. The message is harmless so you should just ignore it.

The main issue here is why your app returns a "Completed 401 Unauthorized" and why it takes in 115666ms. As you can see in the demo, SSE works fine. So there is probably something in your app -- maybe not your app itself, but some library -- which relies on Puma-specific behavior and thus doesn't work well on Passenger.

This sort of thing happens all the time, because WebSockets and SSE are not standardized by the Rack specification, so many libraries in the ecosystem depend on server-specific behavior. [Here is a case study of such a problem](https://github.com/ngauthier/tubesock/issues/10#issuecomment-72539461). The Tubesock library for example was unintentionally written to rely on Puma-specific behavior, and so it didn't work correctly on Passenger. It also didn't work correctly on Unicorn because Unicorn happened to behave like Passenger in that particular area, but it did happen to work in Thin because it happened to behave like Puma in that particular area.

**Comment by FooBarWidget** [comment]
Hi @rubytastic, has the problem been solved for you? Can I close this issue?

**Comment by OnixGH** [comment]
No feedback received, assuming resolved.
