### ISSUE TITLE
Documentation of the JSON API usage

### ISSUE THREAD

**Issue by dmitry** [phusion/passenger#1407]
Is there are a documentation how to use admin JSON API, for example requesting the server status information?

I found this code, but still cannot understand how to access it:
https://github.com/phusion/passenger/blob/0f27be53c246e6ad206063bd6b3a6c23770ded24/ext/common/agents/HelperAgent/AdminServer.h#L569

**Comment by OnixGH** [comment]
Hi @dmitry, thanks for your interest! We're currently working on better documentation for the HTTP JSON API. You can expect a blog post about this topic in the near future.

The commands you found in the AdminServer are actually used under the hood by various passenger scripts from passenger/bin/, for example if you run "passenger-status --show=server" the script outputs the result of a get /server.json (through a UNIX domain socket, with authentication).

**Comment by dmitry** [comment]
@OnixGH thanks! Looks like now I understand how I can use it.

**Comment by FooBarWidget** [comment]
What @OnixGH said. :) Until our blog post has been written, you can refer to the following files to learn how the API works:

 * https://github.com/phusion/passenger/blob/release-5.0.1/lib/phusion_passenger/config/restart_app_command.rb#L199-L206
 * https://github.com/phusion/passenger/blob/release-5.0.1/lib/phusion_passenger/config/detach_process_command.rb#L91-L104
 * https://github.com/phusion/passenger/blob/release-5.0.1/bin/passenger-status#L123-L132

Because the server listens on a Unix domain socket and not a TCP socket, you cannot use curl to make requests. But we've written a tool to help you with that: `passenger-config admin-command`. You can run `passenger-config admin-command --help` to learn more.

For example, running the following will give you the exact same results as `passenger-status --show=server`:

    passenger-config admin-command GET /server.json

**Comment by grahamb** [comment]
You actually can use curl to make requests to the API. curl v7.40.0 added the `--unix-socket` option.

```
curl --unix-socket /tmp/passenger.4Zi3cu5/agents.s/server_admin "ro_admin:PASSWORD@localhost/server.json"
```

The path to to the socket will differ. The passwords are in /tmp/PASSENGER_INSTANCE/[read_only_admin_password.txt | full_admin_password.txt]

**Comment by dannykopping** [comment]
This file is also pretty useful for seeing what's available: https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/agent/Core/ApiServer.h
