### ISSUE TITLE
PassengerAgent invoked oom-killer

### ISSUE THREAD

**Issue by proigor** [phusion/passenger#1433]
Hi!

Please, help me to understand this error. I found it in syslog
http://pastie.org/10024775

I'm using sidekiq and it looks like it receives oom-killer. Looks like this ruby process took too much memory. But any help much appreciated.

I'm using latest passenger, ruby 2.0.0p598, sidekiq 3.3.2.

**Comment by FooBarWidget** [comment]
Mar 13 13:18:41 newmth kernel: [630250.830734] Out of memory: Kill process 16886 (ruby) score 750 or sacrifice child

This log output means that your Ruby application -- with PID 16886 -- used too much memory. If you look for PID 16886 in the output, you'll find this:

    Mar 13 13:18:41 newmth kernel: [630250.830637] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
    ...
    Mar 13 13:18:41 newmth kernel: [630250.830727] [16886]  1001 16886  1257320   756433    1669        0             0 ruby

Your Ruby app used 756433 KB of RSS memory, or about 750 MB.

    Mar 13 13:18:41 newmth kernel: [630250.830790] Killed process 16886 (ruby) total-vm:5029280kB, anon-rss:3025732kB, file-rss:0kB

Here we see that the kernel decided to kill 16886 in an attempt to free memory.

    Mar 13 13:18:41 newmth kernel: [630250.830457] PassengerAgent invoked oom-killer: gfp_mask=0x2084d0, order=0, oom_score_adj=0

And finally, this first line is a red herring. The kernel tries to trace the cause of the memory problem to its root. Because your Ruby app was spawned by PassengerAgent, the kernel thinks the entire problem was caused by PassengerAgent. In a sense, the kernel is right -- if PassengerAgent never spawned your app in the first place, this wouldn't have happened. But that's a useless conclusion.

So Passenger is not causing problems here. Your app is probably leaking or bloating memory, and you need to fix that. Or, if you're using Passenger Enterprise, you can use [passenger_memory_limit](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerMemoryLimit).

**Comment by proigor** [comment]
Thanks a lot!

**Comment by synth** [comment]
@FooBarWidget If ruby is leaking memory and the kernel kills passenger ruby processes, will passenger respawn? Our server went down today because of kernel killing ruby processes when memory was exhausted. Trying to learn how to avoid this.

**Comment by CamJN** [comment]
Yes, Passenger replaces killed processes up to the min instances count.
