### ISSUE TITLE
Monitor passenger

### ISSUE THREAD

**Issue by proigor** [phusion/passenger#1462]
Hi!

Sorry for disturbing you. But today's morning I saw such passenger status output:

passenger-status
Version : 5.0.6
Date    : 2015-04-01 05:23:20 +0000
Instance: 2UdIqiQq (Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f Phusion_Passenger/5.0.6)

----------- General information -----------
Max pool size : 6
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/u/apps/mth/current#default:
  App root: /u/apps/mth/current
  Requests in queue: 0
  * PID: 2747    Sessions: 0       Processed: 9341    Uptime: 10h 23m 39s
    CPU: 1%      Memory  : 823M    Last used: 2s ago
  * PID: 2853    Sessions: 0       Processed: 334     Uptime: 10h 22m 42s
    CPU: 0%      Memory  : 279M    Last used: 1m 44s
  * PID: 2969    Sessions: 0       Processed: 38      Uptime: 10h 21m 9s
    CPU: 0%      Memory  : 136M    Last used: 1h 17m 1
  * PID: 6129    Sessions: 0       Processed: 20      Uptime: 9h 43m 49s
    CPU: 0%      Memory  : 90M     Last used: 2h 15m 3
  * PID: 6229    Sessions: 0       Processed: 11      Uptime: 9h 43m 19s
    CPU: 0%      Memory  : 76M     Last used: 2h 15m 3
  * PID: 8256    Sessions: 0       Processed: 8       Uptime: 2h 54m 21s
    CPU: 0%      Memory  : 61M     Last used: 2h 15m 3

As you can see PID: 2747 processed a lot more request then other processes and also it uses again much more memory then others. Is it a normal behaviour?

For my system it took a lot of memory and I got many OOM-killer calls for other ruby processes.
I'm running passenger 5.0.6, ruby 2.2.1 and rails 4.2.1. 

I had to manually restart passenger via 'passenger-config restart-app' in order to free memory.

Please, suggest me the best way to monitor passenger via monit and restart if it takes more then 1gb of memory. If there is nothing else I can do in such situation.

**Comment by OnixGH** [comment]
@proigor to see if there is anything abnormal please also run this command when you think memory use is maybe too high:
passenger-status --show=requests

It is not abnormal if one application processed more requests, it's usually because the server has enough speed to handle it with just one or two apps. You can see for example that PID 6129, 6229 and 8256 were not needed in the past 2 hours 15 minutes.

You can tell Passenger to automatically save memory when the server doesn't need so many applications by using the PassengerPoolIdleTime option:
https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerPoolIdleTime (the default is 300, which is 5 minutes). In the situation you posted Passenger would have stopped PID 2969, 6129, 6229, 8256 and freed almost 400 MB of memory.

**Comment by proigor** [comment]
@OnixGH You are right, PassengerPoolIdleTime was set to 0 in my config. I've removed it and it looks fine now. Saving 400MB will be really great! :)

I'll monitor and surely run --show=requests. I still wonder if this is a good idea to monitor and restart app if it uses big % of overall resources.

**Comment by OnixGH** [comment]
@proigor it's possible that what's happening here is that the application is leaking memory. If you are worried about that you could use the PassengerMaxRequests option: https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerMaxRequests

This will let Passenger automatically restart applications after a certain number of requests. Restarting always takes some time (depending on the app) and some unlucky users might have to wait for it if they arrive in a calm period where there are no other apps in the pool waiting to serve them. But it's still faster than restarting all of Passenger, then everyone has to wait for sure.

**Comment by OnixGH** [comment]
P.S. the show=requests looks healthy to me, no sign of Passenger memory leaks there ("active_memory" stays around 0, just like it should after the fix in 5.0.6).

**Comment by proigor** [comment]
Thank you!
