### ISSUE TITLE
passenger 5.0.6 still caching env variables across requests

### ISSUE THREAD

**Issue by decasia** [phusion/passenger#1479]
Unfortunately, on further testing of passenger 5.0.6, I still see an env variable issue closely related to #1446 and shibboleth authentication. In essence, the Shibboleth env variables (`uid`, `mail`, etc.) get populated on the first request, and then they are cached for subsequent requests, even when these subsequent requests are from different users. The `REMOTE_USER` variable, however, still gets passed through correctly. This ends up providing the rails app with inaccurate and inconsistent information about the user session.

I did some debugging with two users, one called "eli" and the other called "hcs2". The first request was from "eli" (and shows up correctly), the second was from "hcs2" and is inaccurately reported as being from "eli" (because the `uid` env variable is cached).

Rails application log:

```
[2015-04-15 17:28:25 -0500] [eli] [600340d3] mail: eli@uchicago.edu
[2015-04-15 17:28:25 -0500] [eli] [600340d3] REMOTE_USER: eli@uchicago.edu

[2015-04-15 17:29:14 -0500] [eli] [3829e9f4] mail: eli@uchicago.edu
[2015-04-15 17:29:14 -0500] [eli] [3829e9f4] REMOTE_USER: hcs2@uchicago.edu
```

Apache log for the same requests:

```
128.135.xx.xxx - eli@uchicago.edu [15/Apr/2015:17:28:25 -0500] "GET /test_app HTTP/1.1" 200 4133 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"

128.135.xx.xxx - hcs2@uchicago.edu [15/Apr/2015:17:29:14 -0500] "GET /test_app HTTP/1.1" 200 10675 "https://shibboleth2.uchicago.edu/idp/profile/SAML2/Redirect/SSO" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
```

It sure looks like a caching issue to me. I didn't catch it in my initial testing because I didn't initially test with multiple users. Is there anything else I can do to help debug or fix?

/cc @jrochkind

**Comment by decasia** [comment]
I'd also be interested in helping to get some test coverage added to Passenger around this issue -- if it's not a feature that the core developers are using themselves, then test coverage is the best way to keep this issue from recurring.

**Comment by FooBarWidget** [comment]
I think this is the same as issue #1472. We were caching things that shouldn't be cached. Can you check whether the stable-5.0 branch fixes your problem?

Increasing test coverage is generally a good idea, but I don't think it would have helped here. We were intentionally caching some things, and later we find out that caching them is a bad idea.

**Comment by decasia** [comment]
Oh, great. I will test from stable-5.0. Thanks for the excellent support, @FooBarWidget !

**Comment by decasia** [comment]
Confirmed, stable-5.0 fixes it! I imagine this will come out in 5.0.7?

**Comment by FooBarWidget** [comment]
Yes.

**Comment by jrochkind** [comment]
I am still having trouble with Shibboleth environmental variables reliably making it through, in Passenger  5.0.11 (apache) on my staging server. 

It is hard to reproduce, sometimes it works sometimes it doesn't, with no clarity as to what causes it. I suspect Passenger is still caching something somewhere, and it depends on what passenger process you get load balanced to. 

I am still stuck on passenger 4.x in production because of this. 

I think there might be a way to tell Shibboleth to pass it's info in `x-` HTTP headers instead of ENV, so I might investigate that, since I love passenger and want to keep using it. But that's really undesirable, it's harder to keep such a system secure against spoofing, you need to put in guards to make sure none of the headers Shibboleth is using can be set by the client.

**Comment by mberkowski** [comment]
> I think there might be a way to tell Shibboleth to pass it's info in x- HTTP headers instead of ENV

This is done via [`ShibUseHeaders`](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPApacheConfig#NativeSPApacheConfig-Server/VirtualHostOptions) if anyone is in need of a workaround.

I'm currently working through this with Passenger 5.0.15 and Node.js, wherein Shibboleth attributes are being placed once into `process.env`, and remaining there unchanged all clients. That makes sense in the context of normal process environment variables, but is obviously undesirable for authentication.

**Comment by FooBarWidget** [comment]
> I'm currently working through this with Passenger 5.0.15 and Node.js, wherein Shibboleth attributes are being placed once into process.env, and remaining there unchanged all clients. That makes sense in the context of normal process environment variables, but is obviously undesirable for authentication.

Do you not see the values in the HTTP request headers?

**Comment by mberkowski** [comment]
@FooBarWidget I do see the values in HTTP request headers only if I configure Shibboleth with `ShibUseHeaders`.  This is somewhat different between Node and Rails - with Rails, `request.env` is receiving up to date values from Shibboleth environment variables without requiring conversion to HTTP headers. Inexperience with Node is a hindrance for me here, so this may be expected behavior.  Node's `process.env` receives a _static_ set of Shibboleth variables if Apache is restarted while a client is connected.

**Comment by jrochkind** [comment]
Configuring Shib to pass values in HTTP headers instead of in ENV is recommended against, it is only a workaround. 

There are a variety of things in apache that are built to do per-request ENV, it's not just Shib, Passenger needs to respect per-request ENV in order to avoid interfering with apache.

**Comment by mberkowski** [comment]
Here's an example to illustrate what is happening with Node.js and Passenger 5.0.15, without needing to involve the Shibboleth service provider daemon.  

There's a use case in Apache is to set an environment variable via `RewriteRule` based on some property of the inbound HTTP request.  For example:

```
# Set an env var based on part of the URI
RewriteRule path/([^/]+) - [E=subpathvar:$1]
```

Passenger sets the variable `subpathvar` in `process.env.subpathvar` where it persists and loses any association to the HTTP request which set it.  I have yet to find Node.js middleware that handles or respects per-HTTP-request env vars as Apache can provide (and Rack can handle), but Passenger should not be setting and persisting them for the Node process itself.

Bringing Shibboleth (mod_shib) into the pipeline results in one user's attributes being set as persistent process-level env vars.

**Comment by jrochkind** [comment]
Are there any ideas of what's going on or plans to fix it?

I'm still on Passenger 4 because of this. And now I'm running into an error on passenger 4, with a C stack trace where passenger dies... but I suspect you aren't interested in errors reported on passenger 4 at this point, outdated software. 

I've been a huge advocate of Passenger in public forums, it's always been great to me. I would be sad to have to switch to puma or something else because of this issue. I need reliable per-request Apache ENV to be set, for our enterprise sign-on system to work properly.  If it does what it appears to be doing here re-using cached ENV, that will result in people being authenticated as other users them themselves, which is obviously a pretty disastrous consequence which can't be risked.

**Comment by FooBarWidget** [comment]
Let me look into this again for 5.0.21.

**Comment by FooBarWidget** [comment]
This issue is scheduled for tomorrow.

**Comment by FooBarWidget** [comment]
@jrochkind, @mberkowski, I get the feeling that you two are talking about entirely different issues. Maybe it's because we are mixing up terminology, so let's clear that up.

First of all, let's assert that there are **per-request environment variables**. These can be set on a per-request basis shibboleth authentication, `mod_rewrite`, etc. These variables appear inside the Apache module as `r->subprocess_env`.

Let us also assert that there are 2 different stores for what we informally call "environment variables", but they actually access very different kinds of variables:

 1. System environment variables.
     * These are accessed in C using `getenv()`
     * These are accessed in Ruby through the top-level `ENV` constant
     * These are accessed in Node.js through `process.env`.
 2. Per-request environment variables, as described above.
     * These are accessed in Ruby through the Rack `env` object. When using Rails, these are also accessed through `request.env`.
     * These are not accessible in Node.js. The per-request environment variables are stored *once* inside `process.env` during process startup, but they are never updated, so there is effectively no way to access per-request environment variables in Node.js.

@mberkowski Your problem is that per-request environment variables are not accessible in Node.js, right?

@jrochkind Which of the following statements is what you mean?

 1. You mean that per-request environment variables are not accessible through the top-level `ENV` Ruby constant.

     If this statement is what you mean, can you answer these questions too?

     * Did you know that `ENV` is meant for accessing system environment variables, not per-request environment variables?
     * If the answer to the previous question is "yes", does that mean you want per-request environment variables to be accessible through `ENV`?

 2. You mean that per-request environment variables are not accessible through the Rack `env` object.

**Comment by FooBarWidget** [comment]
@mberkowski I have fixed your problem in commit eaffaf53. See https://www.phusionpassenger.com/library/indepth/nodejs/apache_per_request_envvars.html for documentation.

@jrochkind I will start working on your problem once I've received additional information from you, as per my previous comment.

**Comment by mberkowski** [comment]
@FooBarWidget Thank you for the update. I will examine the new commit's behavior today.  To your summary of the Node.js per-request env issue above:

> The per-request environment variables are stored once inside process.env during process startup, but they are never updated, so there is effectively no way to access per-request environment variables in Node.js.

An accurate summary. I would add here for sake of capturing it that certain variables like those set for user-specific or request-specific purposes were being set on `process.env`, potentially leaving user or auth data there.

It looks like you have addressed this in documentation:

> process.env does not change, so it must not be used for accessing per-request environment variables whose values may change on a per-request basis. For example, do not call process.env.SSL_SESSION_ID because SSL_SESSION_ID changes on a per-client basis.

I'll build 5.0.21 and provide more feedback soon, Thank you.

**Comment by jrochkind** [comment]
Thanks @FooBarWidget. This stuff is confusing to me it's true, I may have gotten things mixed up in muy previous reports, and on top of that the undesirable behavior I was seeing is hard to reproduce reliably which makes it even more confusing. But here's what's up:

* There are per-request environmental variables, set by apache. In my case, set by the Shibboleth apache module on a per-request basis, although I occasionally use other per-request environmental variables set by apache in manual conf files too. 
* I have indeed been accessing them in Rails via `request.env`
* In Passenger 4, this worked fine. 
* In at least some versions of Passenger 5, it did not -- meaning specifically that what I got from `request.env['some_variable']` was sometimes wrong, it appeared to be a cached value from a previous request, rather than the appropriate value for the present request. Sometimes it was nil when it should not have been nil; or non-nil when it should have been nil; or value `x` when it should have been value `y`. 

But this was hard to reproduce, sometimes it would be right, sometimes it would be wrong. It may or may not be related to whether or not there were multiple applications running in the same apache-passenger instance, I'm not sure. 

So that's what my experience has been. Does any of that make any sense at all?

**Comment by FooBarWidget** [comment]
@jrochkind Yes I understand your problem now. I have checked earlier today whether Apache per-request environment variables are accessible though the Rack env object (and thus through `request.env`), and they are. I have also confirmed that they are properly dynamically updated. However I will conduct a code review to see whether I have missed anything.

**Comment by FooBarWidget** [comment]
@jrochkind You mentioned that 5.0.11 was the last release in which you observed the problem. How exactly did the problem manifest? Did your enterprise sign on system confuse the user's identity with that of someone else?

**Comment by jrochkind** [comment]
I use our enterprise sign-on system in my own apps, via the Apache shibboleth plugin.  

The apache shibboleth plugin and the enterprise sign-on system didn't seem to be confused. If I told the apache shibboleth plugin to 'protect' a certain URL in apache (with my app behind it), then accessing that URL would redirect me to enterprise sign on, and then back to the original URL, before letting me access the original URL (and get to my app). 

My app then gets the identity of the now authenticated visitor via a `request.env`, specifically `request.env['eppn']`. 

The problem was that my app would get `nil` from `request.env['eppn']`, even though it should have been set by the apache shibboleth module.  I think, now that I think back, that the only thing I observed was `nil` when it should have been a filled out value.  If it was a caching issue as had been suggested, i was _worried_ about getting the _wrong_ non-nil value for `request.env['eppn']` which would of course be disastrous, but I'm not sure if I ever actually observed that (it's hard to test, since I don't have multiple credentials to my enterprise SSO to test with, I'd have to try to mock things up somehow). 

The problem was hard to reproduce. Sometimes it would happen and sometimes it wouldn't, and it wasn't clear to me exactly what steps might lead to a reproduction. I tried experimenting with only 1 app in my passenger app pool, to see if that would make it go away, but I think it still reproduced with enough trials. I tried experimenting with different Passenger config, including turbocache settings and another config I've lost the name of now that was meant to tell Passenger which 'app' was which in various locations. I think I was able to reproduce under all combinations I tried.  I do have multiple passenger apps in the same apache virtual host with multiple `PassengerBaseURI` at sub-url's -- i started to suspect that maybe if I only had ONE passenger application running on the whole apache instance (or apache virtual host), the problem would go away -- but I'm not sure I ran enough attempts to see if the problem might reproduce anyway eventually. 

Switching back to Passenger 4, with all other components unchanged, is one thing that seemed to reliably make the problem no longer reproducible. 

At some point back then, I had spent enough time trying to investigate this and needed to get work done, and just switched back to Passenger 4 and stopped investigating. 

Hope this helps. Sorry, I think my original reports were unclear about some things I was confused about too.

**Comment by FooBarWidget** [comment]
Thanks for the clarification, and sorry again for the hassle caused so far.

I have indeed found a caching issue through a code review. It has got nothing to do with number of processes, base URIs, etc. The issue is this: when the first application process is spawned, the per-request environment variables that were active at that time, will be stored in a cache.

 * Any subsequent requests that contain per-request environment variables won't use the previously-cached variables,
 * but any subsequent requests that DON'T contain per-request environment variables WILL use the previously-cached variables.

You should be able to reproduce it with 5.0.20 as follows:

 1. Ensure that PassengerPreStart is off. Number of processes, base URI, etc. do not matter.
 2. Ensure that the first request to your application is a request that will set Shibboleth environment variables.
 3. Make another request to your application, this time to an endpoint that doesn't set any environment variables, not even variables by `mod_env` or `mod_ssl`.
 4. You should now observe that your app sees the Sibboleth environment from step (2).

I've fixed this in the `GH-1479` branch. If you follow the above steps using that branch, then you should see that the problem is solved.

**Comment by jrochkind** [comment]
@FooBarWidget awesome! I'm glad you actually found a likely issue, that gives me more confidence it'll be fixed of course! I don't know if I'll have time to reproduce against current Passenger and new branch this week though, I'm sorry!

And that repro script you have (make sure the FIRST request sets request env, but the NEXT does not) makes me see how I failed to reliably reproduce, as I never thought to control the order of those in that way. 

As a larger issue, this does make me wonder whether the performance benefits introduced from all of this caching in Passenger 5 -- which will generally be very very minor in any real app where Passenger overhead dwarfs actual app load -- are worth it, when they introduce code/logic complexity that makes bugs like this possible, bugs which are very hard to reproduce reliably and track down and fix and can take many months to find and fix.

**Comment by jrochkind** [comment]
Also, in my typical setup, while shib request ENV variables may or may not be set in a given request, I suspect I have _no_ requests/URLs that will set _no_ request env variables, not even mod_env or mod_ssl.  Or at least it'd be hard for me to track these down, I'm not used to having to think about it. 

But it still does sound to me like you've likely found the bug that is responsible for the behavior I was seeing. Thank you.

**Comment by mberkowski** [comment]
@FooBarWidget I've had some time to build from master and test it with Node.js & mod_shib.  The secure headers and `!~Passenger-Envvars` feature work as expected.  However, when the Node application starts up, environment vars from Apache specific to the request are still being set and persisted directly on `process.env`.

This means that in a situation when Passenger was gracefully restarted, if for example the first inbound HTTP request after restart carried authentication info that was propagated into env, those vars still leak onto `process.env`.  

Example - mod_rewrite sets a user-specific variable:

```
RewriteEngine On
RewriteRule ^ - [E=user_reqhost:%{REMOTE_HOST}]
```

App is restarted
```
$ passenger-config app-restart
```
`process.env.user_reqhost` now permanently contains the first user's value.

You warned against this persistence in the documentation, but it still has the potential to leak sensitive data.  Since those environment variables was concatenated into `!~passenger-envvars` and their names are known, could they be correspondingly unset from the node process env?

**Comment by FooBarWidget** [comment]
Those variables are supposed to be persisted into process.env. It's necessary for making `SetEnv` work as expected. How about unsetting sensitive variables in your application?

**Comment by mberkowski** [comment]
I can unset the request-specific ones in application code, but I question whether they should ever be set on the Node process environment. because they are intended only for use by the request, of which there are of course many concurrent ones, and   

Those set by mod_env `SetEnv,PassEnv,` (if I read [the Apache docs correctly](https://httpd.apache.org/docs/2.2/env.html)) are process vars and appropriate for `process.env` in Node. But vars set by mod_rewrite or mod_setenvif aren't relevant to the Node.js process.  If there is any way for Passenger to differentiate between the two use cases it would be beneficial.

**Comment by FooBarWidget** [comment]
Unfortunately there is no way to differentiate between those two. Apache uses the same store for storing them, namely `r->process_env`.

The best thing I can come up with is to ignore `r->process_env` entirely, and to introduce a new Passenger configuration option specifically for setting OS environment variable, replacing `SetEnv`. However, I have some doubts about whether this is a good idea because most users expect `SetEnv` to work. It will confuse them if it doesn't.

**Comment by jrochkind** [comment]
It sounds like the problem is just with Node.js, that it provides no way to for request-specific env to be sent to it? Yes, please don't break SetEnv (and shibboleth!) for platforms where request-specific env works, just because one platform (node.js) doesn't properly support it.

**Comment by mberkowski** [comment]
It doesn't sound like the proposed feature would break Shibboleth, but breaking SetEnv does seem like a significant problem.  For Shibboleth there is still always the ability to depend entirely on headers and disable env. It's undesirable and routinely recommended against but Shibboleth's header spoof checking does work well enough under Apache. That's what I'm going to go with in Node.js.

**Comment by jrochkind** [comment]
You might have to use the fallback Shibboleth headers with Node.js, becuase of limitations in Node.js. But I would consider it a significant problem to require that in other platforms (every platform supported by passenger) that don't have such limitations, just because Node.js can't handle request-specific env. In fact, my months of pleas to fix request-specific env caching in Passenger were quite to avoid this, I knew all along I could have used shibboleth header mode instead, but really didn't think I should have to. Request-specific env is a feature in apache, that should be supported by Passenger (and always has been), and not disabled just because node.js can't handle it. That sounds like node.js's problem, not passenger's.

**Comment by mberkowski** [comment]
I guess clarification is needed because the proposed feature doesn't sound to me like it removes request-specific env. I understood it only to change the behavior of the OS process env via SetEnv (still not great) but would allow the request env (via SetEnvIf, mod_rewrite, mod_shib, etc) to keep functioning.

**Comment by FooBarWidget** [comment]
@jrochkind and @mberkowski you are talking about two different issues. The core issue is general, and is not related specifically to Node.js.

@jrochkind there was an issue with not being able to pass request-specific information to Node.js. This issue has been [fixed](https://www.phusionpassenger.com/library/indepth/nodejs/apache_per_request_envvars.html) now, so @mberkowski and I went on to talk about another issue, one which may also affect Ruby.

The issue is that, when a request results in the spawning of an application process, Passenger will store variables for that request into the application's system environment variables. So suppose that the first request to your application is to a Shibboleth-enabled URL. Passenger will store the Shibboleth variables for that request into application's system environment variables.

This is a totally separate system from per-request environment variables.

The reason why Passenger does this is in order to support `SetEnv`. Apache makes no distinction between per-request dynamic environment variables and static environment variables. As far as Apache is concerned, everything is per-request. But this is not how Passenger works.

However, this results in a potential security issue. If the first request to your application is to a Shibboleth-enabled URL, then Shibboleth information will be unnecessarily stored into system environment variables. They stay there unless the application makes an effort to clear them.

The Passenger module running inside Apache cannot distinguish between variables set by `SetEnv` and variables set by Shibboleth. So the only way to fix this security issue is by not storing per-request environment variables into system environment variables. Passenger can still introduce its own configuration option for setting system environment variables. But this breaks compatibility with `SetEnv`.

**Comment by jrochkind** [comment]
Uh oh, it does sound like that is a problem for non-Node.js platforms too?

That does sound like a problem. 

All of this arises because of Passenger 5's caching issues, and was not an issue in Passenger 4, true? I again wonder if the performance gains from this caching are worth the problems -- are the perf improvements of caching env going to actually be significant in any real app which spends most of it's time on the app, not Passenger overhead?

But one way or another, it does sound like it needs to be fixed. 

> So the only way to fix this security issue is by not storing per-request environment variables into system environment variables.... But this breaks compatibility with SetEnv.

If I understand right, if you didn't store Apache-set env into system environment variables (`ENV` in a rack app), they would still be available in `request.env` in a rack app. So it doesn't neccesarily _entirely_ break `SetEnv`.  But I think you are right that people expect `SetEnv`-set variables to appear  in `ENV`. 

It seems to me the only way to fix this security issue without breaking things... is to stop caching env, return to Passenger 4 behavior.  Or at least make it an option off-by-default, that people can turn on if they know what they're doing.

**Comment by FooBarWidget** [comment]
> All of this arises because of Passenger 5's caching issues, and was not an issue in Passenger 4, true?

No. This has got nothing to do with caching in 5 vs 4. It is only related to supporting SetEnv or not.

We can either fix this security issue by not supporting SetEnv, or we can support SetEnv but give rise to this security issue.

A third option is that Apache modifies SetEnv so that it stores its static variables in a different store, allowing Passenger to differentiate between variables set by SetEnv and all other variables.

> ENV in a rack app

For the sake of clarity, let's call it `env` (lowercase), not `ENV` (uppercase), in order to avoid confusion with the global `ENV` constant which is used for accessing system environment variables. Agreed?

> If I understand right, if you didn't store Apache-set env into system environment variables (ENV in a rack app), they would still be available in request.env in a rack app. So it doesn't neccesarily entirely break SetEnv. But I think you are right that people expect SetEnv-set variables to appear in ENV.

Correct.

This was how it worked in Passenger 3 -- Apache per-request environment variables only appeared in `request.env`, not in system environment variables. But people kept filing support requests because `SetEnv` didn't work, so we implemented it in version 4.

> is to stop caching env, return to Passenger 4 behavior.

Caching has got nothing to do with it. Passenger 4 had the same issue too. You cannot fix this without removing `SetEnv` support entirely.

**Comment by jrochkind** [comment]
Oh man this is confusing. Okay, I guess I'm going to have to give up on understanding it, as I still don't. I was using `ENV` in all caps intentionally because I thought I _was_ talking about the global  constant used for accessing system environmental variables. Clearly I'm still confused, this is really confusing. But okay, the problem existed in Passenger 4 too, I just never noticed it, I believe you. 

> This was how it worked in Passenger 3 -- Apache per-request environment variables only appeared in the Rack env, not in system environment variables. But people kept filing support requests because SetEnv didn't work, so we implemented it in version 4.

So if you return to this behavior, Apache-set environmental variables (`SetEnv`, `SetEnvIf`, set by apache modules like Shibboleth, all of these treated the same) WILL still exist in rack `env`, but will NOT exist in system environment variables (`ENV`)?  Do I understand that right?

**Comment by FooBarWidget** [comment]
> So if you return to this behavior, Apache-set environmental variables (SetEnv, SetEnvIf, set by apache modules like Shibboleth, all of these treated the same) WILL still exist in rack env, but will NOT exist in system environment variables (ENV)? Do I understand that right?

Yes.

**Comment by jrochkind** [comment]
Yeah, it does sound like that's the way to go, although clearly a backwards compat problem for people depending on them in ENV. 

There's security vulnerabilities, and then there's just them being _wrong info_ when in ENV, with or without security implications, right?  (It still seems to me like a caching issue, `ENV` is caching whatever value the first time it's set rather than re-calculating for every request. But maybe that's just how `ENV` has to work, or at any rate I believe you that I don't understand what's going on. :) ). 

If you had known then what you realize now, sounds like you might have resisted adding this to Passenger 4 even harder.  Maybe at least a config variable to turn this behavior on or off, whether it should be on or off by default in a 5.x release I don't know.

**Comment by FooBarWidget** [comment]
> It still seems to me like a caching issue, ENV is caching whatever value the first time it's set rather than re-calculating for every request. But maybe that's just how ENV has to work

Yes, that's just how ENV has to work. Can't do anything about that I'm afraid.

> If you had known then what you realize now, sounds like you might have resisted adding this to Passenger 4 even harder.

I haven't heard of Shibboleth until 2015. :)

A config option to turn it off would be possible, but I don't know whether it's a good idea. The problem is quite obscure, and it's hard to explain to people, so I suspect only the two people in this Github issue will end up using that config option.

The only realistic alternative is drop `SetEnv` support as of Passenger 5, to introduce a new config option `PassengerEnvVar` for setting system environment variables, and to tell people to stop using `SetEnv`. That sucks too, but strikes me as *slightly* better than introducing a config option for not setting system environment variables.

**Comment by jrochkind** [comment]
Well, you don't actually need to stop using SetEnv -- you just need to get the values from rack's lowercase `env` rather than System/Process `ENV`, like ruby and rack intended. Right? You don't actually need a special PassengerSetEnv if you are willing to look for the values in the appropriate place. But yes, this is confusing, I'm not sure I understood it until going through these issues with you (thanks!). 

The problem is NOT just limited to Shibboleth though. It is a problem for _any_ variable set with SetEnv (or related apache functionality including internal modules) that is meant to be request-specific, right? If you are looking in system `ENV` for these values, you will find they are wrong if they are request-specific -- may or may not have security implications, but it'll be wrong either way. Shibboleth isn't the only thing that does this. Shibboleth isn't even the only thing that does it for things with security implications -- for instance, standard built-in Apache auth (using basic or digest auth, say) and the `REMOTE_USER` env key.

**Comment by FooBarWidget** [comment]
> Well, you don't actually need to stop using SetEnv -- you just need to get the values from rack's lowercase env rather than System/Process ENV,

But many users actually intend for SetEnv to affect the system ENV. That's the core problem. For example users regularly try to do something like this:

     SetEnv PATH /home/bin:/usr/local/bin:/usr/bin:/usr/sbin
     SetEnv GEM_PATH /opt/mygemset:/usr/lib/ruby/1.9/gems

> It is a problem for any variable set with SetEnv (or related apache functionality including internal modules) that is meant to be request-specific, right?

Yes.

**Comment by FooBarWidget** [comment]
Maybe what I could do for now is to blacklist certain environment variables, such as the ones set by Shibboleth, `REMOTE_USER`, etc. I think that this blacklist has more chance of providing security than a a `PassengerDontSetSystemEnvvars` option, which screams "break me!" all over the place. Then in Passenger 6 I can drop support for `SetEnv` in favor of `PassengerEnvVar`.

**Comment by mberkowski** [comment]
Something like REMOTE_USER is easy to identify, but unfortunately you won't find a regular set of variables from Shibboleth. They are mostly all defined by the identity provider service, and there may be dozens of them on a particular setup.  Some are commonly present like `Shib-Session-ID, Shib-Identity-Provider, Shib-Authentication-Instant` but user attributes tend to be named by the auth service and are frequently customized or institution-specific.

**Comment by jrochkind** [comment]
The problem with dropping support for SetEnv entirely is that it will eliminate the possibility of doing things intentionally in custom apache config that are meant to be request-specific. This is a very useful thing to be able to do.

**Comment by jrochkind** [comment]
Things APPEAR to be working properly for my use case with passenger 5.0.21. I will keep testing and keep an eye on it. Thanks @FooBarWidget !
