### ISSUE TITLE
passenger-config validate-install should take realpath of commands

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1492]
On Red Hat 7, /bin is a symlink to /usr/bin. Therefore `passenger-config validate-install` should take the realpaths of commands. Otherwise it may complain about Passenger being installed in multiple places.

**Comment by OnixGH** [comment]
@FooBarWidget from a 5.0.7 user, is this related?


Validating installation...

 * Checking whether this Passenger install is in PATH... (!)

   Please add /usr/local/Cellar/passenger/5.0.7/libexec/bin to PATH.
   Otherwise you will get "command not found" errors upon running
   any Passenger commands.
   
   Learn more at about PATH at:
    https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_the_path_environment_variable

 * Checking whether there are no other Passenger installations... (!)

   You are currently validating against Phusion Passenger 5.0.7, located in:
   
     /usr/local/Cellar/passenger/5.0.7/libexec/bin/passenger
   
   Besides this Passenger installation, the following other
   Passenger installations have also been detected:
   
     /usr/local/bin/passenger
     /usr/bin/passenger
   
   Please uninstall these other Passenger installations to avoid
   confusion or conflicts.

 * Checking whether the Passenger module is correctly configured in Apache... --------------------------------------------
*** EXCEPTION: No such file or directory - /usr/local/Cellar/passenger/5.0.7/libexec/buildout/$ (Errno::ENOENT)
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/config/validate_install_command.rb:458:in `realpath'
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/config/validate_install_command.rb:458:in `realpath'
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/config/validate_install_command.rb:458:in `check_apache2_load_module_config'
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/config/validate_install_command.rb:60:in `run'
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/config/command.rb:35:in `run_and_get_exit_code'
    /usr/local/bin/passenger-install-apache2-module:786:in `validate_install'
    /usr/local/bin/passenger-install-apache2-module:136:in `run_steps'
    /usr/local/Cellar/passenger/5.0.7/libexec/lib/phusion_passenger/abstract_installer.rb:72:in `run'
    /usr/local/bin/passenger-install-apache2-module:900:in `<main>'

--------------------------------------------

Oops, something went wrong :-(

We're sorry, but it looks like this installer ran into an unexpected problem.
Please visit the following website for support. We'll do our best to help you.

**Comment by FooBarWidget** [comment]
This is already fixed in de8150c82bc.
