### ISSUE TITLE
5.0.6: PassengerMinInstances confusion with multiple VirtualHosts

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1501]
When using the same app directory in two VirtualHosts, and specifying different PassengerMinInstances 2 in one and 3 in the other, behavior seems to be undefined.

Sometimes 2 instances remain, sometimes 3, but also sometimes 0, which violates both configurations.

**Comment by FooBarWidget** [comment]
The official behavior is undefined, but the actual behavior (a result of the implementation) is: the setting associated with the last request will be activated.

For example, suppose that there are two virtual hosts:

 * foo.com, MinInstances 1
 * bar.com, MinInstances 2

If you make a request to foo.com, MinInstances will be set to 1. If you make a request to bar.com, MinInstances will be set to 2, even if it was set to 1 before. If you then make a request to foo.com, MinInstances will once again be set to 1.

This is caused by the fact that configuration is passed from the web server to the PassengerAgent server in the form of secure headers. The process is as follows:

- During each request, the web server first looks up the configuration associated with that request (so in this example, either MinInstances 1 or MinInstances 2).
- The web server serializes the setting's value into a secure header, e.g. `!~PASSENGER_MIN_INSTANCES`.
- The PassengerAgent server looks up the secure header, and sets the ApplicationPool2::Options object, e.g. `options.minProcesses = lookup("!~PASSENGER_MIN_INSTANCES")` (pseudocode).
- In ApplicationPool2/Group.h, `mergeOptions()` is responsible for merging the new value into the internalized Group-specific options.

The reason why the last request is able to change the internalized config value, is because we need to support the Flying Passenger mode. In the Flying Passenger mode, the user can change the web server configuration at any time. We want those new config options to take effect without having to restart the Flying Passenger daemon (i.e. without restarting PassengerAgent server).

Users can avoid the "undefined behavior" by assigning a unique PassengerAppGroupName to each virtualhost.

**Comment by OnixGH** [comment]
This explains the 2 instances and the 3 instances, but not the 0. The likely explanation for the 0 is by the bug fixed in #1500, so the picture is now clear.
