### ISSUE TITLE
How do I restart a Passenger app instance?

### ISSUE THREAD

**Issue by paambaati** [phusion/passenger#1507]
I am developing a Node.js application that also requires an admin console with start/stop/restart capabilities. I understand that the Passenger API documentation isn't public yet, but can someone show me how to figure out the relevant commands from source?

Another question. If I stop an instance, will Passenger's core process still be up and ready to accept a start command?

**Comment by FooBarWidget** [comment]
If you want to restart your own app, the easiest way to achieve that (without using the API) is by setting `passenger_stat_throttle_rate 0` and touching tmp/restart.txt.

You can see how the API is used by looking in the source code for `passenger-status` and `passenger-config restart-app`: https://github.com/phusion/passenger/blob/master/bin/passenger-status and https://github.com/phusion/passenger/blob/master/lib/phusion_passenger/config/restart_app_command.rb (it's in Ruby).
Basically, it finds out where the Passenger API Unix domain socket is, then makes an appropriate HTTP request there. For now, it's probably easier if you shell out to the Passenger commands to get things done.

As for stopping: it depends on what you're stopping. Passenger is like a reverse proxy with process management capabilities. You can spin down Node.js app processes with `passenger-config detach-process`. Passenger itself will still be able to accept requests and commands. But if you stop Passenger itself, then you won't be able to do that.

You can use `passenger-status --show=xml` (or the API request that it internally makes) to lookup the PIDs of your app.

There are some caveats though:

 * Passenger by default ensures that there is at least 1 Node.js app process (`passenger_min_instances 1`). Since you want your admin console to be able to completely stop your app, you need to set `passenger_min_instances 0` and `passenger_pool_idle_time 0`. This latter avoids Passenger from shutting down your app when it's inactive.
 * If your app is being served by Apache or Nginx, then accessing the API requires root access for security reasons. This security restriction is too tight so we're working on a fix. See #1392. You can work around this restriction by using Passenger Standalone.

**Comment by paambaati** [comment]
@FooBarWidget Thanks for the quick response. The source as well as most of your example shows only restart capabilities. Is there support for starting and stopping included in the API as well?

Your suggestion works for me, although I cannot live with setting `passenger_min_instances` to `0`. But as a workaround, if I want to stop the Node.js process, can I do a passenger stop, then passenger start with `passenger_min_instances` and `passenger_pool_idle_time` set to 0, and then finally do a `detach-process`? That should keep passenger running to accept a start command, right?

**Comment by FooBarWidget** [comment]
There is currently no API for starting and stopping apps. You can kind of get the functionality of stopping by detaching/killing your app processes. There is no functionality for explicitly starting an app, but Passenger automatically starts your app upon the first request, if there aren't any processes for that app.

Does your admin panel run inside the same Passenger instance, or does it run under a different Passenger instance?

**Comment by paambaati** [comment]
@FooBarWidget Currently it runs inside the same instance. I am thinking of branching it out into it's own process. That should make my life much more simpler, shouldn't it?

**Comment by FooBarWidget** [comment]
Yes it would. It would become pretty straightforward if the admin panel is separate.

**Comment by paambaati** [comment]
Alright then, I will do that. One last question. After I've spun up 2 Passenger instances - 1 for the main app, and 1 for the admin console, `passenger-status` only shows the 2 instances names and their description. Is there a way to quickly differentiate between the 2 and pick one i.e. the main app's instance name?

**Comment by FooBarWidget** [comment]
You can start both Passenger instances in their own --instance-registry-dir. That way you can unambiguously communicate with the both of them.

**Comment by paambaati** [comment]
Ah, that should do the trick. Thanks!
