### ISSUE TITLE
Nonstandard header cases  lead to 502 (Content-length vs Content-Length)

### ISSUE THREAD

**Issue by fonini** [phusion/passenger#1517]
Hi, I'm using Passenger 5.0.7 with nginx, but I'm getting the following error:

````[ 2015-05-20 18:51:52.0809 14606/7f38173ac700 age/Hel/Req/ForwardResponse.cpp:100 ]: [Client 1-1] Error parsing application response header: Response may not contain both Content-Length and Transfer-Encoding
2015/05/20 18:51:55 [info] 14621#0: *3 client closed connection while waiting for request, client: 180.41.18.10, server: 0.0.0.0:80````

I've deployed the [Tarantula](https://github.com/prove/tarantula) app, but I don't know Rails so much.

What is causing this error?

I'm using Ruby 1.9.3 on Amazon AMI Linux 3.4.37-40.44.amzn1.x86_64

**Comment by OnixGH** [comment]
The error refers to the [HTTP 1.1 specification](https://tools.ietf.org/html/rfc7230#section-3.3.2), specifically: "A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field."

If the Tarantula app is truly sending responses with both these headers then this is an issue for them.

You can set the passenger log level to 7 and grep for "bytes of application data" to verify that Tarantula is passing invalid headers to Passenger.

**Comment by jkljajic** [comment]
go to ./tarantula/rails/lib
in file authenticator.rb
line 24 
replace this 
[ 302, {'Content-type' => 'text/plain', 'Location' => env['SCRIPT_NAME'] + '/home/login',
 'Content-length' => '0'}, []]
with 
[ 302, {'Content-type' => 'text/plain', 'Location' => env['SCRIPT_NAME'] + '/home/login' }, []]
 
and you are safe
all will start wokring 
:+1: 

https://github.com/prove/tarantula/blob/29cb4c2a5e819f5f8de490e850b5ec8c9aa266a4/lib/authenticator.rb
line 24

**Comment by FooBarWidget** [comment]
Aah, I see the problem. Passenger may set Transfer-Encoding if no Content-Length is set. However, our check for Content-Length is case-sensitive because that's how Hash works. Tarantula sets Content-length (note the lowercase l) and so Passenger didn't recognize the Content-Length header. Then, a different part of Passenger checks for headers case-insensitively and finds the contradiction.

Unfortunately, I cannot fix this problem without a performance penalty. Case-insensitively checking for headers on the Ruby side requires a linear scan.

**Comment by OnixGH** [comment]
@FooBarWidget maybe downcase the headers before the hash / check?

**Comment by FooBarWidget** [comment]
And that's a linear operation. It also generates garbage.

**Comment by FooBarWidget** [comment]
The next best thing I can think of is to check for 'Content-Length', 'Content-length' and 'content-length'. This is assuming people won't type weird things like 'content-Length' or 'cOnTeNt-length'.

**Comment by OnixGH** [comment]
@FooBarWidget I know it's also linear, but I suggested it because I thought it defeats the purpose to use casecmp with hash keys. You'd have to casecmp each header against static strings for each header we need to do something special for and then index with that static string, vs. downcasing once and then doing the lookup. But I dunno, casecmp is probably optimized and might still be faster. Btw. the mutable downcase doesn't generate garbage ;)

In any case, isn't there a more important point here that this issue is also relevant for all other app-side header checks, like the Transfer-Encoding, X-Accel-* etc.?

**Comment by gvnc** [comment]
I was getting the same error in logs and this is how I fixed it without changing the source code.

I've seen there are some passenger installation files in /opt/tarantula/rails 

/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.45

However, I was using Passenger 5.0.8. Then I suspected from the version incompatibility and downgrade Passenger to 4.0.45 version, 

# gem list --local passenger
*** LOCAL GEMS ***
passenger (4.0.45)

And the problem was gone ;)

And I believe Rails and Gems may not have the backward compatibility, so it is always important to use the correct versions. Tarantula installation document says it requires Rails 3.2.* and Ruby 1.9.3.

**Comment by OnixGH** [comment]
@gvnc the problem went away because Passenger 4 isn't as optimized as 5 and doesn't affect the headers. It's still an issue with 5.

@FooBarWidget we should reach a conclusion on this matter, either figure out the performance hit and take it, or provide some workaround, as the current approach seems pretty fragile.
