### ISSUE TITLE
passenger-install-apache2-module should allow Apache config sanity check skip

### ISSUE THREAD

**Issue by tmilker** [phusion/passenger#1525]
Passenger 4.0.59: The installer for the apache2 module should have a flag to skip the apache config sanity check.  I'm currently upgrading my Apache installations to 2.4, from 2.2 that is already running Passenger and configured correctly.  apache 2.4 can't load the passenger module, so a configtest properly complains about it.  I can't re-build Passenger without commenting out every reference to Passenger everywhere across my apache configuration to get it to pass this sanity check that isn't doing anything but preventing me from re-compiling the module and then uncommenting them.

Passenger shouldn't really care whether the apache config is broken or not to begin with, this is the kind of hand holding that just creates more issues than it solves.

**Comment by jamgregory** [comment]
I've been having a similar issue - like @tmilker, I'm upgrading our servers to Apache 2.4, and I end up having to disable Passenger and all sites before I can install it. 

:+1: for a flag to allow us to skip this check.

**Comment by FooBarWidget** [comment]
Passenger has legit reasons to care whether the Apache config is broken or not. It happened more than once that people tried to install Passenger, but had an (unrelated) Apache problem, couldn't figure out why their Apache wouldn't start, then contact our support forums in anger. We want to avoid that. So we will not step away from the "hand-holding" approach.

Another reason is that all kinds of autodetection routines depend on the output of `apache2ctl -V`. For example, Red Hat 5 has a bug in its Apache package that causes modules to be compiled with the wrong compiler flags. The installer autodetects this kind of situation and adjusts the compiler flags. Another example is that the installer checks whether your MPM is compatible with Passenger (we only support prefork, worker and event).

However, on recent Ubuntu systems, `apache2ctl -V` tries to parse and load the config file, so we are unable to obtain any useful information as long as the config file has problems. This creates a chicken-and-egg problem.

Anyway, it is correct that the installer should advise, but not enforce. I've made a change so that the installer nags you with a warning, but still allows you to continue.

**Comment by jamgregory** [comment]
Thanks @FooBarWidget! Will the notification about Apache being broken be "ignored" when the installer is in automated mode? At present, it causes it to fail where it'd be preferable for it to go ahead and try to install it anyway.

**Comment by tmilker** [comment]
Yep, that is what I need too, the -a functionality to continue on its own.  That's why I asked for a flag.

**Comment by FooBarWidget** [comment]
Yes. When --auto is given, the warning is still printed but it will not wait for a prompt.

**Comment by jamgregory** [comment]
Cool, thanks @FooBarWidget :+1:
