### ISSUE TITLE
Why I won't be using Phusion any time soon

### ISSUE THREAD

**Issue by superghostmaster** [phusion/passenger#1528]
You left out a VERY important detail, while stating in your configuration guide that it wasn't necessary:

"These packages contain all the binaries that you need."

No, they don't.

They don't include Nginx.  Nothing in your cut/paste guide for Meteor or Nodejs indicates this, and your "official, polished" documentation for Ubuntu install doesn't mention actually installing Nginx.

Unfortunately, as basic and easy as this was to install, it doesn't actually work.  Even with Nginx installed, it fails on startup after following your default guide.

Running ```nginx -t``` provides no insight as to why nginx restart fails, and your guide clearly leaves out a few critical steps.

This is on a default, base cloud server running 14.04 on Digitalocean.

You also give all instructions using 'sudo' which shouldn't be necessary if you're installing @ the server level; you SHOULD be logged in and installing as root, not sudo.  There's a TON of dependency errors that will occur installing packages as a non-root user when they rely on server processes.

This is a good concept, but you're nowhere near production-ready.

**Comment by superghostmaster** [comment]
Your install also completely fucked my Nginx installation.  I seems to break apt-get resources even if it's completely removed.

**Comment by superghostmaster** [comment]
To be clear:  "upgrading" to Phusion on Ubuntu 14.04 with the latest version of Nginx does not work using your default guide.

It seems too good to be true, and clearly it is.

I really wish for once open-source developers would test their packages and ensure they actually do work with the guides they provide.

I have yet to see a single guide on this software that includes the complete instructions.

It's for this reason I strongly doubt the reliability of a product on the open-source level that also has a pay scheme.

It would appear that based on the number of open issues using this with Nodejs, there isn't valid support or guidelines, INTENTIONALLY for Phusion.

You clearly are targeting a pay-for-what-you get scheme.

Thanks for breaking my cloud server, though.  I can't wait to tell all of my nodejs friends how shitty Phusion is for Meteor.

**Comment by FooBarWidget** [comment]
@superghostmaster Please calm down. You are experiencing problems, so I understand that you are not happy with that. However, you also mistrust us from the beginning and assuming that these problems were made by us *intentionally*. I don't think we have done anything to deserve this kind of treatment, especially because tens of thousands of users are using Passenger happily, both open source and paid version alike.

I ensure you that any problems are not introduced intentionally. It should never happen that a Passenger install "breaks your server", and if it does I would want to know why so we can fix that.

I would like to offer my help to analyze the problem and to get your server fixed. However, I need you to be civil and patient. If you agree with this, can you tell me a bit more about your problem? Please give me all the details you can, such as:

 * Which exact guide did you follow? Can you link to the URL?
 * You said `nginx -t` provides no insight on the problem. Many problems are logged inside the Nginx error log, and not shown on screen. Can you tell me what you see in /var/log/nginx/error_log (or error.log)?
 * When you said that certain things should be run by logging in as root, instead of through sudo, what which things do you mean? Sudo is designed to run things with root privileges, so apart from things like environment variables there is no difference between sudo and logging in as root. Can you provide me with a few resources that point out what you mean?
 * You said installing things "completely fscked up your Nginx installation". What exactly do you mean? What are you observing that makes you conclude that your installation is broken? Can you copy & paste your observations?

**Comment by 9mm** [comment]
You sound like an incredibly whiny, entitled wanker. Good riddance.
