### ISSUE TITLE
Is Passenger + rack-timeout being affected by request timeouts?

### ISSUE THREAD

**Issue by rhymes** [phusion/passenger#1536]
I have a Puma + rack-timeout app running on Heroku which sometimes issues "request timeouts" because of a bug (heroku/rack-timeout#76) in rack-timeout which basically kills Puma workers because of unhandled exceptions.

I was wondering, since I'm evaluating Passenger + rack-timeout on a staging app, if it might be affected by the same problem.

It's more of a request for comment or a warning than an actual issue.

Thanks!

**Comment by FooBarWidget** [comment]
The answer is "yes, but...".

Yes, Passenger is also affected by the rack-timeout issue. The Passenger Ruby wrapper code catches StandardError exceptions, but the Timeout module raises an exception that does not inherit from StandardError, thereby causing the process to crash. Passenger then automatically restarts the app.

There are a few "buts":

1. Using Rack::Timeout, or the 'timeout' library in general (which Rack::Timeout uses under the hood), is dangerous. These blog posts explain it better than I do:
   * https://woss.name/articles/ruby-timeout-woes-part-2/
   * https://coderwall.com/p/1novga/ruby-timeouts-are-dangerous
   * https://flushentitypacket.github.io/ruby/2015/02/21/ruby-timeout-how-does-it-even-work.html
   * http://headius.blogspot.nl/2008/02/rubys-threadraise-threadkill-timeoutrb.html
2. Because of (1), the recommended way to apply a timeout is by using Passenger Enterprise's [`max_request_time` feature](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerMaxRequestTime). Unlike Rack::Timeout, this mechanism works on the OS process level and therefore is guaranteed to abort the request (something which Rack::Timeout doesn't guarantee; Rack::Timeout sometimes works, sometimes not, and sometimes appears to work while leaving your app in a corrupted state).

**Comment by rhymes** [comment]
Thanks!
