### ISSUE TITLE
passenger-install-apache2-module unable to detect MPM with Apache 2.4

### ISSUE THREAD

**Issue by betesh** [phusion/passenger#1577]
When running `passenger-install-apache2-module`, I get this warning:

    WARNING: Apache doesn't seem to be compiled with the 'prefork', 'worker' or 'event' MPM

    Phusion Passenger has only been tested on Apache with the 'prefork', the
    'worker' and the 'event' MPM. Your Apache installation is compiled with
    the '' MPM. We recommend you to abort this installer and to recompile
    Apache with either the 'prefork', the 'worker' or the 'event' MPM.

However, this warning is not applicable in RHEL 7, since these modules don't need to be compiled with Apache, but rather are loaded as modules in the configuration file.  See the "Processing Model" section at https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/ch-Web_Servers.html#s2-apache-version2-changes

There probably still is some sort of check that should be done--perhaps make sure that exactly 1 of the modules is loaded by the configuration file.  But the warning needs to be reworded.

Passenger installed as gem. RVM 1.26.11. Ruby 2.2.2.

**Comment by betesh** [comment]
By the way I'm getting the same warning on Ubuntu 15.  I think it really just depends on the Apache version: 2.4.x

**Comment by FooBarWidget** [comment]
Which Passenger version are you using?

**Comment by OnixGH** [comment]
@FooBarWidget I get the message also on Ubuntu 14.04, apache 2.4.7, latest stable.

**Comment by betesh** [comment]
passenger (5.0.15)

**Comment by FooBarWidget** [comment]
It turns out the problem is not related to the Apache version, but to the way distributions wrap around the apache2ctl script. We run 'apache2ctl -V' to detect the MPM, but that command doesn't work on recent Ubuntu versions if the config file contains an error. And now, it seems Red Hat behaves like that too. I am on OS X, which doesn't do this.

We already check for broken config files and display a different warning in that case, but it seems the check didn't work correctly. This has now been fixed.
