### ISSUE TITLE
Passenger not logging processed requests to Rails production.log

### ISSUE THREAD

**Issue by mikechau** [phusion/passenger#1583]
On Passenger 5 (w/ the Passenger + Nginx APT repository on Ubuntu 14.04 LTS), after a certain amount of time Passenger stops writing to the Rails `production.log` file. The nginx logs continue to write.

If we do a `sudo service nginx reload`, the `production.log` starts to write again but then eventually stops again. `sudo passenger-config reopen-logs` does not seem to help any.

We are rotating logs with logrotate but I do not think it should interfere with anything:

```
/home/deploy/apps/sd/shared/log/*.log {
    su deploy sudo
    size=500K
    missingok
    rotate 20
    compress
    delaycompress
    notifempty
    copytruncate
}
```

Any ideas for debugging?

**Comment by FooBarWidget** [comment]
production.log is not the Passenger log. It is the Rails log. Passenger is not responsible for writing to that file; Rails is. A `passenger-config reopen-logs` only tells Passenger to reopen its own logs, so that doesn't cause Rails to reopen production.log.

To reopen production.log, you need to restart the app. Restarting Nginx happens to restart all apps.

**Comment by dave-oz** [comment]
We have to same issue on CentOS. What is the solution on this? @mikechau @FooBarWidget

**Comment by CamJN** [comment]
@dave-oz please open a separate issue and fill out the complete template.
