### ISSUE TITLE
Document what advantages the Phusion APT repository provides

### ISSUE THREAD

**Issue by strugee** [phusion/passenger#1591]
I'm following the production deployment guide for Debian Jessie, and on [this page][1], it gives instructions for adding the Phusion APT repository. I feel somewhat uncomfortable adding foreign repositories into my production deployment (although nothing personal, obviously), especially when I can `apt install libapache2-mod-passenger` directly from the Debian repositories.

Exactly what benefits does your APT repository provide?

**Comment by FooBarWidget** [comment]
The benefits are that the APT packages integrate into your Debian system in Debian packaging guide compliant manner. So we supply init scripts, the files are installed in an FHS-compliant hierarchy, etc. Another advantage is that you won't have to compile source code to install Passenger.

In the end it doesn't matter whether you use our APT repository or install Passenger from source. Both methods are supported. Use what you feel most comfortable with.

**Comment by strugee** [comment]
@FooBarWidget you misread my question. I didn't install Passenger from source; I installed it from the Debian repositories (and to be clear, I mean e.g. `http.debian.net`). From that package I can get all of the advantages you just mentioned.

In any case, you should document that on your website. Apparently I forgot to include the link to the page I'm talking about in the original report. It's [this one][1].

 [1]: https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/apache/oss/jessie/install_passenger.html

**Comment by strugee** [comment]
Also, just for the record, Passenger is fantastic. I'm a Node person, not a Ruby person, and figuring out how Unicorn, etc. was supposed to be set up was a nightmare. Passenger lets me forget about all of that, which is _awesome_.

**Comment by FooBarWidget** [comment]
Ooooh, I see. I thought you were asking about installing from the Phusion APT repository vs installing from source.

We do not recommend installing Passenger from the official Debian APT repo, because that version is pretty much always out of date. We are on a fast development cycle, releasing bug fixes and improvements every 3 weeks on average, so whatever version you get from the official Debian repo is likely to lag behind a lot.

The version from the official Debian APT repo is also improperly packaged and misses some features, so not all of our documentation work with the official Debian APT repo. I've tried discussing this with the Debian package maintainers, but none of them responded to my emails after repeated pinging, so after a while I gave up.

As for your concerns about adding a foreign APT repo:

 * Our packages are based on the official Debian packages. Thus we are 100% compatible, as well as compliant with all the Debian packaging guidelines.
 * You can read the source code of our Debian packages [here](https://github.com/phusion/passenger_apt_automation). Please feel free to review them until you feel comfortable.

**Comment by strugee** [comment]
@FooBarWidget thanks so much for the detailed response, this was exactly what I was looking for. I'll glance through the source code, too. You may want to mention this issue on the walkthrough page I linked to. (Perhaps I'll send a PR, if I find some time.)

**Comment by FooBarWidget** [comment]
A PR would be much appreciated. :)
