### ISSUE TITLE
Allow buffering opt-out via header

### ISSUE THREAD

**Issue by julik** [phusion/passenger#1592]
In my tests I could not let Passenger pass through timed responses without altering the server configuration. It would be extremely handy if Passenger could provide a header in the response that could be used to opt out of buffering if the Rack response is supposed to have a long body.

Related failure: https://travis-ci.org/julik/long_body/jobs/77804760
Related test: https://github.com/julik/long_body/blob/master/spec/shared_webserver_examples.rb#L25

As an option, Passenger could honor the `X-Accel-Buffering: no` as supported by nginx.

The reasoning behind it is that if an application explicitly has a streaming endpoint, the application developer (and not the server administrator) should have a way to disable buffering for that endpoint, from his source.

**Comment by julik** [comment]
Related Rack issue: https://github.com/rack/rack/issues/932

**Comment by FooBarWidget** [comment]
Are you sure your TestDownload class does the right thing? Although Passenger buffers the response by default, its buffering behavior is streaming. That is, sends the response parts as quickly as possible to client, instead of buffering everything before sending to the client. More info: https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_buffer_response

**Comment by julik** [comment]
Well it does the right thing for as much as it can (to the degree Net::HTTP allows it at least), and it does it with all the other servers in the test pack. My initial tests were with curl with `--no-buffer` flag set.

Is there a simple commandline flag I can pass to passengers-standalone to suppress buffering? I skimmed through the `--help` output but could not find anything pertinent to that setting. Also, I still think that there should be a way for the application to tell the app server it is streaming, as opposed to the app server having a setting put in place to allow streaming to happen (this way you remove yet another config value that can be missing/restricted/mistyped).

**Comment by FooBarWidget** [comment]
There is no way to disable Passenger's buffering. Passenger always buffers. Passenger *also* streams by default, even if buffering is enabled.

The following streaming example should work out of the box in Passenger. Is this not the case for you?

~~~
class Response
  def each
    10.times do |i|
      yield("entry #{i}\n")
      sleep 1
    end
  end
end

app = lambda do |env|
  [200, { "Content-Type" => "text/plain" }, Response.new]
end
~~~

**Comment by julik** [comment]
@FooBarWidget that example does work, and "streaming + buffering" is a good enough guarantee for sure. It is possible that Net::HTTP is doing some buffering on it's own here and might be at fault, which would not surprize me.

What would you suggest as a test harness for ensuring that the server indeed streams (that chunks dripped from the response body get received separately)? Opening a pipe to `curl` on the CLI?

**Comment by FooBarWidget** [comment]
I would setup an inter process communication channel with the app. Every time you send a command over the channel, have app output exactly one body chunk. Then in the test, assert that you are able to read that body chunk within a certain timeout. The important thing is that the app doesn't output the body chunk until you tell it to. I would also not use Net::HTTP, but would use raw sockets in order to guarantee that things like Net::HTTP buffering (if any) won't stand in the way.

In pseudo code it would look like this. In the app:

~~~
IPC_CHANNEL = ...

class Response
  def each
    10.times do |i|
      IPC_CHANNEL.readline
      yield("entry #{i}\n")
    end
  end
end

app = lambda do |env|
  [200, { "Content-Type" => "text/plain" }, Response.new]
end
~~~

In your test:

~~~
ip_channel = ...
socket = TCPSocket.new(...)
socket.write("GET /chunk HTTP/1.1\r\n")
...

parse_and_verify_headers(socket)

# Read and verify body now
10.times do |i|
   # Tell application to output next chunk
   IPC_CHANNEL.write("\n")
   
   # Verify that we receive the next chunk
   expect(socket.readline_with_timeout).to eql("entry #{i}\n")
end
~~~

**Comment by julik** [comment]
Ok, I will try something similar (however potential buffering _within_ the `IPC_CHANNEL` might be another pitfall here). How would you explain the buffering that does not happen with other servers, but does happen with Passenger with Net::HTTP though? I know it might be a long shot, but still...

**Comment by FooBarWidget** [comment]
> however potential buffering within the IPC_CHANNEL might be another pitfall here

That should not be a problem. Whatever IPC channel you choose, as long as you make sure that you read and write commands in atomic units, you will be fine. That's why in the example, I chose readline/writeline over a stream socket.

> How would you explain the buffering that does not happen with other servers, but does happen with Passenger with Net::HTTP though? I know it might be a long shot, but still...

I'm afraid I don't know until I've carefully inspected the Net::HTTP source. :) But Net::HTTP does a lot of things, and it appears you are using it in a way for which Net::HTTP does not specify a well-defined contract, so you are better off writing your own client anyway just in case Net::HTTP changes in an incompatible way in the future.
