### ISSUE TITLE
Standalone: Add a way to delay Nginx listening until application boots up

### ISSUE THREAD

**Issue by charlietran** [phusion/passenger#1610]
Currently, Passenger Standalone accepts and queues up requests via Nginx while it waits for the application to boot up. However, this can cause unnecessary delays on Heroku with preboot, where it is preferable to actually refuse connections until the application is booted up and can fully serve requests.

Right now the delay is caused by this sequence of events:

1. Dyno boots up, Passenger Standalone starts, Nginx accepts requests while the application boots
2. Heroku routes a request to this Dyno, Nginx accepts
3. Requests wait X seconds while the application is still booting
4. Latency spikes!

Ideally Nginx would not start listening on the public port until the application is ready.

**Comment by FooBarWidget** [comment]
I see what you mean. It wouldn't be easy to implement though.

**Comment by charlietran** [comment]
Would you please point me towards where I could try modifying Nginx / application boot sequence? Possibly a solution like this one could be implemented:

http://blog.codeship.com/how-to-deploy-nginx-on-heroku/ (under "Configuring Puma")
https://github.com/beanieboi/nginx-buildpack/blob/master/bin/start-nginx#L41-L53

**Comment by OnixGH** [comment]
@charlietran interesting idea. If you just need to create a file when Passenger is finished spawning an application then you could use something like Passenger's [attached_process](https://www.phusionpassenger.com/library/indepth/hooks.html#attached_process) hook.

Let us know if you can get that to work?

**Comment by charlietran** [comment]
@OnixGH happy to try it out! Would also need to modify Passenger Standalone so that its Nginx doesn't bind to the public port until that file exists, where could I try to do that?

**Comment by OnixGH** [comment]
I think the easiest approach would be to run Passenger Standalone with the builtin engine and place a separate Nginx in front of it (reverse proxy) that is started after the Passenger hook creates that file and binds to the public port. 

Then you don't have to modify Passenger or Nginx, which is I think the difficult part that @FooBarWidget was referring to.

**Comment by charlietran** [comment]
Ah that makes sense! I'll try it out, but also I wouldn't mind trying the hard way and making it work within Standalone. Then, Heroku users with preboot enabled who want to use Passenger and avoid this latency issue wouldn't have to wrap their heads around a reverse proxy setup with two running instances of Nginx.

**Comment by OnixGH** [comment]
I haven't looked into it deeply, but it seems to me that 'the hard way' would involve modifying Nginx core + module code (since Passenger Standalone/Nginx runs from an Nginx module and doesn't really control when Nginx opens ports), and I doubt a pull request like that would be accepted by them. Maybe @FooBarWidget has a more positive view :)

Passenger Standalone/builtin has control, but we recommend putting Nginx in front of that anyway, so implementing it there wouldn't really help.

A different thought: I'm not deeply familiar with Heroku Dynos, but isn't it possible to delay the Dyno "start completed" mechanism until the hook is called? I mean, I imagine Heroku wouldn't want to route requests to a Dyno that hasn't finished starting, so it would need to wait for some startup script anyway, and maybe that could just loop until the hook has signaled the magic?

**Comment by charlietran** [comment]
Heroku waits for something to bind to the port specified by `$PORT` until it deems the web dyno ready to receive requests. Another potential solution is load Passenger with any port number other than `$PORT` (which Heroku usually specifies as something like `55755`), wait until it loads the application, and then re-load Nginx with the port set to `$PORT`, thus marking the dyno as ready. Would that be possible using something like the `passenger-config` cmd to reload just the builtin server?

**Comment by OnixGH** [comment]
Unfortunately reloading wouldn't help, because an Nginx config reload triggers a shutdown/restart of submodules, which includes Passenger and all started apps (`passenger-config` doesn't support the reload, but `kill -HUP` on the nginx master process achieves the same).

Not sure if you have access to iptables, but that would be a simple way to route a port without needing a reverse proxy setup. Other than that, a separate nginx still seems like the way to go.

Btw. I read up on [Heroku Web Dynos](https://devcenter.heroku.com/articles/dynos#web-dynos), and one dangerous thing with delayed port binding is that the dyno manager kills the web dyno if it doesn't bind within 60 sec (meaning this setup would break app deployments that need longer than that, unless the startup script takes this into account and launches nginx at like max. 50 sec).

**Comment by charlietran** [comment]
Doesn't look like we have access to iptables, so yeah, another Nginx might be the only way :/. You're right that the delayed port thing is dangerous, but if an application isn't booting within 50 seconds anyway you'd still have the same issue.

I'll close this issue for now and move further discussion to the https://github.com/phusion/passenger-ruby-heroku-demo repo, but one last question: you mentioned that:

> we recommend putting Nginx in front of that anyway

Could you point me to the docs that recommend that? My understanding was that Standalone was deemed as a production ready web server without anything else in front.

**Comment by OnixGH** [comment]
If an application doesn't boot within ~60 sec, but Passenger is already bound to the port then would Heroku still kill the Dyno? I thought it would sooner put it in Quarantine for a bit.

Passenger Standalone actually comes in 2 flavors. By default it uses nginx as its connection frontend, which is battle hardened. For the case that people want their own reverse proxy in front (e.g. nginx), we also provide a more lightweight "builtin" engine (so you don't get the performance overhead of 2 full fledged nginxes in a row). See the [chapter about optimization]( https://www.phusionpassenger.com/library/config/standalone/optimization/) for more info.

**Comment by charlietran** [comment]
As long as something binds to the port within 60 seconds, Heroku won't kill
the Dyno. I believe a Dyno only gets Quarantined for ~5 seconds when it
returns 503 errors back.

Thanks for clarifying! I was mixing up the bundled Nginx vs Builtin options
for Standalone.
