### ISSUE TITLE
RACK_ENV values are set incorrectly

### ISSUE THREAD

**Issue by jeffbyrnes** [phusion/passenger#1613]
As per [this lovely blog post by @mpalmer](http://www.hezmatt.org/~mpalmer/blog/2013/10/13/rack_env-its-not-for-you), the `RACK_ENV` env var should only be set to one of three values:
- `development`
- `deployment`
- `none`

This is corroborated by Rack’s own [inline docs](https://github.com/rack/rack/blob/1.6.0/lib/rack/server.rb#L157-L162).

Hard to say how much of an issue this really causes, but it would probably be best that we follow what Rack expects to receive for this EnvVar, instead of overriding it to match `PASSENGER_APP_ENV`.

**Comment by FooBarWidget** [comment]
Looks like you are right. This isn't helped by the fact that Rails more or less treats `RACK_ENV` as a fallback alias for `RAILS_ENV`.

**Comment by jeffbyrnes** [comment]
@FooBarWidget yeah, though that should probably be handled on the Rails project. I’ll go see if they have an issue tracking this yet; if not, I’ll file one, and reference this one.

**Comment by jeffbyrnes** [comment]
@FooBarWidget a bit of digging reveals quite the mess of conversation around this:

* rails/rails#19404
* rack/rack#831
* sinatra/sinatra#984

So it looks like folks are actively working to unsnarl this issue.

Based on this tidbit from @wuputah:

> The difference about RACK_ENV=deployment is it, effectively, enables most modern features of HTTP/1.1, like keep-alive (rather than running with Connection: close and relying on EOF). Without it, there's no Content-Length, chunked encoding, etc, which means keep-alive cannot be used.

I’d encourage, for the time being, following the spec for Rack and setting `RACK_ENV` to `deployment`, and revisiting this as the Rack & Rails projects sort this out, however it goes.

**Comment by jeremy** [comment]
Reposting from https://github.com/rack/rack/pull/831#issuecomment-89021866:

The blog post makes a strong stand, but it doesn't capture the history or usage of `RACK_ENV`. It's a convention that grew *outside* of Rack, in Passenger, Mongrel, Unicorn and other servers, and in early Rack-friendly frameworks, like Merb and Sinatra. Linking it to Rack::Server's `-E` reflects Rack::Server's role as *just another user of the env*.

Retrospectively recasting its role into a "you're doing it wrong" post is appealing, but misleading. `RACK_ENV` has consistently meant the environment you're running the *app* in, not the "Rack environment." It's caused some confusion, for sure. That's worth addressing. But nobody has been doing it wrong.

If we're going to break compatibility, a stronger path forward could be to remove the default middleware decision-making in Rack::Server. Double down on `RACK_ENV`'s well-established role instead of reinventing it.

**Comment by jeffbyrnes** [comment]
Closing this due to staleness. Based on looking at Rails & Sinatra, they solved this by introducing changes of their own to avoid this concern.

If it's still an issue though, please re-open!
