### ISSUE TITLE
Passenger standalone behavior for upstart

### ISSUE THREAD

**Issue by fabn** [phusion/passenger#1614]
I'm using foreman export to generate upstart configuration files to run passenger in standalone mode. 

Here's the generated config by foreman that used to work in previous passenger versions:

```
start on starting sites/app-web
stop on stopping sites/app-web
respawn

env PORT=3055
env HOME='/var/rails'
env RAILS_ENV='production'
env RACK_ENV='production'

setuid rails

chdir /var/rails/app/releases/20150914143322

exec bundle exec passenger start -p $PORT --max-pool-size ${WEB_CONCURRENCY:-4}
```

I currently have a big issue (I don't exactly know which passenger version broke it). When I restart the app using upstart commands (namely `restart sites/app`) the new instance of the application fail to boot and the old one remain active and working.

When the app is started pid file reports nginx pid while upstart tracks passenger main command, however according [to this document](https://www.phusionpassenger.com/documentation/Design%20and%20Architecture.html) this should not be an issue. Also if I start passenger with `passenger start -p whatever` on my development machine I (should) have the same process tree and if I kill the main process using `TERM` also nginx is stopped.

Do you have any working upstart configuration for passenger standalone? Googling for that I only found very old configurations and nothing recent.

Is my assumption right? I.e. can passenger main process stopped using `SIGTERM` or this is something that should be avoided?

**Comment by fabn** [comment]
I spent a lot of time debugging this and I found out that the main cause of this issue might not be passenger itself. I written a set of scripts to track launched processes and their status and did some restart.

Sometimes a `restart sites/app` works and the app is then restartable, some other it won't and the nginx process remain alive while passenger start script die

Here's what's happening when everything works.

```
Nginx pid: 8236
Passenger start pid (ruby): 8027
Upstart pid: 8027

Upstart status for app
sites/app-web-1 start/running, process 8027

Upstart tree

ruby,8027 /var/rails/app/shared/bundle/ruby/1.9.1/bin/passenger start -p 3040 --max-pool-size 8
  ├─sh,8246 -c tail -f -n 0 "/var/rails/app/releases/20150810104124/log/production.log"
  │   └─tail,8249 -f -n 0 /var/rails/app/releases/20150810104124/log/production.log
  ├─sh,8250 -c tail -f -n 0 "/var/rails/app/releases/20150810104124/log/passenger.3040.log"
  │   └─tail,8252 -f -n 0 /var/rails/app/releases/20150810104124/log/passenger.3040.log
  ├─{ruby},8241
  ├─{ruby},8242
  └─{ruby},8251
```

Here upstart correctly tracks ruby process with PID 8027 and when a stop (or restart) command is issued everything else is killed successfully.

Other times I have this

```
Nginx pid: 6159
Passenger start pid (ruby): 6073
Upstart pid: 6071

Upstart status for app
sites/app-web-1 start/running, process 6071

Upstart tree

sh,6071 -e -c bundle exec passenger start -p $PORT --max-pool-size ${WEB_CONCURRENCY:-8} /bin/sh
  └─ruby,6073 /var/rails/app/shared/bundle/ruby/1.9.1/bin/passenger start -p 3040 --max-pool-size 8
      ├─sh,6169 -c tail -f -n 0 "/var/rails/app/releases/20150810103644/log/staging.log"
      │   └─tail,6173 -f -n 0 /var/rails/app/releases/20150810103644/log/staging.log
      ├─sh,6175 -c tail -f -n 0 "/var/rails/app/releases/20150810103644/log/passenger.3040.log"
      │   └─tail,6177 -f -n 0 /var/rails/app/releases/20150810103644/log/passenger.3040.log
      ├─{ruby},6166
      ├─{ruby},6167
      └─{ruby},6176
```

In this case the wrong pid is tracked by upstart, 6071 instead of 6073. When I issue a stop command the TERM signal is sent to process 6071 and it dies. After it dies all the other processes (passenger related) in that tree die too but the nginx remain alive and continue to serve requests.

In both cases nginx is started as daemon and its parent process is init. For this reason it's not present in the shown tree.

I think that the main issue here (that causes the two different process trees) is not related to passenger. I think that is upstart that is doing something weird because the `/bin/sh -e` commandline is in some way [documented here](http://upstart.ubuntu.com/cookbook/#develop-scripts-using-bin-sh).

I'll continue to investigate to see if there is some race condition somewhere, in any case there might be an issue in passenger shutdown code, why in second case when process 6071 gets a SIGTERM the whole tree is killed as well and nginx remains active?

**Comment by OnixGH** [comment]
In 2015 there was an [issue](https://github.com/phusion/passenger/issues/1454) where someone posted their (working) upstart config, maybe that helps

It should be fine to send a SIGTERM to the passenger process, so I'd suspect there is some issue with the upstart config / shell options?

There is one [known issue](https://github.com/phusion/passenger/issues/1678) regarding standalone, but that's when using daemonized mode and stopping, resulting in a hanging temp-dir-toucher.

**Comment by OnixGH** [comment]
@fabn any update?

**Comment by fabn** [comment]
@OnixGH the project with that setup was dismissed, so I don't know if that is still an issue with latest passenger version. If you are not able to reproduce and nobody else has encountered this imho this issue can be closed.

I'll reopen it if I experience the issue again.

**Comment by OnixGH** [comment]
Alright, please do reopen if you have something reproducible in the future!

**Comment by karlsvec** [comment]
Just wanted to chime in here because I'm the user who reported the [issue mentioned above](1454) by @OnixGH.

@fabn The problem you were experiencing is an Upstart problem, not a Passenger problem. The _only_ way to have Upstart manage Passenger is to do exactly what you did and have it track the `passenger start` launcher process instead of the watchdog agent process.

Upstart cannot, and never will, properly track Passenger's watchdog agent process. Upstart can only deal with three launching behaviors for tracked processes:

1. the process does not fork (i.e. runs "in the foreground")
2. the process forks once (in this case, you use the `expect fork` directive in Upstart)
3. the process forks twice (`expect daemon`)

Unfortunately for Upstart, Passenger forks more than twice when starting up, so Upstart can't track the watchdog. Your only choice is to start Passenger _without_ the `--daemonize` flag and let Upstart track the launcher process. Any signals received by the launcher will get "forwarded" to the watchdog. It works, but you end up wasting a little bit of memory keeping that launcher process around.

Passenger seems to be designed with a "batteries included" philosophy and has all of the daemon management built-in, which isn't a good fit for how Upstart works.

The other popular "modern" init system on the block, Systemd, does not share Upstart's problems with Passenger. On Systemd, you can launch Passenger with `--daemonize` and `--pid-file`, tell Systemd to use that PID file, and it will do the right thing.

**Comment by karlsvec** [comment]
I should add that the `--daemonize` flag is a little bit misleading. Passenger always "daemonizes" no matter what -- the watchdog agent process always get reparented as a child of the init process. The `--daemonize` flag just controls whether or not the launcher process sticks around after the full Passenger process tree (watchdog, core, ust-router, app preloader, etc.) is finished starting up.
