### ISSUE TITLE
Passenger/Apache crashes on large file POST

### ISSUE THREAD

**Issue by will-in-wi** [phusion/passenger#1620]
Passenger 5.0.16
CentOS 6
Apache 2.2.15

When we upload a large set of files (10G+) to a Rails app running under Passenger, Passenger will frequently crash, leaving the following log: https://gist.github.com/will-in-wi/a2847ac19ac08f4f555d

The main line seems to be:

    [ pid=21536 ] Last assertion failure: (bytesBuffered + buffer.size() <= MAX_MEMORY_BUFFERING), function void Passenger::ServerKit::FileBufferedChannel::pushBuffer(const Passenger::MemoryKit::mbuf&), file ext/common/ServerKit/FileBufferedChannel.h, line 475.

It looks like the buffer gets bigger than the number of bytes a 32bit integer can reference. https://github.com/phusion/passenger/blob/release-5.0.19/src/cxx_supportlib/ServerKit/FileBufferedChannel.h#L475

Is there an expected hard limit in Passenger on the amount of data which can be uploaded, or is this a bug?

Thanks!

**Comment by FooBarWidget** [comment]
This looks like a bug.

**Comment by OnixGH** [comment]
The 32 bit int actually makes this a buffer limit (that is guarded by the assert). We should consider moving to 64 bit, which might affect several different places.

**Comment by OnixGH** [comment]
In summary: 
- this is an issue that only affects Passenger + Apache due to the buffering technique. 
- there is / was no hard upload limit
- the issue occurred only sometimes because it happens when the server harddisk isn't able to write the incoming bytes fast enough to disk, which causes increased memory buffering, which eventually overflows at 4 GB if the disk gets far enough behind

The [fix](https://github.com/phusion/passenger/commit/136fb28cfe471aa788d36ac0851112ef8735a42b) now applies backpressure on the uploader connection when the server harddisk isn't able to keep up instead of trying to buffer in memory. The memory buffer has also been sharply limited (to 130 KB) to allow for high speed clients and high concurrency, which also means the original idea of switching to 64 bit was discarded.
