### ISSUE TITLE
Union Station: provide more information about request queueing

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1633]
Passenger should provide more information to Union Station about what happens before entering 'request proxying'.

Issue rephrased:
This is currently logged thru a "get from pool" activity block, which is the duration that a request waits in the queue for an available process to handle it. That duration of this block can be affected by two things:
1. Waiting for (one or more) processes to spawn
2. Waiting for other requests to be handled

If we see a long "get from pool" we would like to be able to say something about how it was affected by the above 2 cases.
We can say something in each request about spawning activity / headroom to know if the server was already at full capacity (i.e. whether changing min-processes would help or not). We can also say something about the queue size when the request arrives, to know whether the queueing time involved waiting for other requests (i.e. whether having more processes / servers would help).

**Comment by sahin** [comment]
+1

**Comment by sahin** [comment]
@FooBarWidget  in our server "requests proxing" takes like 30-50 ms, pools, and cpu, memory looks good, we would love to see why it is 50 ms.

**Comment by OnixGH** [comment]
@sahin this issue is not about "request proxying", but about "get from pool".

The request proxying is all about your application, basically anything that happens between passenger giving your application the request, and your application returning a response. If you're on Ruby you can add union station log calls in your application to time different parts of your app. If you're on Node, then that will be possible too very soon :)
