### ISSUE TITLE
[Debian] broken package relationship for nginx

### ISSUE THREAD

**Issue by antoineco** [phusion/passenger#1651]
The `nginx-{extras,light,full}` Debian packages define the following dependency/relationship:

```
Recommends: passenger (>= 5.0.20), passenger (<< 5.0.21)
```

However, `apt-get install nginx-extras=1:1.8.0-8.5.0.20~jessie1` installs the following packages (note the version mismatch):

```
ii  nginx-extras                       1:1.8.0-8.5.0.20~jessi amd64
ii  passenger                          1:5.0.21-1~jessie1     amd64
ii  passenger-dev                      1:5.0.21-1~jessie1     amd64
ii  passenger-doc                      1:5.0.21-1~jessie1     all
```

[Theoretically](https://www.debian.org/doc/debian-policy/ch-relationships.html) it should work, but it seems like only the `>=` condition is evaluated. It might be safer to establish strict version dependencies on `nginx` and `nginx-*`.

**Comment by ramirovjr** [comment]
In Ubuntu 14.04, using the PPA Mainline (to install the latest version of Nginx) also installs the Nginx 1.8.0 version.

**Comment by FooBarWidget** [comment]
I'm afraid there isn't much we can do about this. If we specify a strict version dependency then it won't allow installation patch updates for the passenger package (e.g. passenger 1:5.0.21-2~jessie1). I'm of the opinion that this is a bug in APT and that it should be fixed in APT.

As a workaround, maybe you can supply the Passenger version explicitly, e.g.:

    apt-get install nginx-extras=1:1.8.0-8.5.0.20~jessie1 passenger=1:5.0.20-1~jessie1
