### ISSUE TITLE
Nginx ECDSA SSL - 403 forbidden

### ISSUE THREAD

**Issue by Aqualie** [phusion/passenger#1658]
Nginx 1.9.5 HTTPS SSL with ECDSA certificates
Phusion_Passenger 5.0.21
Ruby 1.9.3 (Single User Installation)

nginx.conf - snippet:
http {
passenger_root /home/user/.rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.21;
passenger_ruby /home/user/.rvm/gems/ruby-1.9.3-p551/gems/wrappers/ruby;
server {
listen 443 ssl
server name snorby.localhost;

root /srv/https/ruby/snorby/public;
passenger_enabled on;
rails_spawn_method smart;
rails_env production;

Works great on standard  HTTP listen 80 but as soon as I toss ECDSA  SSL into the mix I'm greeted with a nice 403 Forbidden. No errors are generated in production.log or nginx logs.

**Comment by OnixGH** [comment]
Hi @Aqualie, this sort of question is more suitable for the [forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger), unless you have a clear indication the issue is with passenger.

I would also recommend posting entire config files without leaving out parts, configuration issues can be pretty sneaky.
