### ISSUE TITLE
Node/Ruby install not working on Amazon Linux

### ISSUE THREAD

**Issue by jwhitmarsh** [phusion/passenger#1666]
Passenger installed fine and `passenger-config validate-install` returns
```
What would you like to validate?
Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Passenger itself
   ⬡  Apache

-------------------------------------------------------------------------

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓

Everything looks good. :-)
```
(although I running the command with sudo returns `command not found`)

Running `passenger-memory-stats` works but shows no nginx processes running, which the docs say 'If you do not see any Nginx processes or Passenger processes, then you probably have some kind of installation problem or configuration problem.'

Update:
If I manually start nginx and then run `passenger-memory-stats` it shows two nginx processes running, however if I reboot the system nginx doesn't startup.

**Comment by FooBarWidget** [comment]
> (although I running the command with sudo returns command not found)

This is normal because sudo nukes all environment variables, including PATH. See https://www.phusionpassenger.com/library/indepth/environment_variables.html#environment-variables-and-sudo

> If I manually start nginx and then run passenger-memory-stats it shows two nginx processes running, however if I reboot the system nginx doesn't startup.

In that case you need to configure Nginx to start at system boot. This is an operating system-specific thing, and not directly related to Passenger, so you will probably have more luck asking a more generic Linux support forum or something.
