### ISSUE TITLE
After updating node, passenger is still using the old version

### ISSUE THREAD

**Issue by jwhitmarsh** [phusion/passenger#1669]
I just upgraded node to v4.2.2 (LTS) but when I run my app it's running v.0.10.x

**Comment by OnixGH** [comment]
Hi @jwhitmarsh, this question is more suitable for the [forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger), unless you have a clear indication the issue is with passenger.

Passenger isn't responsible for the node version, it runs with whatever node version is set active in the environment it's run from.

**Comment by jwhitmarsh** [comment]
Ok, thanks @OnixGH
