### ISSUE TITLE
cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by rowend** [phusion/passenger#1680]
### Introduction

Hi, I try to deploy a sample app, but always I get this error:

```cannot load such file -- bundler/setup (LoadError)```

The sample app is so simple, is a hello world. I try to do it with sinatra or rails and I get the same error.

---

### My App structure

app (folder)
-->public (folder - empty)
-->tmp (folder - empty)
-->.ruby-version (file)
-->app.rb (file)
-->config.ru (file)
-->Gemfile (file)

---

### My Code

**.ruby-version:**

```
ruby-2.2.3
```

**Gemfile:**

```
source "https://rubygems.org"

gem 'sinatra'
```

**app.rb:**

```
require 'sinatra'

get '/' do
    'Hello, from sinatra'
end
```

**config.ru:**

```
# encoding: UTF-8
require './app'
run Sinatra::Application
```

---

### Setup Step 1

* SO: **ubuntu trusty 64**
* some commands:
```
sudo apt-get update
sudo apt-get install git
sudo apt-get install build-essential
sudo apt-get install ruby-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install apache2-threaded-dev
sudo apt-get install libapr1-dev
sudo apt-get install libaprutil1-dev
sudo apt-get install apache2
```
* other commands:
```
sudo dd if=/dev/zero of=/swap bs=1M count=1024
sudo mkswap /swap
sudo swapon /swap
``` 
* Install **ruby-install** tool from https://github.com/postmodern/ruby-install
```
wget -O ruby-install-0.5.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
tar -xzvf ruby-install-0.5.0.tar.gz
cd ruby-install-0.5.0/
sudo make install
```
* Install **ruby 2.2.3** with  ```ruby-install 2.2.3```
* Install **Chruby** tool from https://github.com/postmodern/chruby
```
wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
tar -xzvf chruby-0.3.9.tar.gz
cd chruby-0.3.9/
sudo make install
```
* Go to **.bashrc** and append the next lines
```
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
```
* reload your bash

---

### Setup Step 2

* Go to **app folder**
* check **ruby version** ```ruby -v```must be 2.2.3
* Install **bundler** with ```gem install bundler```
* Install gems with ```bundle install --path vendor````
* This is my **Gemfile.lock:**
```
GEM
  remote: https://rubygems.org/
  specs:
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    tilt (2.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  sinatra

BUNDLED WITH
   1.10.6
```
* Install **passenger** with: ```gem install passenger --no-rdoc --no-ri````
* Install **apache module** with ```passenger-install-apache2-module```
* follow instructions and paste in your apache2.config the passenger lines. In my case were:
``` 
LoadModule passenger_module /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21
     PassengerDefaultRuby /home/vagrant/.rubies/ruby-2.2.3/bin/ruby
   </IfModule>
``` 
* edit the file /etc/apache2/sites-available/000-default.conf with something like this
```
DocumentRoot /somewhere/public
      <Directory /somewhere/public>
         # This relaxes Apache security settings.
         AllowOverride all
         # MultiViews must be turned off.
         Options -MultiViews
         # Uncomment this if you're on Apache >= 2.4:
         Require all granted
      </Directory>
```
* reload your server with: ```sudo service apache2 restart```

---

### Problem

When I got my localhost I get the next error ![](http://i.imgur.com/rbFJi0X.png)
I go to apache logs in /var/log/apache2/error.log and I get the next Info:
```
App 16575 stdout:
App 16575 stdout:
[ 2015-11-24 12:47:25.7305 16472/7fab1df1a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /vagrant: An error occured while starting up the preloader.
  Error ID: dd1fe3d8
  Error details saved to: /tmp/passenger-error-DBHVnn.html
  Message from application: cannot load such file -- bundler/setup (LoadError)
  /home/vagrant/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/vagrant/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /home/vagrant/.gem/ruby/2.2.3/gems/passenger-5.0.21/src/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2015-11-24 12:47:25.7380 16472/7fab1ef1c700 age/Cor/Req/CheckoutSession.cpp:253 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is dd1fe3d8. Please see earlier logs for details about the error.
```

I include the file /tmp/passenger-error-DBHVnn.html for more information: https://monosnap.com/file/IsJpyphHvgEY3HQMlBkeGkGSCVkN7J

---

### Notes

I tested the same setup with different ruby versions and only one works:

ruby 2.2.0 works
ruby 2.2.1 fails
ruby 2.2.2 fails
ruby 2.2.3 fails

---

A lot of thanks...
Have a nice day

**Comment by OnixGH** [comment]
Hi @rowend, thanks for the detailed report, but it sounds like a problem with your environment, passenger certainly supports running with those ruby versions.

Maybe you can remove the passenger gem installation do a clean install from apt (the recommended way to install passenger).

**Comment by FooBarWidget** [comment]
I am pretty sure this is related to the environment. Probably your Ruby interpreter expects a certain `GEM_PATH`, but Passenger sets a different `GEM_PATH`. Try fixing that.

**Comment by rowend** [comment]
Sorry for answer a little late. I have few personal details.....

I fix it with your suggestions and it is working. (Path problem)

Have a nice day.

**Comment by OnixGH** [comment]
Thanks for reporting back!

**Comment by ZuevEvgenii** [comment]
You can try to run:

    bundle exec rake rails:update:bin

**Comment by vaultnetworks** [comment]
@rowend I'm experiencing the same issue, can you explain what you did to fix it?

**Comment by rowend** [comment]
@vaultnetworks In that moment I was installing passenger out of bundler. In order to fix it I added to the gemfile but It only worked with ruby v-2.2.2.

**Comment by vaultnetworks** [comment]
@rowend Thanks for your response. My issue turned out to be different (and a dumb oversight on my part). I simply needed to set the proper Ruby version (2.3.1) in rbenv globally, because the app was attempting to use the system Ruby (1.9.1).

**Comment by disastrous-charly** [comment]
Hello, 
Sorry to re-open the issue.

I'm on Centos 7 with ruby 2.4.2. When I access a page, I have the same issue as previous : 
`[ E 2017-11-23 23:43:26.7891 31059/T8 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 7b661dea. Please see earlier logs for details about the error.
App 31104 stdout: 
App 31104 stdout: 
[ E 2017-11-23 23:43:27.0959 31059/Th age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/myapp/: An error occurred while starting up the preloader.
  Error ID: 695e96ef
  Error details saved to: /tmp/passenger-error-4ZKhpj.html
  Message from application: cannot load such file -- bundler/setup (LoadError)
  /usr/lib64/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib64/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /opt/myapp/env/rubygems/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:456:in `activate_gem'
`
The thing is, my company build the all rails app as a rpm, and to do that we use https://github.com/nkryptic/sandbox to have all the gems with the app.

I'm currently migrating to centos7, with centos6, when the application start/restart, we put 'source /opt/myapp/env/bin/activate_sandbox' so it loads the good GEM_PATH for gems.

I do the exact same thing, but httpd doesn't seems to care because it can't find bundler...

I should add that I install ruby (2.4.2) using https://github.com/feedforce/ruby-rpm/releases and if I try to install Passenger using yum repository, I have an error telling me I don't have ruby > 2.0.0 (but I have) that's why I had add passenger in the Gemfile.

passenger-config validate-install is all green.
So as previous, I think it's an environment issue, but can you help me ? Any idea ?

**Comment by CamJN** [comment]
@disastrous-charly please check the output of `passenger-config about ruby-command` and compare to your `PassengerRuby` config in your apache config. Also if you set your `PassengerLogLevel` to 7 it will print out (amongst other things) the bash startup scripts as they are executed so you can check if your `GEM_PATH` env var is set.

**Comment by disastrous-charly** [comment]
@CamJN thanks for the tips !

Here is what I get : 
```
Ruby load path ($LOAD_PATH)
/usr/lib64/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib
/usr/lib64/ruby/site_ruby/2.4.0
/usr/lib64/ruby/site_ruby/2.4.0/x86_64-linux
/usr/lib64/ruby/site_ruby
/usr/lib64/ruby/vendor_ruby/2.4.0
/usr/lib64/ruby/vendor_ruby/2.4.0/x86_64-linux
/usr/lib64/ruby/vendor_ruby
/usr/lib64/ruby/2.4.0
/usr/lib64/ruby/2.4.0/x86_64-linux

```
```
RubyGems version = 2.6.13
RubyGems paths = ["/home/maestro/.gem/ruby/2.4.0", "/usr/lib64/ruby/gems/2.4.0"]
```
So...the path with the gems is not here. But if do 'env' to print environment variables, I can see my custom GEM_PATH which is properly set. (with both root and my lambda user)

Do you know how can I add an entry in Rubygems paths please ?

**Comment by CamJN** [comment]
The reason I suggested the logging is that you clearly set the GEM_PATH (either directly or by sourcing another script) in your bash setup scripts. However this is likely done after an "interactive shell guard" which stops evaluating the scripts when bash is run non-interactively.

By reviewing the output of the bash startup logs you can find where the script stops instead of setting the env var (or calling the ruby env script). Then simply move the relevant setup before the interactive shell check.
