### ISSUE TITLE
Graceful shutdown signal when using websockets

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1702]
When the new `passenger_abort_websockets_on_process_shutdown` is set to `false`, Passenger will wait with sending a termination signal until the application has closed its websockets. Passenger should have a way of signaling the app that it should commence websocket termination.

**Comment by FooBarWidget** [comment]
The most obvious way to implement this is by sending a Unix signal to the process to indicate that it should prepare for termination. However, this is not the approach I would recommend because different language runtimes handle Unix signals differently. There aren't a whole lot of signals that we can use -- SIGUSR1 and SIGUSR2 are basically the only ones, and they are often already in use. Some language runtimes, e.g. JRuby or anything based on the JVM, are almost completely incapable of handling signals.

Instead, I propose a solution that makes use of a secondary auxiliary server. When a Node.js application starts, it tells Passenger which socket it listens on. I'm saying that the application should spawn a *second* http.Server, and tell Passenger that address. Passenger will then send a request to that second address, e.g. 'POST /prepare_shutdown'.
