### ISSUE TITLE
Request environment variables with underscores filtered by passenger 5.0.22

### ISSUE THREAD

**Issue by hajimenomomo** [phusion/passenger#1707]
Hi,
Since the latest version of passenger (5.0.22), accessing request specific environment variables from my Rails 4.2.4 (Ruby 2.2.3) doesn't work anymore. For instance the term request.env['HTTP_HOST'], just gives a nil field for every request, whereas request.host works flawlessly. This applies to every request specific field accessed through request.env['FOO'], and also to my authentication tokens for instance, this problem doesn't happen with previous versions of passenger 5.
Sincerely,

**Comment by OnixGH** [comment]
Are you sure the problem is with Passenger?

I tried Passenger 5.0.22 with a Rails 4.2.4 app on Ruby 2.2.3 and I get "localhost:3000" for request.env['HTTP_HOST'] (on Ubuntu 14.04).

**Comment by hajimenomomo** [comment]
I just did some further testing and it so happens that this occurs only with my custom request environment variables, I am able to access request.env['HTTP_HOST'], but request.env['HTTP_X_USER_TOKEN'] gives back an empty string for instance.

**Comment by OnixGH** [comment]
How are you setting the custom env variables?
In which previous version of Passenger did you test it to work?

**Comment by hajimenomomo** [comment]
My request environment variables are just request headers used by my API, I tested it to work from passenger 5.0.7 to 5.0.21, standalone (with integrated nginx). When I print out request.env['HTTP_X_USER_TOKEN'], it is an empty string, I checked my client application requests, and this field is set, and accessible with every other version of passenger 5 before 5.0.22. This problem causes my application controller to be unable to access user tokens, thus leading to authentication problems.

**Comment by OnixGH** [comment]
What HTTP headers are you sending exactly? Your example contains underscores, note that we had to start filtering those to fix a [security vulnerability](https://blog.phusion.nl/2015/12/07/cve-2015-7519). 

If you use dashes instead of underscores the headers will be allowed through like all the regular headers.

**Comment by giorgian** [comment]
I can confirm, just downgrading (on ubuntu) to 5.0.21 made everything work again.

FWIW, My hypothesis is that the new version of passenger is not blocking request env variables, but it's instead interfering with nginx `directive underscores_in_headers on;`

Most of the request headers where still present, but not HTTP_AUTH_TOKEN, the one we rely on.

**Comment by OnixGH** [comment]
@giorgian allowing headers with underscores, especially with authentication, leads to the header overwriting security vulnerability [CVE-2015-7519](https://blog.phusion.nl/2015/12/07/cve-2015-7519) as discovered by the SUSE security team.

In your case for example, a client set the header `Auth-Token` and it will potentially overwrite your `AUTH_TOKEN` header.

So while you can configure Nginx to allow underscored headers, the conclusion is still the same: when they reach Passenger they will be dropped to prevent CVE-2015-7519.

**Comment by giorgian** [comment]
@OnixGH I see. 
I wonder if there isn't some way to tell underscores from dashes, for instance: turn Auth-Token into HTTP_AUTH_TOKEN and Auth_Token into HTTP__AUTH_TOKEN (double underscore meaning there's an underscore in the original header).

My problem is that clients out there are already using underscores in requests to our servers; while fixing the server would be really easy for us, having all existing clients from different versions changed is not so easy, so for now my solution will be to have either Varnish or Nginx to convert incoming Auth_Token into Auth-Token.

**Comment by OnixGH** [comment]
@giorgian Sorry about the discomfort, actually the same vulnerability was discovered in Apache and the recommended workaround for user was to do exactly as you plan, to rewrite the underscored header.

We copied this workaround into our blog post about it, if you have a rewrite workaround for Nginx then we'd be happy to update the post to include this information as well for users of `underscores_in_headers on`?

B.t.w. we thought about escaping `-`, but it didn't get us very far within the SCGI limitations (for example using `__` would still collide with clients using `-Some-Header`, which also maps to `HTTP__SOME_HEADER`)

**Comment by OnixGH** [comment]
@hajimenomomo were you also using `directive underscores_in_headers on;` ?

**Comment by giorgian** [comment]
@OnixGH If I do implement this in Nginx I'll post a snippet.

Regarding the second part: yeah, I thought of that, but I would definitely block `-Some-Header`, as well as `Some--Header` etc. I'm not sure what the HTTP specification says about that, though.

**Comment by hajimenomomo** [comment]
I was just using the passenger standalone default configuration, without any specific directive.

**Comment by OnixGH** [comment]
@hajimenomomo so what about my questions? What HTTP headers are you sending exactly? Did you read about the underscore filtering? Can you change to dashes?

**Comment by hajimenomomo** [comment]
I am using an underscored header named x_user_token, just read about header filtering and trying to figure out a way to convert underscore headers into dash ones. My main problem is that all my clients are using underscored headers.

**Comment by OnixGH** [comment]
Closing this, as the filtering from the Passenger side is intentional.

**Comment by runephilosof** [comment]
It would be nice if you could write a more noticeable item in the changelog as this is backwards incompatible change for those using request headers with underscores (isn't that quite common?).
Searching through the changelog I was not able to identify the item causing my problems.
I had to ask google to find this issue.

**Comment by OnixGH** [comment]
@runephilosof done: https://github.com/phusion/passenger/commit/9ca81d481577fffe8e09bbc80ea8ef83a42b5ca9. Thanks for the suggestion.

**Comment by MarcosCunhaLima** [comment]
Well, for anyone suffering, I have solved this this way:

1) Intercept the request headers before Passenger have time to drop it.
2) Store it in another name without underscore.
3) Change my application to read the new request header.

So, although Passenger standalone has an "internal" nginx running and you could even set it up, it seems that when the request arrives at this nginx instance, Passenger have done its work and dropped out the headers with underscore in it.

So, what worked for me was:
1) Install a standalone nginx as a reverse proxy.
2) Change passenger configuration to listen to a different port (for instance, 8080).
3) Change standalone nginx configuration to get undescores headers saving it in other headers without it (so you can read them in your application).

There are good documentation in Passenger's site in order to go through items 1 and 2. To map a header to other variable, edit /**etc/nginx/nginx.conf**:

     // in http section:
     underscores_in_headers on;

     // in location section:
     proxy_set_header AuthToken $http_auth_token;

To create variables, Nginx adds a prefix 'http' and undescores all dashes. So, my header was 'auth_token' and to access it, the variable name is **$http_auth_token**. So, I saved it to other variable named AuthToken and I am able to read it in my application. 

Hope this helps.
