### ISSUE TITLE
High CPU load in Passenger Core percentage of requests freeze

### ISSUE THREAD

**Issue by tinco** [phusion/passenger#1709]
Under certain conditions requests appear to be getting stuck in Passenger 5.0.20 (no reponse) with a Ruby app.

Conditions:
The behavior most likely started after an increase in websocket connections (a script that makes one every N seconds was introduced recently). The server is not particularily high traffic, but each session is coupled to a websocket that tunnels I/O constantly. The server performs I/O with many backends, possibly leaking connections. We haven't managed to reproduce the conditions outside production yet.

Research:
`Thread 0x7fa221283700` is suspected to be stuck in `FdSinkChannel` (down the line from `RequestHandler::onRequestBody`), to be reviewed. 
`Thread 0x7fa219ef9700` looks to be stuck in a `runSync`, but that is likely a side-effect (e.g. frozen event loop).

Backtraces available here: (only for Phusion staff)
https://phusionnl.slack.com/files/niels/F0H3SPQHY/-.sh

**Comment by cbeckr** [comment]
We may have run into the same issue after updating to 5.0.23 (from version 4): The server peaks at 100% CPU doing basic ELB health checks; we're also using Websockets (Faye / EM).
Here's a gist: https://gist.github.com/cbeckr/e4559ed1e14fd34d2c44
What struck me was how all queued requests have the exact same timestamp.

**Comment by OnixGH** [comment]
Research into #1732 revealed it to be looping at exactly the same place (a write loop in FdSinkChannel), and the code in question was found to contain a wrong exit condition. Closing this as a duplicate.

**Comment by OnixGH** [comment]
@cbeckr I'm not sure your issue is the same. The gist mentions "Watchdog seems to be killed; forcing shutdown of all subprocesses", which is not a symptom of this issue (unless you were killing it manually). If the watchdog died without you killing it your system might be out of memory and killing processes, which can cause all sorts of trouble.

In any case we'll release a fix as part of 5.0.24 soon, so it's worth seeing if that makes a difference.

**Comment by cbeckr** [comment]
@OnixGH thanks for the update, we'll keep an eye out for 5.0.24.
The watchdog was killed since I also sent it a SIGQUIT, reading up on the guidance in the ["The right way to deal with frozen processes on Unix"] (http://old.blog.phusion.nl/2012/09/21/the-right-way-to-deal-with-frozen-processes-on-unix/). However, SIGQUIT is obviously only handled by the workers - something minor that could be clarified in the documentation.

**Comment by OnixGH** [comment]
@cbeckr the link you're referring to is pretty old, and we've been in the process of moving documentation into the [Passenger Library](https://www.phusionpassenger.com/library).

It's a work in progress (it's not completely there yet but the SIGQUIT part is mentioned [here](https://www.phusionpassenger.com/library/admin/standalone/overall_status_report.html)), but we'll take your comment into account :)
