### ISSUE TITLE
In passenger 5, deploying a rails app to a sub-URI throws No route matches issues

### ISSUE THREAD

**Issue by mingleiwang** [phusion/passenger#1722]
After I upgrade passenger from 4.0.59 to 5.0.18, deploying a rails app to a sub-URI throws **No route matches issues**.

In 4.0.59, I deployed a rails application using apache under "test.com/some-service", after I upgrade to 5.0.18, the rails log throws No route matches [GET] \"/some-service/ \ error. It seems like PassengerBaseURI doesn't take effect.

Does anyone experience the same issue?

**Comment by OnixGH** [comment]
Hi @mingleiwang, this sort of question is more suitable for the [forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger), unless you have a clear indication the issue is with passenger (Passenger 5 supports sub-uri's just fine as far as I know).

I would also recommend posting your config files without leaving out parts, configuration issues can be pretty sneaky.
