### ISSUE TITLE
NoMethodError: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by kyrylo** [phusion/passenger#1730]
Given this Sinatra app (or any Rack app)...

```ruby
require 'sinatra'

at_exit do
  puts 'CONFIG.RU AT_EXIT'
  if $!
    puts "EXITING BECAUSE OF AN EXCEPTION:"
    p $!
    p $!.backtrace
  end
end

get '/' { 'Hello world!' }
run Sinatra::Application
```

...launch it with `passenger start`. Then make a few requests and wait for 5 minutes (I don't know how tell Passenger to react quicker). When 5 minutes passed check your console and evidence this:

```
App 8923 stdout: CONFIG.RU AT_EXIT
[ 2016-01-22 15:01:45.3458 8875/7f3ae0e58700 age/Cor/CoreMain.cpp:794 ]: Disconnecting long-running connections for process 12434, application /home/kyrylo/code/airbrake-passenger-demo/public (development)
App 12434 stdout: CONFIG.RU AT_EXIT
App 12434 stdout: EXITING BECAUSE OF AN EXCEPTION:
App 12434 stdout: #<NoMethodError: undefined method `call' for nil:NilClass>
App 12434 stdout: []
[ 2016-01-22 15:01:50.2792 8875/7f3ae0e58700 age/Cor/CoreMain.cpp:794 ]: Disconnecting long-running connections for process 10205, application /home/kyrylo/code/airbrake-passenger-demo/public (development)
App 10205 stdout: CONFIG.RU AT_EXIT
App 10205 stdout: EXITING BECAUSE OF AN EXCEPTION:
App 10205 stdout: #<NoMethodError: undefined method `call' for nil:NilClass>
App 10205 stdout: []
```

The ppid when inside `at_exit` is `1`. This happens at least with these versions that I tested: `5.0.23` & `4.0.60`.

This issue was originally [reported at the Airbrake's issue tracker](https://github.com/airbrake/airbrake/issues/490), but when I debugged it I came to conclusion it's an issue with Passenger itself.

**Comment by OnixGH** [comment]
Thanks for reporting, we'll have a closer look. 

At a first glance I should note that this test is inconclusive as to whether there is a problem with Passenger (it might be, or not). The application is not exiting due to an exception, it's exiting because Passenger tells it to, since the pool idle time expired (default 5 mins, which you can adjust with the [pool idle time setting](https://www.phusionpassenger.com/library/config/reference/?a=passenger_pool_idle_time)).

Furthermore, anything along the way of the exit can raise an exception, not just Passenger. 

Is there anything you can tell us about whether you had a setup without this error before, and if so, what changed? And do you get it in any other circumstances than at application exit?

**Comment by kyrylo** [comment]
Thanks for the clarification. I don't use Passenger myself so I don't (and didn't) have any actual setup. I cannot tell for sure, but most likely it happens only on process exit.

I am a maintainer of the Airbrake gem and I encourage our users who also use Passenger to collaborate with @OnixGH to ease debugging of this problem.

**Comment by nick-desteffen** [comment]
I initially reported the issue.  We recently upgraded Airbrake from 4.x to the newly released version 5.0 and this exception started showing up across all of our applications.  We have been running Passenger v5.0.11 with Nginx 1.8.0 since last July (2015) and haven't received this exception before.  All of our applications are running Ruby 2.2.2 and Rails 4.2.x.

**Comment by FooBarWidget** [comment]
The bug has been fixed. See commit 4f898b0a79 for an explanation.

**Comment by scottsherwood** [comment]
@FooBarWidget Will version 4 also be patched with this fix?

**Comment by FooBarWidget** [comment]
No. Version 4 is practically unmaintained. We only release v4 hotfixes for enterprise customers in exceptional cases.

**Comment by jbertrand-siliconsalad** [comment]
> No. Version 4 is practically unmaintained. We only release v4 hotfixes for enterprise customers in exceptional cases.

I just want to add that AWS Elastic Beanstalk only propose the version 4 of passenger.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.ruby

I just asked them when do they plan to upgrade to the version 5.

**Comment by OnixGH** [comment]
@jbertrand-siliconsalad Yeah, we had noticed this. Good that you asked, the more users raise this with them the better the chances I hope!

**Comment by mathieujobin** [comment]
For some reason, Amazon Beanstalk offers Passenger 4.x as an option.
I wish to keep using Passenger, but if this patch it not backported, I might just switch to Puma out or simplicity...
