### ISSUE TITLE
Build passenger as a dynamic nginx module

### ISSUE THREAD

**Issue by clemensg** [phusion/passenger#1748]
Hi @FooBarWidget,

I just read the nginx changelog and apparently the fresh 1.9.11 version of nginx finally supports dynamically linked modules: http://nginx.org/en/docs/ngx_core_module.html#load_module

Would be great if the passenger module could be built as such to no longer require the tedious recompilation of the passenger module on every nginx version upgrade.

Thanks,
Clemens

**Comment by OnixGH** [comment]
Thanks for the heads up!

**Comment by OnixGH** [comment]
Review shows that this Nginx feature does not come with [a stable ABI](http://mailman.nginx.org/pipermail/nginx-devel/2016-February/007879.html), which is a basic requirement for Passenger.

For example, compiling Nginx with SSL on or off changes structures that Passenger depends on, so in order to prevent recompilation we would have to know how exactly the user's Nginx was compiled and provide precompiled packages for all (combinations of) configurations multiplied by every Nginx version.

So for now it doesn't seem doable.

**Comment by FooBarWidget** [comment]
We *can* make Passenger dynamically loadable. You just have to be aware of the restriction that you can only load it in an Nginx that is of the same version and that was compiled with the same parameters.

**Comment by sbagmeijer** [comment]
@FooBarWidget I think dynamic loadable would be great a very great addition I would love to see that.

**Comment by OnixGH** [comment]
Support added in: https://github.com/phusion/passenger/commit/e952d81d50b5401d8cc1cf58b811a94172b55adf. But as was said above, you'll still have to recompile it(!) whenever Nginx is changed (upgraded or compiled with different parameters) due to the lack of a stable ABI.

It does help avoid an Nginx compilation if it's just Passenger being upgraded.

**Comment by clemensg** [comment]
Thanks! :+1:
