### ISSUE TITLE
Unable to start Phusion Passenger Watchdog - Permission Error

### ISSUE THREAD

**Issue by yigitbacakoglu** [phusion/passenger#1801]
Hi  I am repopening this issue with reference #1470 , I am having same permission problem even my Passenger was installed in root - /user/local directory.  (update: I installed it both as root and as user, both have same problem)

```
[root@s13 ~]# which passenger
/usr/local/rvm/gems/ruby-2.2.2/bin/passenger
```

`Validating installation...

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓
 * Checking whether Apache is installed... ✓
 * Checking whether the Passenger module is correctly configured in Apache... ✓

`

```
[root@s13 ~]# passenger -v
Phusion Passenger 5.0.27

```
```
[root@s13 ~]# getenforce
Disabled
```

Centos 5.4
RVM
Apache
MySQL
Passenger

And the error log output:

```
[root@s13 ~]# tail -f /var/log/httpd/error_log
[Sat Apr 16 08:22:30 2016] [notice] SSL FIPS mode disabled
[ 2016-04-16 08:22:30.4608 16592/7a0b4d104730 age/Wat/WatchdogMain.cpp:1301 ]: Starting Passenger watchdog...
[Sat Apr 16 08:22:31 2016] [error] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start the Passenger core because exec("/usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.27/buildout/support-binaries/PassengerAgent") failed: Permission denied (errno=13)
[Sat Apr 16 08:22:31 2016] [warn] module ssl_module is already loaded, skipping
[Sat Apr 16 08:22:31 2016] [warn] module limitipconn_module is already loaded, skipping
[Sat Apr 16 08:22:31 2016] [notice] SSL FIPS mode disabled
[ 2016-04-16 08:22:31.5355 16603/6704aa021730 age/Wat/WatchdogMain.cpp:1301 ]: Starting Passenger watchdog...
[Sat Apr 16 08:22:32 2016] [error] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start the Passenger core because exec("/usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.27/buildout/support-binaries/PassengerAgent") failed: Permission denied (errno=13)
[Sat Apr 16 08:22:32 2016] [notice] Apache/2.2.3 (CentOS) PHP/5.3.3 mod_ssl/2.2.3 OpenSSL/0.9.8e-fips-rhel5 Phusion_Passenger/5.0.27 configured -- resuming normal operations

```

When I re-run passenger-install-apache2-module, this error message comes:

Before request:
```
(reverse-i-search)`er': sudo service httpd restart
[root@s13 ~]# tail -f /var/log/httpd/error_log
[ 2016-04-16 09:06:43.1610 28726/76950abd2730 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[Sat Apr 16 09:06:43 2016] [notice] SSL FIPS mode disabled
[ 2016-04-16 09:06:43.2113 28773/6bc20cae6730 age/Wat/WatchdogMain.cpp:1301 ]: Starting Passenger watchdog...
[ 2016-04-16 09:06:43.2240 28776/78f4dd02f730 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-04-16 09:06:43.2242 28776/78f4dd02f730 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-04-16 09:06:43.2350 28776/78f4dd02f730 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 28776
[ 2016-04-16 09:06:43.2396 28781/77517f580730 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-04-16 09:06:43.2403 28781/77517f580730 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 28781
[Sat Apr 16 09:06:43 2016] [notice] Apache/2.2.3 (CentOS) PHP/5.3.3 mod_ssl/2.2.3 OpenSSL/0.9.8e-fips-rhel5 Phusion_Passenger/5.0.27 configured -- resuming normal operations
[ 2016-04-16 09:06:43.3401 28719/6dd5c9328730 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished

```
After request:
```

[ 2016-04-16 09:06:43.3401 28719/6dd5c9328730 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
App 28983 stdout: 
App 28983 stderr: *** ERROR ***: Cannot execute /usr/local/rvm/gems/ruby-2.2.2/wrappers/ruby: Permission denied (13)
[ 2016-04-16 09:07:31.7397 28776/78f4cf75b940 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /container1/alsondemand/www/test/current: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 57299e0e
  Error details saved to: /tmp/passenger-error.4VqQUT
  Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
*** ERROR ***: Cannot execute /usr/local/rvm/gems/ruby-2.2.2/wrappers/ruby: Permission denied (13)
</pre>

[ 2016-04-16 09:07:31.7572 28776/78f4d8ffe940 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 57299e0e. Please see earlier logs for details about the error.

```

Can you please advise me ?

**Comment by yigitbacakoglu** [comment]
UPDATE: 
I've changed rvm directory permissions to 755 and now I am getting this error
https://www.dropbox.com/s/7szd8h1ndngqb92/Screenshot%202016-04-17%2022.56.57.png?dl=0

**Comment by OnixGH** [comment]
Sorry, I don't really see a clear indication of an issue is with Passenger. It rather looks like mismatching permissions your system. It's not about how you install Passenger, it's with which user / permissions you run it.

Please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for questions about your setup (we recommend posting as much info about how you configure / run Passenger it to avoid wasting time with guessing).

**Comment by jerome-diver** [comment]
@yigitbacakoglu Hi, i have the same issue than you and definitely not understand the link on web site page provided by passenger team for explain what's happen (instead of provide a simple solution/help for fix it).
@OnixGH Hi, i'm sorry but we are searchinf for help because we don't understand "your" debug page and we not find solution. Maybe you could try to help us by explain us what's happen and how to fix that. If you doesn't understand to, tell us, maybe we can give you more information for someone from passenger dev would be able to help for fix that.
It's a big pain now and we would like to find a solution, not see that all issue subject become simply closed without any solution provided.
So sure it is a problem of permission (that is what the error debug message said, i thing we can all read and understand it...) the problem stay: how to resolve this please ? I change permission of all the ~/.rvm repos many time for many differents users/group (never resolve nothing this way)... 
We are now searching for someone show us that he knows and understand something really and show that he wants to provide an help.
Thank you for help us.
(PS: i just follow your own tutorial about install passenger-nginx... exactly does the same for this link: https://www.phusionpassenger.com/library/install/nginx/install/oss/rubygems_rvm/  but faile)
what more please ?

**Comment by yigitbacakoglu** [comment]
Hi @jerome-diver, there is something is wrong in our system's installations. When I upgrade ruby and rails version on the system by installing rvm, I couldn't make it work again and the site was down. That's why I have to find immediate solution and after spending days, I changed PassengerDefaultUser to one of my root users to make it work. I know that has security problems but it solved the problem for my system. So you can change PassengerDefaultUser from nobody to root or similar.

https://www.phusionpassenger.com/library/config/apache/reference/#passengerdefaultuser

**Comment by OnixGH** [comment]
@jerome-diver I closed the issue because Github is not the place to discuss issues not related to Passenger. We usually cannot fix those anyway because it's not under our control (user permissions are a good example of that). You need to post to the [Community support forum ](https://groups.google.com/forum/#!forum/phusion-passenger) instead for help on that.

Sorry you've been struggling for a month, but I don't remember seeing any posts from you before now about this. If you post to the forum, please include as many details as possible about your system, it often happens that someone says they have the same problem but it turns out to be a totally different cause on their system.

**Comment by jerome-diver** [comment]
@yigitbacakoglu ok, i will not do that due o security raison but that is a solution, thank you.
I target (i think, i'm not sure) the problem of permissions because of rvm single/multi-user way of doing things. In this situation, my web site should be in the same directory of the user, or user used by passenger/nginx (http) should be on the group of the .rvm directory (who was in my own "jerome" user directory: /home/jerome/.rvm
So that is why i think the problem occur (and hope that will help other guys had or will have the same problem).
Then, finally, the solution(s) should be (not sure 100%) to: 
1/ add user used by passenger in the group of the group name content directory used by rvm gems (so... passengers gems are inside this). then stay in single-user installation rvm mode
2/ delete rvm from /home/... directories and install it in multi-user mode (so by default in /usr/local/rvm through sudo /curl.... installation commands.

PS: if for resolve some problem you try to use rvmsudo or sudo for install/bundle gems, you will break the mechanism in single-user mode...
For server installation, multi-user mode is a more stable solution maybe than single-user mode (single user mode is more for test code, do production things... etc...)
I don't know how to do without rvm, but i would like to know because rvm content is very heavy also.

@OnixGH ok yes, i think also this is more related to rvm problem than only passenger, for sure. But passenger is exposed to this real problem due to rvm or other... anyway... we are not searching for fault/responsabilities (we are not like that), but for resolve things and provide solutions. 
So this permissions things-related-problems are linked with passenger-nginx-rails (all together, permission is something that rvm/passenger/rails use in a particular way together due to there own constructions code... so they should not turn the head when problem exist... when passenger web site tutorials talk about nginx/rvm/rails, then he has to take care about practices of permissions in the real world to. 
Maybe yes, it is not the best place for talk about that. But because people talked about that, then it should be the good place for provide a great solution by the way of "help community". 
Isn't it ? Thank you for tolerance care of thinking and help community. Good job.

**Comment by jerome-diver** [comment]
i find solution and want to share it all place where people ask for help (it should not be a problem to provide help because someone decide it is not the best place... help is allways the best way to go).
SO... it is related to administration/installations things related with nginx, passenger and rvm in front of all.
there is two differents modes for install rvm and if you have ruby installed allready it should be a pain if you not well undertsand and use rvm commands tools (that was my origin of problems first).
Multi-user mode (installed with sudo) do create files on /usr/local/share and some other in /etc/. If you use this mode, you have to add the user of your web site inside rvm group and do nice attribution mak on your directory of web site.
Also, if after that you want to go back on single user mode, you have to delete by hand all files from multio-user mode, if you do not do that, single-user mode will never install (anbd rvm.io not explain that, but you have a part of page at the end of "troubleshootings" in rvm.io who list all the files to delete from multi-user mode, you have to look at them, because if no one tell you that,  you can not find them alone).
So if you choose single-user mode, you have to link the user who use the web site directory (maybe http or www-data or what else ?) with a directory (for example /home/http) by use the command usermod -d /home/http http (for user "http") and login on http, go in ~ dir and start single-user mode.
from there, don't forget to do: "rvmu use default" (this is important for do clean things in variables environment for the next steps, if you don't do that, you will what mixed root attributions and failed to run servers properly). do install passenger the easy way from there and rvmsudo passenger-install-nginx-module (not sudo).
You will have a clean install and should make a bundle install from directory of your web site (take car of file .rvmrc to not change things and make you confuse again....), after that it should works if rails doesn't ask for change part of code due to new way of doing things no more compatible with last version.
So passenger installed from rvm will failed to make running Rails application if these user points are not well cleaned (and it will not tell you the problem at install time or after... but maybe just make you more confuse without know or search the real problem origin from rvm not proper used)
In case of problem, best way for me was to delete/clean all (not the web site directory... sure, but all from rvm things) and do it again from clean initial position (this way should make win many times).

good luck... (now i think it should be closed and "resolved")
