### ISSUE TITLE
Error downloading passenger 5.0.28 for Ruby 2.3.1

### ISSUE THREAD

**Issue by morgoth** [phusion/passenger#1819]
I'm upgrading passenger from 5.0.27 to 5.0.28 and Ruby from 2.3.0 to 2.3.1
Error I'm getting is:

```
runuser -u app passenger-config build-native-support
 ---> Running in 1f8fd6eab35c
 [passenger_native_support.so] trying to compile for the current user (app) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1277kw8.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.28/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.28/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
```

**Comment by OnixGH** [comment]
As the error messages states, this is not an error downloading Passenger and it will function normally.

This is a warning about the native support libraries that are not essential, to learn why they cannot be compiled you need to look at /tmp/passenger_native_support-1277kw8.log,

**Comment by c-knowles** [comment]
What's the recommended way to install the native extensions using bundle install and Ruby 2.3.1? I was trying to find out and not sure where the best place to find out is so sorry if this is in the wrong place.

I checked out the logs for the install I'm doing and since rubyext binaries for 2.3.1 don't seem to be available at either [oss](https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/) or [s3](https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.30/) it ends up without the native extensions. I had a look through the code, it seems that the Makefile is hardcoded [here](https://github.com/phusion/passenger/blob/stable-5.0/src/helper-scripts/download_binaries/extconf.rb#L30) to return true rather than build if the download of the prepackaged binaries fail.

Assuming I'd like the performance boost of the native extension I was wondering if there is a better way than compiling separately and copying around `passenger_native_support.so`? Maybe customise the `BINARIES_URL_ROOT` env var? If the extensions are not supported any more or similar, happy to turn them off completely.

**Comment by OnixGH** [comment]
@c-knowles You can post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for help. We don't supply precompiled extensions for all Rubies, but there's no need to copy around things, Passenger automatically attempts to compile. If that fails then as said, you need to look at the error file.

**Comment by c-knowles** [comment]
OK sure I will ask there. Just for anyone checking here, there's nothing in the bundler logs and the output in the extensions folder only mentions download failure and nothing about compiling at all. I have a dozen or so other gems with native extensions, all have their appropriate extensions built (so don't think it's the current setup).

**Comment by mg1006** [comment]
I'm also having similar issue. I'm trying to run the application on passenger 5.0.30 standalone in CentOS 6 machine. As mentioned the application runs. However, a /tmp/passenger_native_support-xxxx.log file gets created every time the application gets a hit. Any help in this issue would be very much appreciated.

$ bundle exec passenger start
 [passenger_native_support.so] trying to compile for the current user (testapp) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-brhpqi.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.0-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.0-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
=============== Phusion Passenger Standalone web server started ===============

######################################################################

Contents of  /tmp/passenger_native_support-brhpqi.log 
  
# current user is: testapp
# mkdir -p /home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/buildout/ruby/ruby-2.3.0-x86_64-linux
# cd /home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/buildout/ruby/ruby-2.3.0-x86_64-linux
# /usr/local/rvm/wrappers/ruby-2.3.0@usage/ruby /home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/src/ruby_native_extension/extconf.rb
checking for alloca.h... *** /home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/src/ruby_native_extension/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=/home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/src/ruby_native_extension
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
        from /home/testapp/apps/1110/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/src/ruby_native_extension/extconf.rb:38:in `<main>'
        
#####################################################################     
        
Contents of mkmf.log 

have_library: checking for main() in -lstdc++... -------------------- yes

"gcc -o conftest -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/x86_64-linux -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC conftest.c  -L. -L/usr/local/rvm/rubies/ruby-2.3.0/lib -Wl,-R/usr/local/rvm/rubies/ruby-2.3.0/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-R/usr/local/rvm/rubies/ruby-2.3.0/lib -L/usr/local/rvm/rubies/ruby-2.3.0/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/x86_64-linux -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/usr/local/rvm/rubies/ruby-2.3.0/include/ruby-2.3.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC conftest.c  -L. -L/usr/local/rvm/rubies/ruby-2.3.0/lib -Wl,-R/usr/local/rvm/rubies/ruby-2.3.0/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-R/usr/local/rvm/rubies/ruby-2.3.0/lib -L/usr/local/rvm/rubies/ruby-2.3.0/lib -lruby -lstdc++  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))main; return !p; }
/* end */

**Comment by CamJN** [comment]
@mg1006 the relevant bit is `checking for alloca.h [...] failed` you are missing dev headers or they aren't in expected paths.
