### ISSUE TITLE
passenger_max_request_time setting kills all thread requests in a process when process not free for a number of seconds

### ISSUE THREAD

**Issue by dmitry** [phusion/passenger#1850]
I have a `thread` configuration for one of my application groups. Additionally I have `passenger_max_request_time` setting with value of 10 secs. When some of the requests in a process as thread works longer than 10 seconds, passenger kills this process with all the unfinished threads. 
More than that, I have 30 threads per process, and if process non-free for longer than 10 seconds (threads are working less than 10 seconds) with queue of threads - it just going to be killed as well with all the threads.

Process should be killed only in case when one of the threads works longer than 10 seconds, or better just kill only the thread in the process with the request that works longer 10 seconds (if that really possible at all).

Additionally once that fixed, documentation should point the threaded case as well, so anyone could notice that all the threads in the process will be killed by the passenger when one of the thread request exceeds number of seconds.

passenger enterprise 5.0.30/nginx
ubuntu 14.04
APT repo
Ruby 2.1.7, rbenv, Rails 3.2.2.22
Plain hardware used

**Comment by CamJN** [comment]
Hi @dmitry,

Unfortunately we can't make these changes because it introduces situations where a process never gets killed, or doesn't get killed in a reasonable amount of time. Consider the situation where a process is blocked on IO, the process' CPU time is then not increasing, and could potentially (depending on the operation) wait indefinitely. Since `passenger_max_request_time` exists to help limit the effects of misbehaving apps, we can't introduce situations where a misbehaving app can run forever.

As to killing individual threads, the unit of failure in modern OS' is the process, and killing just a thread can introduce instability if the threading model doesn't expect individual threads to be killed. And we need to consider many different models, mri, jruby, rubinius, node.js, python, and potentially more in the future.

**Comment by dmitry** [comment]
Hi @CamJN,

what about killing process, when subsequently process blocked by many threads more than 10 seconds? So each thread takes 1 second, but each of them are blocking process and then it gets killed.

**Comment by CamJN** [comment]
Regardless of the concurrency mode Passenger only tracks the time taken by individual requests, so if each request only takes 1 second, then passenger won't kill the process. So if you are seeing processes being killed then one or more threads is taking more than 10 seconds to finish a request.

**Comment by dmitry** [comment]
> So if you are seeing processes being killed then one or more threads is taking more than 10 seconds to finish a request.

I will try again, and hopefully that true, as we had timeouts in our application...
