### ISSUE TITLE
HTTP2 bug with apple devices

### ISSUE THREAD

**Issue by traxanos** [phusion/passenger#1866]
Hi,

we have big problem with the bundled nginx in your repository. customers got often an error during post data through HTTP2. So at the moment HTTP2 is not usable. A fix is still available. See: https://trac.nginx.org/nginx/ticket/959

It's possible to backport this patch in you repository?

**Comment by OnixGH** [comment]
This is not possible because we don't have an Nginx repository (we just bundle from the official source).

The fix is available in 1.11, so one solution would be to download that and use `passenger-install-nginx-module` with option 2 (customize) to compile Passenger against it.

**Comment by traxanos** [comment]
i know that you bundle it from official source. my hope was you ware able to integrate the patch before compiling. we have some hundreds of server based on your repository and many other people have the same problem, too. the problem exists with MSIE, too.

**Comment by OnixGH** [comment]
I understand, but unfortunately we can't (the source is downloaded straight to the user in some use cases).

The thread you linked to also warns that: "If you use such new, very complicated and actively developing protocol as HTTP/2 then it's naturally that you have to stay with the mainline branch.". If you disagree it would be better to focus efforts on convincing the good people of Nginx; after all, there are many more who would benefit rather than just Passenger/Nginx users if it was applied at the root.
