### ISSUE TITLE
Can passenger act as superserver?

### ISSUE THREAD

**Issue by mk-pmb** [phusion/passenger#1887]
**Question 1: What is the problem?**
(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:
I need a superserver for my node.js apps because I cannot afford to run all of them at the same time when I only need them occasionally and most often just for a few minutes.
I found node-systemd but it's cumbersome, and also it recommends to put an nginx in front of my service, so I thought maybe I can have that nginx manage my apps with passenger instead of systemd.
It could probably even do the socket activation based on URL paths instead of TCP port numbers!
However, I was unable to find any info in the readme, the github issues, and my favorite search engine, whether Passenger can act as a superserver, so I guess "not yet"?
Maybe passenger even manages to transport the peer IP address and port of the first request, that caused the app to be started. It seems like node-systemd can only do this for subsequent requests, when the app is still running.

**Question 2: Passenger version and integration mode**:
Your answer:
I'll try to use the latest open source deb package with Ubuntu's latest nginx.

**Question 3: OS or Linux distro, platform (including version)**:
Your answer:
Ubuntu 14.04.5 LTS trusty i686

**Question 4: Passenger installation method**:
Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer:
Node.js v6.8.1, npm v3.10.8, latest "[web](https://www.npmjs.com/package/web)" (that's an npm module name)

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer:
No.

**Question 7: Anything else about your setup that we should know?**
Your answer:
Some apps will need to run as a special user and/or group in order to write files in directories that "nobody" and "www-data" cannot access. (Minor; in case nginx can't do that already, sudo could.)

It would be great if I could use some templating to declare all subdirectory of my webapps directory as webapps and give them a default config, then write apps' custom config only if they need changes, and only those changes. (Minor; in case passenger can't do that already, puppet could.)

**Comment by OnixGH** [comment]
Yes, with Passenger you can serve multiple apps at one, in their own security domain (user)! Separation can be port-based or URI-based.

Passenger can spin up apps on request, and spin them down when there is no demand so that resources are used where you need them most.  This is all described in the [Passenger Library](https://www.phusionpassenger.com/library/).

See for example [passenger_pool_idle_time](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_pool_idle_time), [passenger_min_instances](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_min_instances), [passenger_user](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_user), [sub-uri deploy](https://www.phusionpassenger.com/library/deploy/nginx/deploy/nodejs/#deploying-an-app-to-a-sub-uri-or-subdirectory).

If you need help on specific features or configuration, please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger).

**Comment by mk-pmb** [comment]
Thanks! Would be nice if passenger could SEO for "superserver", esp. with "node" or "nodejs" in front. ;-)

**Comment by OnixGH** [comment]
We've just given the site a major overhaul, and are still finetuning SEO, thanks for the tip! :)
