### ISSUE TITLE
Setting passenger to not download native support still checks for download requirements

### ISSUE THREAD

**Issue by c-knowles** [phusion/passenger#1890]
**Question 1: What is the problem?**
- What is the expected behavior?
Setting the environment variable `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0` should not check the download requirements (wget/curl) and server should continue to run.

- What is the actual behavior?
When using the passenger ruby gem, setting the environment variable `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0` checks for downloading requirements (wget/curl) and the server exits with code 1. Since wget and curl are not available in the environment I'm in could passenger bypass these checks?

```
 --> Downloading a Phusion Passenger agent binary for your platform
Checking for basic prerequities...

 * Checking for A download tool like 'wget' or 'curl'...
      Found: no

---------------------------------------

No download tool found

This program requires a download tool, but none can be found on your system.
Please install one as follows:

    - Please install it with <b>apt-get install wget curl</b>

---------------------------------------

The Phusion Passenger agent binary could not be downloaded. Compiling it from source instead.

Checking for basic prerequities...

 * Checking for A download tool like 'wget' or 'curl'...
      Found: no

---------------------------------------

No download tool found

This program requires a download tool, but none can be found on your system.
Please install one as follows:

    - Please install it with <b>apt-get install wget curl</b>
/app/vendor/bundle/ruby/2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/rack_handler.rb:47:in `run': Error starting Passenger (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
Exiting
```

**Question 2: Passenger version and integration mode**:
open source 5.0.30 standalone

**Question 3: OS or Linux distro, platform (including version)**:
Debian 8

**Question 4: Passenger installation method**:
RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.3.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Yes, Docker 1.12.3 although the same behaviour is present natively.

**Question 7: Anything else about your setup that we should know?**
Nope

**Comment by OnixGH** [comment]
The `Phusion Passenger agent binary` is not native support, but a core Passenger executable. `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0` isn't supposed to affect that, so I don't see the issue.

N.B. if you must run without curl you can try the recommended way to install Passenger: via [apt-get](https://www.phusionpassenger.com/library/install/nginx/install/oss/jessie/).

**Comment by c-knowles** [comment]
Hmm, ok maybe it's a message issue then. The path I got to this was:

1. I got the above error on app startup
2. I installed curl
3. No prebuilt binary is available for Ruby 2.3.1 and the log message from passenger is below - it states to set `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0` to disable downloading
5. I set that and then since I don't need curl any more I removed it
6. Repeat but get the same error related to downloads

```
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
```

**Comment by OnixGH** [comment]
My guess is that you set `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0`, and then started with a fresh docker container without curl, expecting everything to work.

As the first error message tells you, Passenger needs wget / curl (on the first run) to finish installing essential dependencies like the PassengerAgent, or it won't be able to start.

After that curl is no longer needed and setting `PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0` will shorten the error message to `[passenger_native_support.so] not downloading because PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0`

**Comment by c-knowles** [comment]
OK, thanks that makes sense. Sorry for my confusion over the different downloads.

**Comment by sherbo** [comment]
I get this message also even though I (presumably) disabled the support binary check. In my Apache vhost file, I have this:

<VirtualHost *:80>
        SetEnv PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY 0 
       ....

Nevertheless, I keep seeing these messages in my error_log:
 E 2019-07-24 10:15:17.4315 13643/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 718e1913. Please see earlier logs for details about the error.
[ E 2019-07-24 10:15:17.4317 13643/Ta age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 718e1913. Please see earlier logs for details about the error.
App 13894 output:  [passenger_native_support.so] not compiling because PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
App 13894 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 13894 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 13894 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.2/rubyext-ruby-2.6.2-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 13894 output:      Trying next mirror...
App 13894 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.2/rubyext-ruby-2.6.2-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 13894 output:      Trying next mirror...
App 13894 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.2/rubyext-ruby-2.6.2-x86_64-linux.tar.gz: Connection timed out after 4001 milliseconds
App 13894 output:  [passenger_native_support.so] will not be used (can't compile or download) 
App 13894 output:   --> Passenger will still operate normally.

**Comment by CamJN** [comment]
@sherbo increase the [log level](https://www.phusionpassenger.com/docs/references/config_reference/apache/#passengerloglevel) to 7 and post the logs, there will likely be more useful info there.
