### ISSUE TITLE
PassengerAgent - No such file or directory

### ISSUE THREAD

**Issue by omegahd** [phusion/passenger#1896]
Passenger was working properly for over a year and yesterday Apache crashed and the log was indicating that Passenger was causing the problem so we updated Passenger to the latest version. Now when we try to open any website that is using Passenger we get the following error:

SpawnPreparerShell: line 0: exec: /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/buildout/support-binaries/PassengerAgent: cannot execute: No such file or directory

PassengerAgent file exists and has the correct permissions. We tried to reinstall and to recompile PassengerAgent, but nothing seems to work. The error itself makes no sense.

**Comment by OnixGH** [comment]
Are you the same reporter as this forum thread: https://groups.google.com/forum/#!topic/phusion-passenger/PP3Q4ort5h8 ?

**Comment by OnixGH** [comment]
Either way, please fill in the questions that you skipped when filing this issue. This report is too vague to act on. Questions below:

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

**Question 7: Anything else about your setup that we should know?**

Your answer:

**Comment by omegahd** [comment]
Question 1: What is the problem?

The problem has been described in the first post. You can open gramas.ba website to see the actual error. I can not find any more information that could be usefull.

Question 2: Passenger version and integration mode:

open source 5.0.30 apache

Question 3: OS or Linux distro, platform (including version):

CentOS 6 x64 with CloudLinux and cPanel/WHM

Question 4: Passenger installation method:

RubyGems, no Gemfile

Question 5: Your app's programming language (including any version managers) and framework (including versions):

Ruby 2.3.0, RVM, Rails 5.0.0

Question 6: Are you using a PaaS and/or containerization? If so which one?

No

Question 7: Anything else about your setup that we should know?

Nothing I can think of.

**Comment by OnixGH** [comment]
Aha, you are using CloudLinux. 

Was the previous version of Passenger that you upgraded from 5.0.27 or below by any chance?

If so then this is very likely a permission issue that you need to solve with CloudLinux (Passenger integrates with the CloudLinux LVE and CageFS since version 5.0.28).

**Comment by omegahd** [comment]
The previous version was 5.0.26. Can you give me more information about the permission issue ?

**Comment by OnixGH** [comment]
No, sorry, you should talk to CloudLinux about this. Passenger just obeys the security policies that are configured for the system, which we don't control.

If you manage to figure it out it would be very helpful to write that here though, so that other users who might experience something similar can solve it directly. If it is something common we might also add it to the [Passenger Library](https://www.phusionpassenger.com/library/).

**Comment by omegahd** [comment]
I managed to solve this problem. You need to add the path to PassegnerAgents to a conf file located in /etc/cagefs/conf.d. You can create a new file. Check other conf files in the folder to see how the contents should look like. Once added, run /usr/sbin/cagefsctl --update

Now I'm stuck at another error and I would apreciate any input on it.
This is the complete output:
[passenger_native_support.so] trying to compile for the current user (gramasba) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1i6457e.log
 [passenger_native_support.so] not downloading because passenger wasn't installed from a release package
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
/usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:121:in `initialize': No such file or directory - connect(2) for /tmp/passenger.4MCStsd/apps.s/preloader.13n94f (Errno::ENOENT)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:121:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:121:in `block in run_main_loop'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/utils.rb:65:in `block in retry_at_most'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/utils.rb:63:in `times'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/utils.rb:63:in `retry_at_most'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:118:in `run_main_loop'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:157:in `<module:App>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in `<main>'

It looks to me like Passenger can't write to /tmp folder ?

**Comment by OnixGH** [comment]
I would think that /tmp is also shielded with an access rights policy, that you need to configure?
