### ISSUE TITLE
Passenger Error 

### ISSUE THREAD

**Issue by Joshocan** [phusion/passenger#1939]
Nginx version : 1.80 
phusion passenger version : 5.0.10
Ruby version : 2.0.0p643

Problem: 
My web page produce 502 Bad Gateway error. Upon reviewing the logs in /var/log/nginx/error.log I found this error 
[error] 1245#0: *6358 connect() to unix:/tmp/passenger.KMnpQom/agents.s/server failed (111: Connection refused) while connecting to upstream, client: x.x.x.x , server: x.x.x.x , request: "GET / HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.KMnpQom/agents.s/server:", host: "x.x.com"

I restated nginx and everything is fine again. But Please I want to know what is cause of this problem and what i need to do prevent it from happening again. 

I need your assistance; 

thank you

**Comment by CamJN** [comment]
This is often caused by a process on your server "cleaning" the /tmp directory and removing the passenger instance directory there. You can move the dir elsewhere using the passenger_instance_registry_dir config option (https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_instance_registry_dir)

**Comment by FooBarWidget** [comment]
Not just that though. I've seen a different sort of error that causes this.

Check whether your server has multiple conflicting Nginx installations. I've seen a case in which the admin didn't realize that there were two Nginxes. Whenever Nginx #1 starts, it half-kills the already running Nginx #2. By half-killing I mean that it kills the master but not the workers. Because the master is gone, Passenger itself also goes way, but the workers keep running so they keep trying to contact the Passenger agent in vain.

**Comment by Joshocan** [comment]
Thank you @CamJN; your response has been very helpful. You are Gem.

**Comment by Joshocan** [comment]
@FooBarWidget !!! I checked, there is one instance of nginx server running. Thanks for your response though.
