### ISSUE TITLE
How to donate to the free software project

### ISSUE THREAD

**Issue by jasp00** [phusion/passenger#1941]
I would like to donate a symbolic amount (1€) to the free version. Is it possible?

**Comment by jasp00** [comment]
May I use your old [PayPal data](http://www.modrails.com/donate.html)?

**Comment by CamJN** [comment]
Thanks, but due to the efforts involved in processing the donation we will have to respectfully decline.
However, if you would like you can send your address and shirt size to camden@phusion.nl and we’ll send you a care package, since it’s the thought that counts.

**Comment by jasp00** [comment]
>you can send your address and shirt size

My address is jasp.net and my size is XL, but please do not send anything yet.

>due to the efforts involved in processing the donation we will have to respectfully decline.

Sorry for my ignorance, but I fail to see how processing a donation is more effort than sending a care package. I want to help the project; receiving a gift instead seems to do the opposite. Of course, I assume donors act in good faith and are not involved in credit fraud.

Since processing efforts are a problem for you, could you consider joining Software in the Public Interest? They handle this kind of donations. Here it is a list of [associated projects](https://www.spi-inc.org/projects/): LibreOffice, PostgreSQL, X.Org, etc. Non-contributing membership only [requires](https://www.spi-inc.org/membership/guidelines/) a valid email address. May I arrange this for you?

Since this is my first Passenger issue, you may ask about my motivation.

**Comment by prototype** [comment]
Hi Javier,

That's an excellent question. The answer to it might not seem obvious at first, but allow me to explain. Even though Passenger is available as an open source product, its efforts are sponsored by a commercial entity (the company Phusion).

As you can imagine, processing a donation as a commercial entity involves more steps than just simply accepting some cash. For one, it requires us to process this in our financial administration, taking into consideration potential tax rules etc... that might be applicable as well. 

In this particular case, we'd need to make an annotation that this is a donation and should be processed differently compared to regular commercial revenue. As you can imagine, that'd require someone from Phusion to work with our accountant to process this -- manually -- to keep our administration accurate. Let's just say that the hourly wages of these people are significantly higher than EU 1. So as much as we would appreciate your donation, the net effect would in fact be a loss for us. Bummer, right? :(

As Camden has already expressed, it's the thought that counts: we're already stoked that you found our software worthy of donating to! And in light of that, we wanted to reward *you* for being kind/thoughtful instead. So that's why we wanted to offer to send you a shirt + some stickers as a thank you for using our software; and hey, maybe you can put in a good word for us with your friends/employer/employees at the next watercooler party!

For future readers, if you want to monetarily support Phusion's efforts into maintaining and improving Open Source Passenger, consider buying an enterprise license. Our customers are the real heroes when it comes to our open source efforts in that they allow us to keep improving Passenger. In return, our customers get to leverage the additional features in the premium version of Passenger and we are able to provide them with support as well. Sounds like a pretty fair trade right? :-)

I hope this has answered your questions, and please let Camden know how he should proceed.

Cheers,
Ninh, co-founder Phusion

**Comment by CamJN** [comment]
Hi Javier, since you kindly offered to talk about your motivation, we'd love to hear about it.

**Comment by jasp00** [comment]
>since you kindly offered to talk about your motivation, we'd love to hear about it.

[TBH](https://en.wiktionary.org/wiki/TBH), I do not run Passenger. [Digitally Imported](http://www.di.fm/) does use Passenger Enterprise. I used to listen to DI.fm for free and I did for many years. I want to thank them, but they do not accept €1 donations either (minimum €7). Since I cannot help them directly, I am trying to help them through the tools they use: a better Passenger means a better Passenger Enterprise.

In my case, $1 discount from you to DI.fm would work. But this looks like a general problem with many free services. I guess someone (me) should set up PayPal accounts to gather donations, buy products and deliver them to random donors.
