### ISSUE TITLE
Q: rails streaming with response.stream.write

### ISSUE THREAD

**Issue by jrochkind** [phusion/passenger#1968]
If I'm using the rails4 streaming API to stream a response with eg `response.stream.write`, `response.stream.close`, and using Passenger (free version, not Enterprise)...

Is Passenger going to support streaming responses? Where the user-agent gets headers and starts streaming bytes as soon as they are available, even before the rails app has completed the response (with `stream.close`)?

This matters when you are sending a huge amount of data, and want the browser to start getting it without another layer (Passenger?) having to buffer it all first. 

Apologies, I tried googling and looking at Passenger docs for a while, and could not find a definitive answer.  Thank you for your advice!

**Comment by CamJN** [comment]
Rails streaming is supposed to work. Can you please provide the following information:

**Question 1: The problem**
- What is the actual behavior when you try and receive a streaming response?
- How can we reproduce it? Please try to provide a sample application (or dockerfile, Virtual Machine, etc.) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

**Question 6: Anything else about your setup that we should know?**

**Comment by jrochkind** [comment]
I believe I have verified it is indeed working, thanks and sorry!
