### ISSUE TITLE
Passenger 5.2.0 fails to start

### ISSUE THREAD

**Issue by distler** [phusion/passenger#2029]
After upgrading from 5.1.12 to 5.2.0. I get the following error in the Apache error log, when restarting Apache:

~~~~~
[Wed Jan 31 02:12:17.161574 2018] [passenger:error] [pid 56795:tid 140735142305792] *** Passenger could not be initialized because of this error: Null Value Passed to Value Constructor
[Wed Jan 31 02:12:17.404057 2018] [passenger:error] [pid 56795:tid 140735142305792] *** Passenger could not be initialized because of this error: Null Value Passed to Value Constructor
[Wed Jan 31 02:12:17.405845 2018] [mpm_event:notice] [pid 56795:tid 140735142305792] AH00489: Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.1 mod_fcgid/2.3.9 configured -- resuming normal operations
~~~~~

A normal startup, with the previous version, looks like

~~~~~
[Wed Jan 31 02:14:33.471235 2018] [mpm_event:notice] [pid 56880:tid 140735142305792] AH00489: Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.1 mod_fcgid/2.3.9 Phusion_Passenger/5.1.12 configured -- resuming normal operations
~~~~~

MacOSX 10.11
Apache 2.4.29
Passenger installed via Rubygems under Ruby 2.4

**Comment by CamJN** [comment]
By any chance did any crashreports get generated at either of these paths?
```
~/Library/Logs/DiagnosticReports
/Library/Logs/DiagnosticReports
```

**Comment by distler** [comment]
No; apache didn't crash. (In fact, it ran fine.) Passenger didn't start, which you can see from the "resuming normal operations" line in the log I attached.

**Comment by CamJN** [comment]
Oh, I meant crash reports for PassengerAgent, which seems like it would have crashed.

**Comment by distler** [comment]
>Oh, I meant crash reports for PassengerAgent

Sorry. Don't say any of those.

**Comment by sbourgeois1** [comment]
I am currently looking for help with similar issue. I do not understand the origin of the problem, and how to solve it.
Since my Ubuntu 16.04 system update of Jan 26 which includes a series of changes related to passenger, my apache2 server fails to start. 
As I am not a system expert, so despite my efforts, I cannot understand the reason. 
I have tried to reinstall based on https://www.phusionpassenger.com/library/install/apache/install/oss/xenial/, but no change...
The system keeps saying that I have a syntax error in the following instruction of the following file:
/etc/apache2/sites-enabled/redmine.conf
PassengerResolveSymlinksInDocumentRoot on

Here under the result of journalctl -xe
févr. 01 10:47:54 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4014s)
févr. 01 10:48:24 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4044s)
févr. 01 10:48:38 sbourgeois-HP-Pavillon gnome-session[1851]: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.d
févr. 01 10:48:38 sbourgeois-HP-Pavillon gnome-session[1851]: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.d
févr. 01 10:48:38 sbourgeois-HP-Pavillon gnome-session[1851]: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.d
févr. 01 10:48:45 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:48:45 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:48:46 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:48:54 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4074s)
févr. 01 10:48:55 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:48:55 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:48:55 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:49:22 sbourgeois-HP-Pavillon gnome-session[1851]: (gnome-software:1985): As-WARNING **: failed to rescan: Failed to parse /usr/share/a
févr. 01 10:49:24 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4104s)
févr. 01 10:49:35 sbourgeois-HP-Pavillon AptDaemon.Worker[15754]: INFO: Finished transaction /org/debian/apt/transaction/3766deb540484f37963b0939c
févr. 01 10:49:35 sbourgeois-HP-Pavillon org.debian.apt[899]: /usr/lib/python3/dist-packages/aptdaemon/progress.py:491: Warning: Source ID 41 was 
févr. 01 10:49:35 sbourgeois-HP-Pavillon org.debian.apt[899]:   GLib.source_remove(id)
févr. 01 10:49:35 sbourgeois-HP-Pavillon org.debian.apt[899]: /usr/lib/python3/dist-packages/aptdaemon/progress.py:491: Warning: Source ID 42 was 
févr. 01 10:49:35 sbourgeois-HP-Pavillon org.debian.apt[899]:   GLib.source_remove(id)
févr. 01 10:49:35 sbourgeois-HP-Pavillon org.debian.apt[899]: 10:49:35 AptDaemon.Worker [INFO]: Finished transaction /org/debian/apt/transaction/3
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]: /usr/bin/update-manager:28: PyGIWarning: Gtk was imported without specifying a versi
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]:   from gi.repository import Gtk
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]: /usr/lib/python3/dist-packages/UpdateManager/UnitySupport.py:29: PyGIWarning: Dbusme
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]:   from gi.repository import Dbusmenu, Unity
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]: /usr/lib/python3/dist-packages/UpdateManager/UnitySupport.py:29: PyGIWarning: Unity 
févr. 01 10:49:39 sbourgeois-HP-Pavillon gnome-session[1851]:   from gi.repository import Dbusmenu, Unity
févr. 01 10:49:54 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4134s)
févr. 01 10:50:09 sbourgeois-HP-Pavillon systemd[1]: Starting LSB: Apache2 web server...
-- Subject: Unit apache2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has begun starting up.
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]:  * Starting Apache httpd web server apache2
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]:  *
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]:  * The apache2 configtest failed.
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]: Output of config test was:
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]: AH00526: Syntax error on line 15 of /etc/apache2/sites-enabled/redmine.conf:
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]: Invalid command 'PassengerResolveSymlinksInDocumentRoot', perhaps misspelled or defined b
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]: Action 'configtest' failed.
févr. 01 10:50:09 sbourgeois-HP-Pavillon apache2[16566]: The Apache error log may have more information.
févr. 01 10:50:09 sbourgeois-HP-Pavillon systemd[1]: apache2.service: Control process exited, code=exited status=1
févr. 01 10:50:09 sbourgeois-HP-Pavillon systemd[1]: Failed to start LSB: Apache2 web server.
-- Subject: Unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has failed.
-- 
-- The result is failed.
févr. 01 10:50:09 sbourgeois-HP-Pavillon systemd[1]: apache2.service: Unit entered failed state.
févr. 01 10:50:09 sbourgeois-HP-Pavillon systemd[1]: apache2.service: Failed with result 'exit-code'.
févr. 01 10:50:18 sbourgeois-HP-Pavillon com.ubuntu.OneConf[1727]: WARNING:oneconf.hosts:Error in loading other_hosts file: [Errno 2] No such file
févr. 01 10:50:24 sbourgeois-HP-Pavillon org.freedesktop.PackageKit[1727]: DEBUG:Checking for inactivity (4164s)

**Comment by CamJN** [comment]
@sbourgeois1 that is an deliberate change in 5.2, see the release announcement: https://blog.phusion.nl/2018/01/29/passenger-5-2-0/#breakingchangeoverview

That said, please don't hijack other people's issue threads.

**Comment by boboroshi** [comment]
Replicated on CentOS 6:

```
[Thu Feb 01 15:51:57 2018] [error] *** Passenger could not be initialized because of this error: Null Value Passed to Value Constructor
[Thu Feb 01 15:51:57 2018] [notice] Apache/2.2.22 (Unix) DAV/2 mod_ssl/2.2.27 OpenSSL/1.0.1h PHP/5.5.38 configured -- resuming normal operations
```

**Comment by sbourgeois1** [comment]
Thanks for your quick reaction.
Now, I start understanding my problems.
It is not clear yet for me how I can solve them.

As far as I understand, I see I have to change at least the file /etc/apache2/sites-available/redmine.conf
This is probably very easy for an expert like you, but very tricky for a naïve user like me.
Can I ask you some suggestions?Here under is the content of this file.
Thanks in advance for any suggestion.
Kind Regards,
Serge

# fichier destiné à utiliser redmine via le port 3000 en http
<VirtualHost *:3000>
 # rendre appel possible via tripkit.dlinkddns.com:3000
 ServerName tripkit.dlinkddns.com
# rendre appel possible via www.tripkit.dlinkddns.com:3000
 ServerAlias www.tripkit.dlinkddns.com
# rendre appel possible via localhost:3000
 ServerAlias localhost
 # follow simlinks home/www-data pour qu'apache2 puisse accéder à la version de redmine en pointant sur redmine
   <Directory /home/www-data>
        Options +FollowSymLinks
        AllowOverride None
    </Directory>
 # Passenger a aussi un filtre pour bloquer les simlinks, bloqué par défaut. Il faut le débloquer.
 PassengerResolveSymlinksInDocumentRoot on
 # positionner apache dans les répertoires adhoc
 DocumentRoot /home/www-data/redmine/public
 PassengerAppRoot /home/www-data/redmine
 # définir les users pour ouvrir les accès aux répertoires www-data (sinon, on se retrouve avec le répertoire su user qui a fait linstallation!)
 PassengerDefaultUser www-data
 PassengerUser www-data
 PassengerDefaultGroup www-data
 PassengerGroup www-data
 PassengerDefaultGroup www-data
# Relax Apache security settings on public
  <Directory /home/www-data/redmine/public>
   AllowOverride all
   # MultiViews must be turned off.
   Options -MultiViews
   Require all granted
  </Directory>
# Relax Apache security settings on Gemfile and Gemfile.lock
  <Directory /home/www-data/redmine>
  <Files Gemfile>
      Require all granted
    </Files>
    <Files Gemfile.lock>
      Require all granted
    </Files>  
  </Directory>
# adresse de rails
  RailsBaseURI /home/www-data/redmine/bin
# si on veut un log specifique pour débugger les erreurs specifiques à passenger, activer la ligne ci-dessous.
# sinon, elles seront dans /var/log/apache2/errors.log
# PassengerLogFile /var/log/apache2/error_passenger.log
</VirtualHost>


Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr 

    Le jeudi 1 février 2018 à 16:06:38 UTC+1, Camden Narzt <notifications@github.com> a écrit :  
 
 
@sbourgeois1 that is an deliberate change in 5.2, see the release announcement: https://blog.phusion.nl/2018/01/29/passenger-5-2-0/#breakingchangeoverview

That said, please don't hijack other people's issue threads.

**Comment by CamJN** [comment]
@boboroshi can you enable core dumps and see if you get a dump from the passenger agent?

**Comment by CamJN** [comment]
@sbourgeois1 This is not a support forum, this is a bug tracker and you are distracting from an issue that is not related to your problem. Please ask your question on stack overflow: https://stackoverflow.com/questions/ask?tags=passenger

**Comment by sbourgeois1** [comment]
Sorry. Thanks.


Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr 

    Le jeudi 1 février 2018 à 17:26:15 UTC+1, Camden Narzt <notifications@github.com> a écrit :  
 
 
@sbourgeois1 This is not a support forum, this is a bug tracker and you are distracting from an issue that is not related to your problem. Please ask your question on stack overflow: https://stackoverflow.com/questions/ask?tags=passenger

**Comment by boboroshi** [comment]
@CamJN looking to see how I might do that (a bit out of my league...)

**Comment by boboroshi** [comment]
@CamJN Followed these instructions https://www.unixmen.com/how-to-enable-core-dumps-in-rhel6/ and restarted the httpd service, no dump shows up in `/tmp`.

Going to uninstall/reinstall as I feel there's probably some cruft lying around that's causing this.

**Comment by boboroshi** [comment]
Rolled back to 5.1.12 as I can't be down all day.

**Comment by FooBarWidget** [comment]
Here are tips w.r.t. how to debug this issue. The error message's prefix ("[Wed Jan 31 02:12:17.161574 2018] [passenger:error] [pid 56795:tid 140735142305792]") suggests that this is an error that that Apache has logged, i.e. it must be an error occurring within the Passenger Apache module. Furthermore, this is not a segfault, otherwise we would see Apache's master process complaining about segfaulted workers. So it is not surprising that there is no core dump.

Grepping for "could not be initialized because of this error" in the Passenger source tree yielded this result for me: src/apache2_module/Hooks.cpp, function init_module:

~~~
	} catch (const std::exception &e) {
		ap_log_error(APLOG_MARK, APLOG_ERR, 0, s,
			"*** Passenger could not be initialized because of this error: %s",
			e.what());
~~~

This confirms that it is an error that occurred within the Passenger Apache module. The source is the caught exception.

This leaves the following question: what is the origin of the exception? There are a few strategies we can follow:

 * Getting rid of the `catch` and allow the exception to crash the Apache worker. With the right system settings, this will result in a core dump that we can inspect.
 * Insert log print statements at strategic places to find out where it crashes.

Both strategies require cooperation from the user who's able to reproduce the problem.

If I grep for "Null Value Passed to Value Constructor" in the Passenger source tree then I find:

~~~
src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp
2854:  JSON_ASSERT_MESSAGE(value != NULL, "Null Value Passed to Value Constructor");
~~~

So we know that this is an exception thrown by the jsoncpp library. The biggest change in Passenger 5.2.0's Apache module is the deterministic configuration system, of which the configuration manifest generator is a huge part. The config manifest generator is the subsystem that converts the Apache configuration into a JSON description, and it would not surprise me if there is a bug in that subsystem. Its source is in src/apache2_module/ConfigGeneral/ManifestGeneration.h.

**Comment by CamJN** [comment]
@distler @boboroshi would either of you mind providing your passenger configs? This would go much faster if I could reproduce the issue locally.

**Comment by distler** [comment]
~~~~~
PassengerRoot /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.12
PassengerDataBufferDir /tmp
PassengerInstanceRegistryDir /tmp
PassengerLogFile /var/log/passenger.log

PassengerDefaultRuby /usr/local/bin/ruby24
PassengerUserSwitching on
PassengerMinInstances 2
PassengerMaxInstancesPerApp 6
PassengerMaxPoolSize  12
PassengerPreStart https://golem.ph.utexas.edu/wiki/web_list
PassengerPreStart https://golem.ph.utexas.edu/class-S/E7/
PassengerPreStart https://golem.ph.utexas.edu/class-S/E8/
PassengerPreStart https://golem.ph.utexas.edu/forum/
PassengerPreStart https://golem.ph.utexas.edu/dingus/maruku/json
PassengerPreStart https://golem.ph.utexas.edu/dingus/maruku-math/json
PassengerCtl hook_spawn_failed /usr/local/bin/spawnfailed.rb

PassengerBaseURI /wiki
PassengerBaseURI /class-S/E7
PassengerBaseURI /class-S/E8
PassengerBaseURI /forum
PassengerBaseURI /dingus/maruku
PassengerBaseURI /dingus/maruku-math

<Directory /Library/WebServer/Documents/wiki>
    PassengerAllowEncodedSlashes on
</Directory>

<Location /forum>
  PassengerAllowEncodedSlashes on
  PassengerRuby /usr/local/bin/ruby21
</Location>

<Location /dingus>
  PassengerAllowEncodedSlashes on
</Location>

~~~~~

**Comment by CamJN** [comment]
Awesome, thanks.

**Comment by CamJN** [comment]
@distler Do you have a ServerName defined? It seems that the issue is that Passenger is not able to find one in the Apache config.

**Comment by distler** [comment]
There are several `ServerName` directives, each one wrapped in a `<VirtualHost>` directive.

**Comment by CamJN** [comment]
@distler Can you test the https://github.com/phusion/passenger/tree/GH2029-Apache_config_processing_issue branch on your box? If the issue was arising in the same place for both of us, it will be fixed, if not it will print a stack trace to your passenger log pointing to where the null value is being created.

**Comment by distler** [comment]
Please excuse the Noob question. I am accustomed to installing Passenger as a Gem. What's the procedure for installing it from source?

**Comment by CamJN** [comment]
No problem, to use the branch you follow these steps:
```
git clone https://github.com/phusion/passenger.git
cd passenger
git submodule init
git submodule update
bin/passenger-install-apache2-module 
```
And after that point you should be pretty familiar with the process.

**Comment by CamJN** [comment]
Sorry I forgot to point out how to switch to the right branch, hopefully you weren't past that point yet. instructions are updated now.

**Comment by distler** [comment]
Seems to work fine now. You can close this issue (at least as far as I am concerned).

**Comment by sbourgeois1** [comment]
Hello,
Sorry to come back, but I could not solve the problem in my environment.

Of course, I am a novice in system software, and not used to install system components such as passenger (I installed around 2 years ago by following the redmine installation steps).
So, I applied the recipe described in the mail here under, but, as I suspected, as there is no change in the file /etc/apache2/sites-enables/redmine.conf,, it is normal that I get excaltly the same Syntax error on line15 of the file, containing the instruction 'PassengerResolveSymlinksInDocumentRoot'.

Context:On my server, apache2 is used to serve 2 applications: Redmine and a Python app developped with the Web2py framework, and lightly integrated with the ruby Redmine app.

Fortunetely, when I disable the passenger module and the redmine site, apache2 still serves toe python app.
Thanks in advance for explanation on what to do to reverse the passenger upgrade with gem, and to block the future upgrades with the Ubuntu Software Updater.

Best regards,Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr 

    Le vendredi 2 février 2018 à 21:46:07 UTC+1, Camden Narzt <notifications@github.com> a écrit :  
 
 
No problem, to use the branch you follow these steps:
git clone https://github.com/phusion/passenger.git
cd passenger
git submodule init
git submodule update
bin/passenger-install-apache2-module 

And after that point you should be pretty familiar with the process.

**Comment by boboroshi** [comment]
Let me know if you still want my configs. There's a very long `vhosts.conf` in `conf.d`, one vhost in `ssl.conf`, and then the relatively minimal `passenger.conf` in `conf.d`. I have this installed from yum as well.

**Comment by distler** [comment]
@boboroshi, you might want to try the branch @CamJN suggested.

In my case, the problem was that `ServerName` was only defined inside of `<VirtualHost>`s, and *not* in the top-level configuration (which is perfectly fine, as far as Apache is concerned). Passenger 5.2.0 didn't like that, though.

This is fixed on the new branch.
