### ISSUE TITLE
Rotation using a pipe not working

### ISSUE THREAD

**Issue by charleneChen** [phusion/passenger#2067]
https://www.phusionpassenger.com/library/admin/nginx/log_rotation.html

I follow the instruction, and after done, all my applications shut down and cannot restart again

error shows:

```
An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: ef76a5ad
  Error details saved to: /tmp/passenger-error-T7v5KQ.html
  Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)
```

https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems

this link is helpless

**Comment by OnixGH** [comment]
Hi, the instructions work for me with the latest Passenger, so we don't know why it's not working for you. 

Please provide more information about your setup by filling in the questions below.

## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**
Please read our troubleshooting and debugging guides first:
https://www.phusionpassenger.com/library/admin/troubleshooting/
https://www.phusionpassenger.com/library/admin/

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

**Question 7: Anything else about your setup that we should know?**

Your answer:

**Comment by charleneChen** [comment]
**Question 1: What is the problem?**
![11](https://user-images.githubusercontent.com/7545977/39282303-614942ea-493b-11e8-96b1-2ffff3b5cf82.png)
![12](https://user-images.githubusercontent.com/7545977/39282304-6648bcee-493b-11e8-83b5-491db936f022.png)

I did follow the instruction, and print out the PID? but no process existed, because 

```
killall -HUP pipetool
pipetool: no process killed
```

And, all my applications in the control of passenger just shut down

I tried to restart nginx, the passenger started but not the applications

```
An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: ef76a5ad
  Error details saved to: /tmp/passenger-error-T7v5KQ.html
  Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)
```

**Question 2: Passenger version and integration mode:**
Passenger 5.1.6/ nginx 1.10.3

**Question 3: OS or Linux distro, platform (including version):**
```
cat /proc/version
Linux version 2.6.32-279.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) )
```

**Question 4: Passenger installation method:**
RubyGems, no Gemfile


**Question 5: Your app's programming language (including any version managers) and framework (including versions):**
one application: ruby 2.2.4p230, RVM, Rails 4.2.5
another one: ruby 2.4.1p111, RVM, Rails 5.1.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
NO

**Question 7: Anything else about your setup that we should know?**
using rvm to install ruby, so ruby executable not listed in `/usr/bin/`

**Comment by charleneChen** [comment]
Finally, I commented `passenger_log_file` and restart nginx, then everything works
