### ISSUE TITLE
nginx service error after installing passenger with nginx and Ubuntu 18.04 (AWS)

### ISSUE THREAD

**Issue by guigs** [phusion/passenger#2180]
**Question 1: What is the problem?**

- What is the expected behavior?

I'm trying to install Passenger + nginx on Ubuntu 18.04 following the instructions on https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/aws/nginx/oss/bionic/install_passenger.html. On Step 2 when I run `sudo service nginx restart` nginx service should be restarted successfully.

- What is the actual behavior?

But instead it gives 

```
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```

- How can we reproduce it? 

I've just launch a new AWS EC2 instance (type t3.micro) with Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0ac019f4fcb7cb7e6 (64-bit x86).

Then run `sudo apt update` and `sudo apt upgrade`.

I've installed Ruby 2.5.3 using rbenv and then tried to install Passenger using instructions from https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/aws/nginx/oss/bionic/install_passenger.html.

Step 1 went ok and step 2 was looking good until discover that nginx service is failing to running.

Also, when I run: 

`sudo /usr/bin/passenger-config validate-install` it displays:

````
What would you like to validate?
Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Passenger itself
   ⬡  Apache
````

Which is odd, because I've installed `libnginx-mod-http-passenger` and not `libapache2-mod-passenger`.

If I select both I get:

````
 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓
 * Checking whether Apache is installed... ✗

   Apache is not installed. You can solve this as follows:
   
   Please install it with apt-get install apache2
````

And this is result from running `sudo /usr/sbin/passenger-memory-stats` 

````
Version: 6.0.1
Date   : 2019-02-14 16:22:18 +0000
------------- Apache processes -------------
*** WARNING: The Apache executable cannot be found.
Please set the APXS2 environment variable to your 'apxs2' executable's filename, or set the HTTPD environment variable to your 'httpd' or 'apache2' executable's filename.


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


--- Passenger processes ---

### Processes: 0
### Total private dirty RSS: 0.00 MB
````

**Question 2: Passenger version and integration mode**:

Open source 6.0.1/nginx

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 18.04 from AWS AMI ami-0ac019f4fcb7cb7e6

**Question 4: Passenger installation method**:

[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework 

rbenv Ruby 2.5.3, Node.js 8.10.0

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Question 7: Anything else about your setup that we should know?**

I don't know. Ask me ;)

**Comment by CamJN** [comment]
Please post the contents of your /var/log/nginx/error.log (or equivalent).

**Comment by guigs** [comment]
@CamJN `/var/log/nginx/error.log` is empty (0 bytes).

**Comment by guigs** [comment]
Here is the exact steps to reproduce it:

Launch new a AWS EC2 instance of type t3.micro with Ubuntu 18.04 (AMI ID
ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180912 (ami-0ac019f4fcb7cb7e6))

Then connect to it via ssh and run:

````
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/89e798aeada2fa069a0de550bd283ab45995bba8/bin/rbenv-installer | bash
export RBENV_ROOT="${HOME}/.rbenv"
export PATH="${RBENV_ROOT}/bin:${PATH}"
eval "$(rbenv init -)"
sudo apt update
sudo apt -y install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
rbenv install 2.5.3
rbenv global 2.5.3
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update
sudo apt-get install -y libnginx-mod-http-passenger
if [ ! -f /etc/nginx/modules-enabled/50-mod-http-passenger.conf ]; then sudo ln -s /usr/share/nginx/modules-available/mod-http-passenger.load /etc/nginx/modules-enabled/50-mod-http-passenger.conf ; fi
sudo ls /etc/nginx/conf.d/mod-http-passenger.conf
sudo service nginx restart
````

After running last command, it shows:

````
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
````

And nginx is not running.

**Comment by pscdodd** [comment]
What is the output of
"sudo systemctl status nginx.service" and "sudo journalctl -xe"
??

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Guilherme Goettems Schneider<mailto:notifications@github.com>
Gesendet: Montag, 25. Februar 2019 15:08
An: phusion/passenger<mailto:passenger@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [phusion/passenger] nginx service error after installing passenger with nginx and Ubuntu 18.04 (AWS) (#2180)


Here is the exact steps to reproduce it:

Launch new a AWS EC2 instance of type t3.micro with Ubuntu 18.04 (AMI ID
ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180912 (ami-0ac019f4fcb7cb7e6))

Then connect to it via ssh and run:

curl -fsSL https://github.com/rbenv/rbenv-installer/raw/89e798aeada2fa069a0de550bd283ab45995bba8/bin/rbenv-installer | bash
export RBENV_ROOT="${HOME}/.rbenv"
export PATH="${RBENV_ROOT}/bin:${PATH}"
eval "$(rbenv init -)"
sudo apt update
sudo apt -y install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
rbenv install 2.5.3
rbenv global 2.5.3
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update
sudo apt-get install -y libnginx-mod-http-passenger
if [ ! -f /etc/nginx/modules-enabled/50-mod-http-passenger.conf ]; then sudo ln -s /usr/share/nginx/modules-available/mod-http-passenger.load /etc/nginx/modules-enabled/50-mod-http-passenger.conf ; fi
sudo ls /etc/nginx/conf.d/mod-http-passenger.conf
sudo service nginx restart


After running last command, it shows:

Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.


And nginx is not running.

**Comment by guigs** [comment]
````
$ sudo systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-02-25 15:45:09 UTC; 11s ago
     Docs: man:nginx(8)
  Process: 22218 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=203/EXEC)

Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed to execute command: No such file or directory
Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Control process exited, code=exited status=203
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Failed with result 'exit-code'.
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
````

````
$ sudo journalctl -xe
Feb 25 15:44:56 ip-172-30-0-75 sudo[21619]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/bin/apt-get install -y libnginx-mod-http-passenger
Feb 25 15:44:56 ip-172-30-0-75 sudo[21619]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.
Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.
Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.
Feb 25 15:45:06 ip-172-30-0-75 sudo[21619]: pam_unix(sudo:session): session closed for user root
Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/sbin/service nginx restart
Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit nginx.service has begun starting up.
Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed to execute command: No such file or directory
Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory
-- Subject: Process /usr/sbin/nginx could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/sbin/nginx could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Control process exited, code=exited status=203
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Failed with result 'exit-code'.
Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit nginx.service has failed.
-- 
-- The result is RESULT.
Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]: pam_unix(sudo:session): session closed for user root
Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/systemctl status nginx.service
Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]: pam_unix(sudo:session): session closed for user root
Feb 25 15:46:24 ip-172-30-0-75 sudo[22235]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe
Feb 25 15:46:24 ip-172-30-0-75 sudo[22235]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
````

**Comment by pscdodd** [comment]
Is nginx installed? Try

sudo apt install nginx

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Guilherme Goettems Schneider<mailto:notifications@github.com>
Gesendet: Montag, 25. Februar 2019 16:49
An: phusion/passenger<mailto:passenger@noreply.github.com>
Cc: Dodd, Paul Sutton (UB)<mailto:paul.dodd@ub.unibe.ch>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [phusion/passenger] nginx service error after installing passenger with nginx and Ubuntu 18.04 (AWS) (#2180)


$ sudo systemctl status nginx.service ● nginx.service - A high performance web server and a reverse proxy server Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Mon 2019-02-25
 15:45:09 UTC; 11s ago Docs: man:nginx(8) Process: 22218 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=203/EXEC) Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Starting A high performance web server and a reverse proxy
 server... Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed to execute command: No such file or directory Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory
 Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Control process exited, code=exited status=203 Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Failed with result 'exit-code'. Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Failed to start A
 high performance web server and a reverse proxy server.

$ sudo journalctl -xe

Feb 25 15:44:56 ip-172-30-0-75 sudo[21619]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/bin/apt-get install -y libnginx-mod-http-passenger

Feb 25 15:44:56 ip-172-30-0-75 sudo[21619]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)

Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.

Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.

Feb 25 15:45:04 ip-172-30-0-75 systemd[1]: Reloading.

Feb 25 15:45:06 ip-172-30-0-75 sudo[21619]: pam_unix(sudo:session): session closed for user root

Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/sbin/service nginx restart

Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)

Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Starting A high performance web server and a reverse proxy server...

-- Subject: Unit nginx.service has begun start-up

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

--

-- Unit nginx.service has begun starting up.

Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed to execute command: No such file or directory

Feb 25 15:45:09 ip-172-30-0-75 systemd[22218]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory

-- Subject: Process /usr/sbin/nginx could not be executed

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

--

-- The process /usr/sbin/nginx could not be executed and failed.

--

-- The error number returned by this process is 2.

Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Control process exited, code=exited status=203

Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: nginx.service: Failed with result 'exit-code'.

Feb 25 15:45:09 ip-172-30-0-75 systemd[1]: Failed to start A high performance web server and a reverse proxy server.

-- Subject: Unit nginx.service has failed

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

--

-- Unit nginx.service has failed.

--

-- The result is RESULT.

Feb 25 15:45:09 ip-172-30-0-75 sudo[22212]: pam_unix(sudo:session): session closed for user root

Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/systemctl status nginx.service

Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)

Feb 25 15:45:20 ip-172-30-0-75 sudo[22232]: pam_unix(sudo:session): session closed for user root

Feb 25 15:46:24 ip-172-30-0-75 sudo[22235]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe

Feb 25 15:46:24 ip-172-30-0-75 sudo[22235]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)



―

**Comment by guigs** [comment]
Hey, that seems to fix it :man_facepalming:

I thought it would be installed as dependency of libnginx-mod-http-passenger.
Anyway, I think this should be made clearer in docs. 

The docs mention launching a server from Amazon EC2, then installing Ruby and then installing Passenger. It should mention installing nginx if I have selected nginx in "Pick an integration mode" doc page.

**Comment by pscdodd** [comment]
Yes, this is a bug in the documentation or the libnginx-mod-http-passenger package.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Guilherme Goettems Schneider<mailto:notifications@github.com>
Gesendet: Montag, 25. Februar 2019 17:25
An: phusion/passenger<mailto:passenger@noreply.github.com>
Cc: Dodd, Paul Sutton (UB)<mailto:paul.dodd@ub.unibe.ch>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [phusion/passenger] nginx service error after installing passenger with nginx and Ubuntu 18.04 (AWS) (#2180)


Hey, that seems to fix it 🤦‍♂️

I thought it would be installed as dependency of libnginx-mod-http-passenger.
Anyway, I think this should be made clearer in docs.

The docs mention launching a server from Amazon EC2, then installing Ruby and then installing Passenger. It should mention installing nginx if I have selected nginx in "Pick an integration mode" doc page.

**Comment by CamJN** [comment]
It's better called out in the new docs: https://www.staging.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/aws/ruby/nginx/
