### ISSUE TITLE
Is passenger supported on ubuntu 19.04?

### ISSUE THREAD

**Issue by Bdoom** [phusion/passenger#2223]
What versions of ubuntu are supported for passenger? I had installed it on ubuntu 19.04 but it sounds like 18.04 isn't supported either. I'm curious, do I need to use 16.04 or something?

Could someone give me a list of supported OSes and environments? Maybe a list of minimum requirements as well?

**Comment by CamJN** [comment]
If by supported you mean we have .deb packages in our apt repo, then we support ubuntu 16.04, 18.04, and 19.04. And debian 8, 9, and 10.

The ubuntu 19.04 and debian 10 packages were delayed quite a bit (until just this week actually) so depending on when you did your test that could have been the issue. Otherwise, please elaborate on what went wrong.
