### ISSUE TITLE
Change .passenger folder path

### ISSUE THREAD

**Issue by connecticus** [phusion/passenger#2321]
I'm currently trying to get a ruby on rails app running on a server with ISPConfig using nginx with passenger. The problem is, that ispconfig doesn't allow any modification of the home directory (/var/www/clients/CLIENT/WEBX) of the web user. When I set up the app in that folder I get an error saying that it wasn't able to create the .passenger folder:

Is there a way to make it create that folder somewhere else other than changing the home folder of the corresponding user?

Thank you!

**Comment by CamJN** [comment]
You can provide the binaries to Passenger in the support binaries directory.
The default path to that dir can be found with `passenger-config about support-binaries-dir`.
If that path is acceptable then you can use `passenger-config install-agent` to grab the PassengerAgent bianry and put it in the dir. If you need to override the HOME dir in order to download the binary you can use `HOME=/new/path passenger-config install-agent` to do so.
