### ISSUE TITLE
Debian 11 suport

### ISSUE THREAD

**Issue by darkBuddha** [phusion/passenger#2380]
Hi guys, any idea when Debian Bullseye will be supported? 
Thanks!

**Comment by CamJN** [comment]
The only remaining blocker is this bug: https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/1916633
The fixed version mentioned in the bug report is in impish (https://packages.ubuntu.com/impish/ubuntu-dev-tools) but the current version available from focal is https://packages.ubuntu.com/focal/ubuntu-dev-tools I've checked and there is a request in to backport the change to focal (https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/1934452) but it hasn't been done yet. 

Our build box runs focal, so we need to be able to get this backported or otherwise installed on focal to make a debian 11 bullseye release.

**Comment by darkBuddha** [comment]
Thanks! Interesting that you run Ubuntu instead of Debian.

**Comment by CamJN** [comment]
We build both ubuntu and debian images from the same host, and it's _usually_ easier to build on ubuntu.

**Comment by CamJN** [comment]
New bug to track: https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/1947192

**Comment by CamJN** [comment]
I had to upgrade our build machine to impish, next release should have debian 11 packages.

**Comment by darkBuddha** [comment]
Excellent, thanks for information and effort!

**Comment by darkBuddha** [comment]
https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install/oss/bullseye.html 

So, it's available now? Thanks!

**Comment by joolswills** [comment]
Just to note - the version number for the bullseye version was lower than the latest I had on buster when upgrading and I had to use aptitude to downgrade from the buster version of passenger to the bullseye one (I probably could have forced it with apt-get install passenger=VERSION also). Maybe the versions  could be changed so this doesn't happen though (6.0.9-1~buster1 is newer than 6.0.9-1~bullseye1).

**Comment by CamJN** [comment]
I think this is because when apt sorts the packages, `l` comes before `s` alphabetically (the actual version is the same). Probably a happy accident for ubuntu that their version names avoid this by always advancing the leading character alphabetically, but a nice perk in that ecosystem.
