### ISSUE TITLE
apt-get failing across the board

### ISSUE THREAD

**Issue by xandroxygen** [phusion/passenger#2381]
similar to #2142 , all installs fail with 
```
Err:8 https://oss-binaries.phusionpassenger.com/apt/passenger focal Release
[2021-09-30T14:12:18.146Z]   Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 109.107.35.58 443]

E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file.
```
This is blocking all builds

**Comment by CamJN** [comment]
Probably related: https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

**Comment by FooBarWidget** [comment]
This is not related to 2142 because it's not a GPG key problem. Instead, this is a TLS certificate trust problem. It seems the TLS certificate that Let's Encrypt hands out to our server, isn't trusted by your server.

I've just tested this on Ubuntu 20.04 and it works for me. Have you tried installing any ca-certificates updates?

**Comment by xandroxygen** [comment]
thanks for the tip, it does seem to be related to that LE article. thanks for the quick response, glad the world isn't broken!

**Comment by bretweinraub** [comment]
Try this if you've not done it since the LE root cert expired.

 sudo apt-get install --reinstall ca-certificates
