### ISSUE TITLE
Problem: package passenger-6.0.11-1.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed

### ISSUE THREAD

**Issue by tikroute** [phusion/passenger#2391]
Hello 
I am trying to install Redmine 4.2.3 with Ruby 2.7.3 
Everything is working fine with webrick but when I want to install Passenger I get the following error: 

`[root@localhost tmp]# sudo yum install -y passenger
Last metadata expiration check: 0:26:45 ago on Tue 19 Oct 2021 08:37:48 AM EDT.
Error:
 Problem: package passenger-6.0.11-1.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - cannot install the best candidate for the job
  - package ruby-libs-2.5.5-105.module_el8.1.0+214+9be47fd7.x86_64 is filtered out by modular filtering
  - package ruby-libs-2.5.9-107.module_el8.5.0+811+d98a1657.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)`

I searched a lot without any luck. Can you please help me?
I can not install Ruby 2.5 because Redmine doesnt support it. 

My OS is Centos Stream 8 and I have enabled Phusion repos.

**Comment by CamJN** [comment]
You do not have to use Ruby 2.5 just because you installed it. You choose the ruby version with the appropriate config option:

Apache:
`PassengerDefaultRuby` : https://www.phusionpassenger.com/docs/references/config_reference/apache/#passengerdefaultruby
`PassengerRuby` : https://www.phusionpassenger.com/docs/references/config_reference/apache/#passengerruby

Nginx:
`passenger_ruby` : https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_ruby

Standalone:
`--ruby` : https://www.phusionpassenger.com/docs/references/config_reference/standalone/#--ruby-ruby
