### ISSUE TITLE
strscan dependency/version

### ISSUE THREAD

**Issue by gdonald** [phusion/passenger#2410]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?

I expect my Rails app to run, like it has for years.

- What is the actual behavior?

My Rails app does not run.

- How can we reproduce it?

I upgraded (compiled from source) my Ruby from 2.7.4 to 2.7.5.  I recompiled Passenger.  I restarted Apache.  I then get this error in the logs:

```
[ E 2022-01-12 00:39:03.6423 100375/T2p age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for
application /path/to/my/rails/app/current: The application encountered the following error: You have already
activated strscan 1.0.3, but your Gemfile requires strscan 3.0.1. Since strscan is a default gem, you can either
remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default
gem (Gem::LoadError)
``` 

**Question 2: Passenger version and integration mode**:

Both 6.0.10 and 6.0.12 produce the same error for me.

**Question 3: OS or Linux distro, platform (including version)**:

Debian 10, Apache 2.4.51

**Question 4: Passenger installation method**:

source tarball

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Rails 6.1.4, Ruby 2.7.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No.

**Question 7: Anything else about your setup that we should know?**

Ruby 2.7.4 works fine for me.

**Comment by minivdweek** [comment]
I can confirm that this also happens when upgrading `actionmailer` to 7.0.1 when using Ruby 2.7.4, since `actionmailer` has a dependency on `strscan` as well (which is then included in the lockfile at the most recent version, 3.0.1). 

As a workaround, locking the `strscan` version to `1.0.3` in your Gemfile until you upgrade Ruby to >=3 (which includes `strscan 3.0.1` by default) will fix the issue. Or upgrade Ruby to >=3, if that's possible for you.

This issue feels like it may be either closely related to or caused by #2409

**Comment by gdonald** [comment]
I can confirm, locking the strscan version to 1.0.3 in my Gemfile works.  Thanks @minivdweek.

**Comment by CamJN** [comment]
fixed, see: https://github.com/phusion/passenger/issues/2409
