### ISSUE TITLE
Ubuntu 22 support, and any possible fixes - Depends: nginx-common (< 1.14.1) ...

### ISSUE THREAD

**Issue by goldingdamien** [phusion/passenger#2436]
I am trying to install Passenger on Ubuntu. Details below:
Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1011-aws x86_64)

Is Ubuntu 22 supported?
If so, how can this issue be fixed?
If not, what is the latest version supported?

Regards.

```
$ sudo apt-get install -y libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (< 1.14.1) but 1.18.0-6ubuntu14.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by uaqben** [comment]
@goldingdamien -- from their documentation latest supported ubuntu versions are:
- 20.04 LTS 
- 21.10

There are builds for 22.04 since last May:
- https://oss-binaries.phusionpassenger.com/apt/passenger/dists/jammy/
- https://oss-binaries.phusionpassenger.com/apt/passenger/pool/main/p/passenger/

However, after having run a test with Rails app, it still feels like WIP, ie. fails to spawn correctly... FWIW: you may want to follow #2428.

**Comment by CamJN** [comment]
Updated the docs, i guess i missed doing that when i added jammy packages.

**Comment by CamJN** [comment]
`libnginx-mod-http-passenger : Depends: nginx-common (< 1.14.1) but 1.18.0-6ubuntu14.1 is to be installed` looks like you have a deb for an older ubuntu version configured, check that `/etc/apt/sources.list.d/passenger.list` says `jammy`

**Comment by goldingdamien** [comment]
@uaqben @CamJN Thanks.
