### ISSUE TITLE
Unexpected error in mod_passenger: An error occurred while receiving HTTP upload data: The timeout specified has expired (70007)

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#589]
_From [timurv2](https://code.google.com/u/117803467800458402514/) on April 27, 2010 15:02:54_

Hey guys,
- OS Cent OS 5.4
- passenger 2.2.11
- httpd-2.2.3, thread-based model, 'worker'

I have a server behind hardware load balancer. And from time to time get
this errors in the httpd error log

[ pid=4329 file=ext/apache2/Hooks.cpp:727 time=2010-04-27 07:48:06.698 ]:
  Unexpected error in mod_passenger: An error occurred while receiving HTTP
upload data: The timeout specified has expired (70007)
  Backtrace:
     in 'void Hooks::receiveRequestBody(request_rec_, const char_,
std::string&)' (Hooks.cpp:1135)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:459)

I'm sure I have no uploads on the app.
Have you ideas what is that?

Thanks,
Timur

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=489_

**Comment by coolgandhi** [comment]
Hello, I understand this issue was closed and it is not related to Phusion. I get this error randomly when I upload video files (~1.5 MB) every 10 seconds on a very similar setup. I have tried to find relevant help on the web but there aren't any clear smoking gun except network issues. Just wondering if anyone here was able to figure out the possible causes/solutions?

**Comment by anthonysomerset** [comment]
i had to set MTU of a server down to 1400 in one case - wonder if that helps you?
