### ISSUE TITLE
Passenger does not log anything if Apache has "ErrorLog syslog" set

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#832]
_From [flameeyes@flameeyes.eu](https://code.google.com/u/flameeyes@flameeyes.eu/) on January 22, 2012 21:07:26_

This seems to be a less critical issue from the similar one in mod_perl (which instead decides to crash Apache), but still bothersome.

Without going to look through the code, just by checking the `lsof -p $pid` output, I see that STDOUT/STDERR of the Rails applications are set to output to the log set in ErrorLog or PassengerDebugLogFile.. but without further warnings it simply drops the whole output if ErrorLog is set to "syslog" in Apache.

I'm not sure if there is a decent way to solve this but at least it should be throwing some kind of warning or error if PassengerDebugLogFile is not set and ErrorLog is set to syslog so that one knows what is going on.

Thanks,
Diego Elio Pettenò

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=733_

**Comment by ioquatix** [comment]
If someone points me in the right direction for where this needs to be implemented I will take a look at it.

**Comment by ioquatix** [comment]
Okay, so I checked where the error is being generated. It's here:

https://github.com/phusion/passenger/blob/9660bb233fc93d3ca73aa8cebe3a663877c8c228/src/nginx_module/ngx_http_passenger_module.c#L295-L301

So, I assume we just need to extract the error_log details and handle basically the same format as nginx (might be a path name, or might be syslog).

**Comment by ioquatix** [comment]
Okay, so I see what the problem is.

Essentially, nginx has an opaque logging data structure which isn't really easy for passenger to use.

For example, there could in theory be multiple error log outputs, formats, levels, etc.

Passenger has to support an abstract input for logging, w.r.t. handling both Apache and Nginx.

I don't know about Apache, but I'm sure it has it's own way of doing things.

An example of the nginx logging function is here: http://agentzh.org/misc/code/nginx/core/ngx_log.c.html#L79

```
void
ngx_log_error_core(ngx_uint_t level, ngx_log_t *log, ngx_err_t err,
    const char *fmt, va_list args)
```

To handle logging, passenger pulls the first file name out of the configuration: https://github.com/phusion/passenger/blob/9660bb233fc93d3ca73aa8cebe3a663877c8c228/src/nginx_module/ngx_http_passenger_module.c#L295

But, that's not really good behaviour because you might have multiple error logs defined with different levels. In any case, passenger always uses the first one.

It would be interesting to know how Apache handles this. But, from what I see, there is only really one logical simple way of handling this in a cross-server way:

The `passenger_log_file` should be set to inherit or some other token.

This should indicate that log output from the child process should be processed upstream by nginx or apache, in the server specific way.

How this works is another question. The main logging output is probably always "error_log" type output, as the access log is irrelevant to passenger (?). Therefore, it might be simplest to open a channel from the server to child process for the error log. When passegner_log_file is set to inherit, it uses the FD for reporting errors (could be stderr, or could be something more specific).

The format could be well defined and then parsed within nginx/apache before being passed to the relevant error log function.

What do you think?

**Comment by FooBarWidget** [comment]
Yes how you described it is exactly right. To fully integrate Passenger's logging with Apache/Nginx's logging (including integration with per-server or per-location logs) Passenger will have to send the logs back to Apache/Nginx so that the log data can be processed by Apache/Nginx's log routines.

There are a couple of challenges though:

1. How do you run an embedded server inside Apache/Nginx which listens for log data from Passenger? How do you integrate with Apache/Nginx's event loop to make that happen?
2. Passenger internally does not support the concept of per-server or per-location logs. Inside Passenger, all logs are treated equally: they are all sent to the same place, namely the log file. So Passenger itself will need to be modified to support this concept, which is a lot of work.
3. If Apache/Nginx crashes or shuts down, then any further logs generated by Passenger after that point are lost.

Would this work be worth it? So far I haven't found a compelling reason. The integration would be nice, but point 3 is a fundamental problem that cannot be solved I think, and we'll have to come up with some kind of way to support per-server/per-location logs in Passenger without making the internal logging API significantly more complicated.

**Comment by ioquatix** [comment]
@FooBarWidget those are all good points. After reviewing the situation further, there are two options I think would be good:

- Logging to syslog
- Logging to /dev/stderr

If either of these options are implemented, the problem would be essentially solved.

I also think that simply pulling the first log file from Nginx is a bad approach. If logging is not configured explicitly, it would be better to log to `/dev/stderr`, IMHO.

**Comment by FooBarWidget** [comment]
Logging to stderr is unfortunately not an option. Normally, Nginx and Apache set stderr to the global error log, so the original stderr is lost. In some configurations (related to all the different daemonization options) Nginx/Apache set stderr to null, causing all logs to be lost.

Even if Nginx/Apache never set stderr to null, logging to stderr will make log rotation impossible. A filename must be known for log rotation to work.

The above two reasons are why we pull a log filename from Nginx/Apache.

**Comment by ioquatix** [comment]
Well, if you log to /dev/stderr it will go to syslog/journald so log rotation would work just fine.

In the case of Nginx or Apache setting /dev/stderr to null, that's a problem. Then the only real option is to support syslog.

**Comment by FooBarWidget** [comment]
> Well, if you log to /dev/stderr it will go to syslog/journald

That's not our experience. We used to log to /dev/stderr but then the logs would just get lost. Maybe it depends on the OS.

**Comment by ioquatix** [comment]
Thanks for your continued attention to this issue.

It would obviously depend on where stderr is going from the parent process. If nginx or apache closes stderr when entering daemon mode, it wouldn't work. This isn't exactly a mystery. It's a pretty common technique to double fork and close all pipes.

I'd probably argue that modern daemons should expect to be demonised by the host system management platform (e.g. systemd, launchd), and just log to stdout/stderr where appropriate. It makes so much sense to me for this to be the default. Then, the system can make a decision about how to log thing. From my perspective, it seems like the most logical thing to do, than every app having it's own logging system, all snowflakes which need to be managed individually, break in strange ways, do strange things, etc.

The reason why I suggested this is because I asked on the systemd-devel mailing list about this exact situation and a workaround I worked on (implementing a fifo which is dumped to journald). They suggested simply logging to /dev/stderr as the most appropriate solution. But, as your and my experience shows, this simply isn't going to work without some major re-thinking of how daemon processes should operate and log errors.

Pending that, syslog is an option that works, works well, and is going to be supported across a wide range of platforms.

¯\_(ツ)_/¯

**Comment by ioquatix** [comment]
Just FYI, here is the discussion..

https://www.mail-archive.com/systemd-devel@lists.freedesktop.org/msg35733.html

**Comment by FooBarWidget** [comment]
This issue has been open for a long time. It seems making Passenger logging work "automagically" when Apache/Nginx are configured to log to syslog, takes quite some effort. It is possible to configure Passenger to log to a custom file, and then configure the syslog daemon to forward that to a server. And depending on the setup (where logging to /dev/stderr works), the user can just configure Passenger to do so.

Given that such alternatives exist, I don't think that an effort to make Passenger logging work automagically, is worth it. So closing this issue.

**Comment by ioquatix** [comment]
Can't you just log to `stderr`?

**Comment by FooBarWidget** [comment]
> I think it would be worth revisiting this issue with at least some way just to log directly to stderr.

To be clear, you are talking about Nginx's *original* stderr, before Nginx has redirected stderr to a blackhole as part of its syslog setup, correct? It is definitely *possible*, just not *easy*. Hence the decision to close is more the result of a cost-benefit analysis, rather than declaring a technical impossibility.

**Comment by ioquatix** [comment]
I don't really know what APIs exist within nginx, but there must be some kind of general error log function, no? If not, I think writing directly to the `stderr` would be ideal since in the cases I can think of, this would just work as expected. In any case, I think it's fine to close this issue, just that I wonder if there isn't an easy fix here.
